### ISSUE TITLE
Different Issue Files for iPhone & iPad?

### ISSUE THREAD

**Issue by BenjaminRPerry** [bakerframework/baker#110]
I recently launched my magazine's app with the following workflow:

Layout in InDesign > Export with In5 > Load Subsequent HTML files to MagCloud/Baker for final viewing in app.

The only problem with this is that I made my app universal, and the end file is laid out for iPad.  It looks small and squished on iPhone.

Is there a way for Baker to call the download of a specific file based on what device is calling for it?  What I be able to lay out iPhone & iPad specific versions?

Thanks

**Comment by kinott** [comment]
Hi.
Any news about this feature?

**Comment by MagLoftMagazines** [comment]
This is also something we plan to implement on MagLoft as we get more requests for it. It's typically InDesign users that have created 2 or more layouts for individual export that would benefit from this feature. We don't have this planned yet in the calendar and it really does depend on the demand for it. So far it is not something a lot of people have requested.
