### ISSUE TITLE
Back to Shelf Javascript call

### ISSUE THREAD

**Issue by ausiuming** [bakerframework/baker#136]
Is it possible to call the back to shelf navigation bar or even go back to shelf directly with a javascript call from the hml pages, instead of double tap ?

**Comment by GennadyK** [comment]
Code for the book:// link inside the BKRBookViewController.m to handle 2 special links:
book://toggleBars
book://shelf

                else if ([[url scheme] isEqualToString:@"book"])
                {
                    if ([[url absoluteString] isEqualToString:@"book://toggleBars"])
                    {
                        [self toggleBars];
                        return NO;
                    }
                    else {
                        // if "book://shelf" then will exit to shelf and try to download nonexistent book
                        [self toggleBars];
                        [self performSelector:@selector(handleBookProtocol:) withObject:url afterDelay:0.4];
                    }
                }
