### ISSUE TITLE
Downloads in Stand Alone (non Newsstand) Mode

### ISSUE THREAD

**Issue by nin9creative** [bakerframework/baker#15]
There seemed to have been a lot of discussion on this one.  Adding it here for tracking...

Reference to prior simbul/baker Repo

---

https://github.com/Simbul/baker/issues/644

**Comment by fransimo** [comment]
Any timing?

**Comment by pieterclaerhout** [comment]
Hi there, 

we currently don't have any timeframe on providing multi-issue apps outside of Newsstand.

However, Twixl Publisher (http://twixlmedia.com/en/publisher) does allow you to create a non-newsstand multi-issue app. If you want more information, feel free to get in touch with me.
