### ISSUE TITLE
Fullscreen PDF and PowerPoint files

### ISSUE THREAD

**Issue by sandor** [bakerframework/baker#213]
Even if that is not intended: Baker can nicely open and display PDF and PowerPoint documents. Basically you can crate a HPUB with some PDF files. If you have multi-page PDF, that can even be showed up in vertically paged mode. Using multiple multi-page documents will give your users a chapter (swipe horizontal) and page (swipe vertical) experience like in DPS. This is really great to show some specific content that does not needs interactions etc.

The only drawback is that the WebView will always show some margins and shadows around the individual pages. I done quite a lot of research on how to get rid of this margin/shadow stuff - till now with no really good results. Quite hard or nearly impossible...

My questions:
- is there anybody that worked on this stuff? A sharable solution for showing fullscreen PDFs?
  If there is no solution for this:
- did one of you found the "ideal pagesize" (in terms of pixels) that would allow a good vertical pagination? The problem here is that i can not clearly take in count how big the gap between the pages are (by scrolling vertically)

Cheers!

**Comment by jbavington** [comment]
I've been looking at embedding PDF's in my Baker magazines.  I tried with one PDF (used for a regular print production magazine), but you are unable to zoom in on a PDF page.  As a result, the 3 columns of printed text or essentially unreadable on an iPhone.

Any idea how to allow zooming in on a PDF in Baker?  My client is sticking with these static PDF's so I can't "massage" them for Newsstand use.

Thanks!

**Comment by MagLoftMagazines** [comment]
We found it much easier to convert PDF's to jpg's and use them as backgrounds in HTML pages, pack them all up in an hpub file and voila, works on iOS and Android.

**Comment by sandor** [comment]
As an alternative you can try out https://crocodoc.com (a box device). It does a nice job by converting PDFs (btw allso Office files) in clean HTML5...

**Comment by jbavington** [comment]
Thanks, crew.  I'll check out the PDF to HTML5 converter.  

Cheers.
