### ISSUE TITLE
K Composite Magazine for iPhone in the App Store

### ISSUE THREAD

**Issue by kcomposite** [bakerframework/baker#240]
The iPhone version of my magazine K Composite (built on Baker Framework and Magrocket) is available in the App Store. Many issues are free and a subscription is only $1 per year. Check it out!

Here's an introductory video http://kcomposite.com/iphone

And here it is on the App Store http://tiny.cc/kcmi

**Comment by Vegals** [comment]
Hey! Loved the magazine! I was hoping if you could give a noobie any advice on changing the buttons to the rounded edge as you have and importing some nice fonts as you have. I've very new to all of this, but would love any information you could provide!

Thanks so much and keep up the good work! :)
