### ISSUE TITLE
Google Web Designer

### ISSUE THREAD

**Issue by ghost** [bakerframework/baker#274]
Has anyone used this to create HTML5 content?

https://www.google.com/webdesigner/

**Comment by themorgantown** [comment]
For folks looking to use Tumult Hype with Baker, here's a tutorial I put together: http://forums.tumult.com/t/embedding-within-the-baker-framework-ebooks-for-the-ipad/1136 

Hype is great for adding a bit of interactivity and movement to a baker production. 

Happy to answer any questions.
