### ISSUE TITLE
When we put up a new issue we have to hit restore purchases every time.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#321]
Each time we upload a new issue we test and check to see if all is working. We have to restore our purchases each time for us to be able to download said issue (we have subscribed to our auto-renewable subscription). Why is this?

**Comment by codegeek511** [comment]
@MagLoftMagazines Hi, I tried to implement https://github.com/Simbul/baker/issues/1062#issuecomment-22324075  to the new version of Baker. Is it still necessary? When I added it there are 8 or so errors. Does the new version fix this issue?

**Comment by MagLoftMagazines** [comment]
As far as I remember you still need to make this change, as it isn't in the Baker master. I'm writing this based on memory, and that has proven to fail before lol ;) The errors you are getting could be due to the missing BKR prefix of the "Utils" if you simply copy/pasted from the fix.

There was someone else who posted something that looked like a very elegant solution, but I can't seem to find that now...

**Comment by codegeek511** [comment]
@MagLoftMagazines here are the errors I get, how do I fix it? Deleting "Utils" did not work
![screen shot 2015-02-19 at 3 48 17 pm](https://cloud.githubusercontent.com/assets/5607372/6278805/e1fc4828-b84e-11e4-83c9-77be0177c21c.png)

**Comment by MagLoftMagazines** [comment]
This is the code you need for the latest Baker:

```objective-c
    - (void)handleSubscriptionPurchased:(NSNotification*)notification {
    SKPaymentTransaction *transaction = [notification.userInfo objectForKey:@"transaction"];
    
    [purchasesManager markAsPurchased:transaction.payment.productIdentifier];
    [self setSubscribeButtonEnabled:YES];
    
    if ([purchasesManager finishTransaction:transaction]) {
        if (!purchasesManager.subscribed) {
            
            [self handleRefresh:nil];
            
            [BKRUtils showAlertWithTitle:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_TITLE", nil)
                                 message:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_MESSAGE", nil)
                             buttonTitle:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_CLOSE", nil)];
        }
    } else {
        [BKRUtils showAlertWithTitle:NSLocalizedString(@"TRANSACTION_RECORDING_FAILED_TITLE", nil)
                             message:NSLocalizedString(@"TRANSACTION_RECORDING_FAILED_MESSAGE", nil)
                         buttonTitle:NSLocalizedString(@"TRANSACTION_RECORDING_FAILED_CLOSE", nil)];
    }
    }

    - (void)alertView:(UIAlertView *)alertView didDismissWithButtonIndex:(NSInteger)buttonIndex
{
    if (buttonIndex == [alertView cancelButtonIndex])
    {
        waitToRestoreTime = 1.0f;
        waitToRestoreTimer = [NSTimer scheduledTimerWithTimeInterval:0.5f target:self selector:@selector(waitToRestore) userInfo:nil repeats:YES];
    }
}

    -(void)waitToRestore
{
    if (waitToRestoreTime == 0)
    {
        [waitToRestoreTimer invalidate];
        [self handleRefresh:nil];
    }
    waitToRestoreTime--;
}
```

**Comment by codegeek511** [comment]
@MagLoftMagazines Thanks! No errors!
