### ISSUE TITLE
What is going on with Baker?

### ISSUE THREAD

**Issue by mtamony** [bakerframework/baker#342]
I built a magazine with it about a year ago and it worked ok. I am revisiting building an enhanced publication again and I am not sure what is happening with Baker. The GitHub files are pretty old, no updates, some kind of lead change that I'm not really understanding. Is there supposed to be a better way to create the magazine now? Is there a paid version that is updated or better to build with? Laker was actually kind of cool and that seems to have tanked too.

Any insight would be great.

**Comment by akeilox** [comment]
Been out of touch but curious about the status of the project.

Has it been completely shelved or forked to another project?

**Comment by tobiasstrebitzer** [comment]
Hi @akeilox,

I'd say neither is the case :-)

## Project State

The Project in it's current shape **is stable** and there are probably more than 100 apps out there live in the App Store that are based on the Baker Framework. It's not a out-of-the-box unicorn solution, and doesn't do many different things, but what it's built for, it does quite well.

## Open Source Development

Development in the Open Source department stagnated quite a bit, and you shouldn't expect this repository to make it in the "trending" section on Github. But having that said, there's enough involvement to keep the project stable (e.g. IF a new iOS version brings breaking changes).

There are some companies involved backing the project (@MagLoft, where i'm involved, @pieterclaerhout from Twixl Media, and others), and contributions are being made ... occasionally.

We're releasing an update to the Baker/MagLoft branch soon (1-2 months from now), where we release the features that work without breaking existing publishing backends.

## Summary
1. If you're looking for an actively maintained, quickly evolving project, Baker **IS NOT** for you.
2. If you need QUICK support and help on issues and bugs you encounter without digging into the code yourself, Baker **IS NOT** for you.
3. If you need a grown, proven and ultimately reliable product for publishing your content, and are willing to commit time and energy into getting it up and running, Baker **IS** for you.

That's kind of my personal view on it, and not a coordinated reply from the parties involved in Baker. I'm happy to be challenged :-)

**Comment by akeilox** [comment]
@tobiasstrebitzer many thanks for the thorough explanation.

I wasnt very sure how Baker stand after the discontinued Newsstand, I assume the current users are all using Baker as a standalone app?
And what is your view with the NewsStand replacement, like News - how Baker can be fitted with such change? I am particularly interested to understand this aspect.

Thanks again

**Comment by tobiasstrebitzer** [comment]
Hi @akeilox,

thanks for these great questions!

## The Long Answer

When Apple removed the newsstand - all newsstand-based apps continued to be supported. While there's no more Newsstand-App, existing apps were simply moved into a new Folder called "Newsstand" (while new app installs went straight to the app screen).

From my experience, the community has - contradictingly - appreciated the removal of the Newsstand. Newsstand-Apps didn't disappear, they were relocated. Back in the Apple Newsstand times, there wasn't really any promotional benefits from items located in the Newsstand. They were located in a _sub-sub-category_ in the App Store. By many, they were even perceived as _less visible_, as they were not accessible from the main app screen, like all _regular_ apps.

Looking at current app category statistics, the share of News and Magazine- related apps is still growing (although there's a shift happening towards article- based content VS issue-based content).

With Apple News (as well as similar services becoming more and more prominent, like Facebooks' Instant Articles or Google's Accelerated Mobile  Pages), they are following the trend of how content is consumed generally i feel... more narrowed down to small and specific articles about very specific content... just like finding an answer to a specific question.

I do - however - still believe in the value of magazine-like content. Here, it's more about the experience while consuming a magazine, the trust in the quality of contained articles, and a more broad and generic exploration of a topic.

## The Short Answer

To me, the _natural_ differences in digest- and magazine based content justify the existence of both, side by side. Also, serving teasers of your magazine to news platforms - luring interested readers to your magazine - is a quite effective approach. An adaptive magazine publisher utilizes the new prominence of news- portals and apps as a leverage for his magazines and content.

**Comment by akeilox** [comment]
Hi @tobiasstrebitzer 

Many thanks for the thorough explanation. I'm sure that answers a lot of questions for many people.
