### ISSUE TITLE
Repeated requests for iTunes Store login

### ISSUE THREAD

**Issue by lyndonl** [bakerframework/baker#346]
I'm in the final stages of approval with Apple but my app now keeps prompting to Sign in to iTunes Store where it didn't before on both my iPhone (iOS8) and iPad (iOS7).

The issue seems to be preventing the app from loading on my iPad  when building in Xcode as well:

error: failed to launch '/private/var/mobile/Applications/AD121D1A-008C-4FFF-B952-4A13CF30AE4A/magazine1878.app' -- process launch failed: timed out waiting for app to launch

presumably because it times out while the iTunes Store login prompt comes up. I didn't have this problem until my latest build and the addition of the second issue of my magazine.

I'm using the Baker Server API to handle subscriptions and, according to the logs and the Data Browser in the Baker Console, the subscriptions, etc are working fine.

The Advanced FAQ references this issue:

"If you've set the PURCHASE_CONFIRMATION_URL constant, make sure that the server is responding correctly:" 

but I don't know how to test for this.

Any ideas as to what the problem might be?

---

UPDATE:

This issue does not happen when testing on two separate iPads in Testflight on iOS8.

**Comment by ojkelly** [comment]
I believe this is related to an issue I had that is fixed with this PR #407
