### ISSUE TITLE
Baker Standalone App and In-App Purchase

### ISSUE THREAD

**Issue by LuxViz** [bakerframework/baker#379]
QUESTION
Has anyone created a standalone Baker app and also implemented in-app purchases? Would you be willing to provide some paid Skype consulting to help us understand how in-app purchases work with standalone apps?

BACKGROUND
We have an approved standalone iPad app called Bali's Finest Villas which was designed to "promote indulgent luxury travel" to Bali by showcasing some of the most exclusive villas here. This app has been developed using the Baker Framework with HTML5 and Javascript, but also with some additional functional components in Objective C.

We're almost finished with some major revisions to the content organization, functionality, and layout for the app. The next release will support all iOS devices, and we will also publish an Android version that will also support both tablets and phones.

Our initial plan has been to release a free SD (standard-definition) version, and then start charging for an HD standalone version of the app. We intended to release new "issues" of the app about every 3 months with a new selection of 10 luxury villas.

We're now reconsidering that strategy and are wondering about keeping one version of the app, and making the SD version of the Premiere Issue free, but then the HD and SD versions of all other issues would be offered as in-app purchases.

However, we would really like help in understanding any architectural changes we need to make to our existing app, as well as receiving knowledgable consulting about the wisdom of this new strategy.

Is there anyone with experience with a standalone Baker app that supports in-app purchases who might be willing to help us out with some paid Skype consulting?

Thanks,
Rick

LuxViz
https://itunes.apple.com/us/artist/luxviz/id796339928#

Bali's Finest Villas - SD Version (for iPads with normal displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-sd-english/id879332125?ls=1&mt=8

Bali's Finest Villas - HD Version (for iPads with the retina displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-hd-english/id880005823?ls=1&mt=8
![01 cover](https://cloud.githubusercontent.com/assets/9841038/5106847/732b3300-7037-11e4-8634-043d18f67a89.jpg)
![02 villa sungai](https://cloud.githubusercontent.com/assets/9841038/5106848/732f7172-7037-11e4-9249-49a35ef33586.jpg)
![03 sanctuary bali](https://cloud.githubusercontent.com/assets/9841038/5106849/73316c70-7037-11e4-9769-302f1a9bb15f.jpg)
![04 sound of the sea](https://cloud.githubusercontent.com/assets/9841038/5106851/7332a7d4-7037-11e4-8624-6f956029da19.jpg)
![05 bali article](https://cloud.githubusercontent.com/assets/9841038/5106850/733293f2-7037-11e4-8f38-37232c1359ea.jpg)

**Comment by pablomateo** [comment]
Hi, We´ve developed an iPhone / iPad app with In-App Purchases and Subscriptions and works like a charm. If you still need help with this issue, please let me know and I´ll try to help you.

**Comment by fransimo** [comment]
Hi @pablomateo is yout app HPUB comptible?

**Comment by pablomateo** [comment]
Hi Fran!
Yes, it´s developed with the Baker Framework and it is fully compatible
with HPub.

**Comment by MagLoftMagazines** [comment]
Hi @pablomateo that sounds very interesting! I wasn't sure if you had extended the Baker Framework to work as a standalone with IAP, but it sounds like that's exactly what you have done! Very awesome. Is this something you would like to share with the Baker community? If so, I know @tobiasstrebitzer would be happy to help merge/adopt your changes to Baker :)

**Comment by pablomateo** [comment]
Sure! Let´s contact.
It isn´t fully finished, but it will be soon.

**Comment by tobiasstrebitzer** [comment]
Hi @pablomateo, that's great news! i remember plenty of people here in baker looking for exactly that!

If you need any help, just let me know!

**Comment by nin9creative** [comment]
That would be awesome!
