### ISSUE TITLE
Suggestions for Framework 3.1

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#394]
An idea that came to my mind working with the new header : 
-> would be great to be able to have the header as an external link to an image hosted on the server : would allow to change it at will, and so do funny stuff (add snow for christmas, etc) and fine marketing (promoting special offers, or new issue, special issues etc...)

**Comment by Sror** [comment]
future implemented in Newsstand Template in Codecanyon:
http://codecanyon.net/item/newsstandtemplate-v20-with-inapp-purchases/8046271

**Comment by thejoepeach** [comment]
the only thing that looks promising is the image slides, the rest is poorly implemente compared with baker...  also i believe Baker only need this or the webview option  to be even better... the rest of those things in with Baker can be better are related to the creativity of all of us....
