### ISSUE TITLE
newsstandManifestUrl

### ISSUE THREAD

**Issue by oscarwu** [bakerframework/baker#398]
i revise baker 4.3  in  newsstandManifestUrl "json" code , but why can't show my json data, is show baker 4.3   default "json" data

**Comment by MagLoftMagazines** [comment]
Hi @oscarwu 

Not sure I completely understand your question. You might want to try and clarify a little more? The way I read it is, you updated the newsstandManifestUrl in the settings.plist to your own path to your manifest file, but you are still seeing the default Baker info?

Can you share your manifest URL?
