### ISSUE TITLE
Shelf lay-out

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#399]
Not really an issue but an improvement suggestion :+1:
Since the new framework, the lay-out of the shelf has changed. 
![howitis](https://cloud.githubusercontent.com/assets/8971320/5456752/084c3dee-8546-11e4-961e-e42e852fc973.jpg)
-> from an art director's p-o-v, the lay-out in the shelf seems a bit unbalanced. There is not enough space on the left gutter. In fact, I feel that the lay-out was more balanced in the previous Framework release.
In fact, the previous lay-out was fine!

Just a suggestions, though ;-)

**Comment by tobiasstrebitzer** [comment]
@NemoMag It definitely looks better as it matches the header size of your magazine. I think other apps might use a broader, narrower or even full-width header, where the current spacing is ok.

@pieterclaerhout Maybe there's a chance to have the gutter / spacing configurable in settings.plist? It might not be trivial, as too much spacing will mess with the contents of the shelf issue view (not enough space...).

**Comment by MagLoftMagazines** [comment]
Hi @NemoMag,

Care to share what code you changed in order to make the gutter wider? I can add it as a setting for later use.

**Comment by pieterclaerhout** [comment]
@tobiasstrebitzer I'll look into next week (I'm currently on holidays).

**Comment by NemoMag** [comment]
@tobiasstrebitzer : ok ;-) But, IMO, the trouble is not 
@ pieterclaerhout : sorry in fact i just changed it on the screenshot, to show you. 
I would love to be a decent code master and to locate the code and tweek it myself, but... 
well, I'm still learning!
