### ISSUE TITLE
How to change in Baker Framework the double tap on one tap?

### ISSUE THREAD

**Issue by WaterSoloGur** [bakerframework/baker#403]
Hello!
Now Baker Framework to display the menu need to double tap on the screen. It is not usual for many users. How do I change it? It would be desirable that the menu in the magazine opened one tap. 
Thank you.

P.S. Sorry for my bad English.

**Comment by pieterclaerhout** [comment]
@WaterSoloGur This is a tricky one to do, as it's very hard to detect a single tap on a webview without breaking something. One option would be to add a custom url scheme that can be called from within the html which can trigger the menu.

**Comment by nin9creative** [comment]
It'd be interesting to see, but I'm curious how you'd be able to tell what the user intended vs tapping something on the webview.  Especially if there are interactive JavaScript elements etc on the page....

Sent from my iPhone

**Comment by pieterclaerhout** [comment]
I've added the following custom URLs that you can use in a Baker article:

* baker-toc://show
* baker-toc://hide
* baker-toc://toggle

This allows you to show, hide and toggle the navigation bars from within the html. This allows you to fix the issue with the double tap to show/hide the navigation bars, however, it requires you to alter the HTML. In Twixl Publisher, we suggest the following:

1. Use a jQuery plugin such as Hammer (http://hammerjs.github.io/jquery-plugin/)

2. Then add the following code to each page (or include it from an external javascript file)

```javascript
$('*').hammer().on('tap', function(e) {
    var target = e.target || e.srcElement;
    if ($(target).hasClass('baker-prevent-navigation') || $(target).prop('tagName').toLowerCase() == 'a' || $(target).parents('a').length > 0) {
        return;
    }
    window.location.href = 'baker-toc://toggle';
});
```

The JavaScript code prevents the display of navigation bars when you tap on:

* An element that has the css class ```baker-prevent-navigation```
* A ```a``` element
* An element that is a child element of a ```a``` HTML element

You might ask yourself why we are making the solution so complicated. It basically has to do with the fact that in an iOS environment, you don't have that much control over a UIWebView element. The only thing you can really do is to catch a url when it's loaded (but only some of them, not e.g. the loading of CSS files, JS files, images, ...). So the only way to handle it is to tackle it from within the HTML.

I'm not sure if the WKWebView classes allow more control, but we can't use these classes yet as there is no support for loading HTML from file urls...

**Comment by GennadyK** [comment]
Hi Pieter,
Could you please help us debug this problem - the custom URL links are not working. This is what I'm getting in debug window for the very 1st click on any of them:
2016-11-10 12:19:59.614651 Baker[332:29378] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-11-10 12:19:59.615595 Baker[332:29378] [MC] Reading from public effective user settings.

Is there anything I'm doing wrong or didn't configure it properly? Below is what we are trying to accomplish from this post: https://github.com/bakerframework/baker/issues/544

TIA,
Gennady

2. We also have at least one book, that we use app custom URL link inside to exit to the shelf, as that book wasn't developed by us and is capturing all the touch controls on the screen, making tap to navigation bar not working. In this post there are 3 app links added to call navigation bar:
#403
So we would like to add the 4th one:
"baker-toc://shelf"
Although those special app links are not working for some reason - I’m not getting that NSLog line in debugger,
could, please, someone help with what and how that exitToShelf function should be called inside the code below and how to fix the code so those custom URLs will start work again:

         else if ([[url scheme] isEqualToString:@"baker-toc://shelf"])
         {
             NSLog(@"[BakerView] - exitToShelf"); // call exitToShelf function
             return NO;
         }
Thank you so much,
Gennady

**Comment by GennadyK** [comment]
@pieterclaerhout 

> You might ask yourself why we are making the solution so complicated. It basically has to do with the fact that in an iOS environment, you don't have that much control over a UIWebView element. The only thing you can really do is to catch a url when it's loaded (but only some of them, not e.g. the loading of CSS files, JS files, images, ...). So the only way to handle it is to tackle it from within the HTML.
- interestingly, Pieter, Adobe's Viewer app somehow is only getting tap event if HTML page is letting it through and I think they use UIWebView for web pages. If tap is captured on the HTML page level for the whole 1024x768 web view, then we need that link URL to get back to shelf.

**Comment by pieterclaerhout** [comment]
Hi,

Most probably, Adobe is injecting some custom JavaScript code in the HTML to make it work, but it would suprise me if this work flawlessly all the time.

Just my 2 cents.

Pieter

**Comment by GennadyK** [comment]
Hi Pieter,
Thank you for you reply. Could you please let me know why those 3 custom URLs that you added 2 years ago might not work (see the post above)? And maybe how to call right function in the 4th "baker-toc://shelf" custom URL? I'm new to Xcode, so some of the stuff is hard to figure out for me yet :)

TIA,
Gennady

PS: As for the single tap it works well in Baker - we just need to tell UIWebView to not toggle navigation bar when tapped on the link inside HTML. There are some solutions offered here (the javascript solution to intercept touches on the DOM itself is the 1st among them), but I'm not as good with Xcode to comprehend those yet:
http://stackoverflow.com/questions/1396355/detecting-taps-inside-a-uiwebview
Also here there is one other answer that looks interesting:
"I've just found that UIWebView does check whether it responds to the - (void)webViewDidNotClick: (id)webBrowserView selector, once one taps on the view area (not on hyperref, or any other area that should be handled specifically)"
http://stackoverflow.com/questions/990870/handling-touches-inside-uiwebview#answer-3867094
