### ISSUE TITLE
Subscription Text Issue in Baker 4.3 iOS8

### ISSUE THREAD

**Issue by jondean73** [bakerframework/baker#405]
I'm using the new version of Baker (v.4.3) and building for iOS8.1 and I'm having an issue where the subscription text isn't being replaced with the values from the Localizable.strings file.  The subscription button displays the text from iTunes connect, which is a bit confusing for the user if we're offering more than one subscription.

Here are the values in the Localizable.strings file which outlines the 2 in-app purchase ID's and the text:

![localizable](https://cloud.githubusercontent.com/assets/854244/5628160/48496826-959b-11e4-9e6d-0a46c365faa9.png)

And here's the screenshot of the app which has the descriptions being pulled from iTunes Connect:

![app](https://cloud.githubusercontent.com/assets/854244/5628182/9dd20dac-959b-11e4-8e32-ae767a0e6bd1.png)

I've tested both on the Xcode previewer tool and also on a physical device (iPad).

Am I missing something simple, or is there an issue with the text replace?

Cheers,
Jon.

**Comment by feralbob** [comment]
Some other people complained that it wasn't coming from iTunes connect for some other localized content. 

Looks like we should make it a flag. I'll look to do that today. 

Sent via my magical pocket Internet device thingy.

**Comment by jondean73** [comment]
Cool, thanks :)

**Comment by feralbob** [comment]
Hopefully in #1255 subject to review

**Comment by pieterclaerhout** [comment]
I've merged the pull request.

**Comment by jondean73** [comment]
Tested and it's now working, cheers :)

![subs-text](https://cloud.githubusercontent.com/assets/854244/5630495/411b9dec-95b6-11e4-92ed-1a78ecf3265f.png)
