### ISSUE TITLE
app don't show content in newsstand

### ISSUE THREAD

**Issue by nickiscoding** [bakerframework/baker#408]
Hi,
I have a problem with last baker app, I compiled it over a real ipad, the app open up and then the shelfs are empty. 

pressing reload I can see the message in the debug 

myApp[258:18908] Received 1 products from App Store
2015-01-09 18:15:54.680 myApp[258:18908] - com.myApp.free.books
2015-01-09 18:16:03.342 myApp[258:18908] Setting newsstand cover icon from latest issue: (null) at (null)

I have no issues loaded on the iTunes Connect,  and the link to the json file in the app is correct, 
I've created the app in iTunes connect, then created the InAppPurchase product id (com.myApp.free.books)  that is maked as "ready to submit"  , is right ?

where can be the problem? 
thanks for help.

**Comment by MagLoftMagazines** [comment]
What backend are you using or did you not change any end points innthe settings?

**Comment by nickiscoding** [comment]
Hi, I'm not using any backend,  I uploaded the .json file, the .hpub and the cover image in .jpeg format. All file are accessible, with my previous app all is working good... 

The new versione requires the use of Magrocket to work ? 

thanks

**Comment by nin9creative** [comment]
No it doesn't require a server backend if you are just doing free issues/subscription.  Still should work...

Sent from my iPhone

**Comment by nickiscoding** [comment]
It's strange ... I used the previous version of baker on other projects without problems, on this project I used the last version with Xcode 6.1.1 and can't solve this issue... 

it's strage this message that tells there's one product  (on the .json there's is one book)

myApp[258:18908] Received 1 products from App Store

can anyone help me ? there's any check I can do ?

thanks a lot

**Comment by nickiscoding** [comment]
anyone has some news about that issue? thanks

**Comment by MagLoftMagazines** [comment]
Can you paste a link to your manifest file (newsstandManifestUrl)?

**Comment by nickiscoding** [comment]
Here is the manifest file 

http://www.stefanoscata.com/apps/shelf.json

thanks

**Comment by nickiscoding** [comment]
I found the problem.  It was a à character used in the title of the issue in the son file of the manifest. 
the ò à è é chars broke the reading of the json.  
I also tried to save the file in UTF-8 format, but no way.

At the moment I removed the accent chars and all is working!

**Comment by GennadyK** [comment]
There is a problem with different tools/editors claiming that they convert/save in UTF-8, but with completely different results. The one below does it the right way for the Baker/Objective-C to decode.
Basically you need these codes instead of ò à è é:
Ã² Ã  Ã¨ Ã©
Please note - there is invisible second symbol for à just behind that Ã.
Also you need to use this link to encode, as copy-paste from above might not work:
http://www.cafewebmaster.com/online_tools/utf8_encode
Operation: UTF8 encode
