### ISSUE TITLE
Progress bar not working in Newsstand

### ISSUE THREAD

**Issue by bsjosten** [bakerframework/baker#409]
Hi,

When I download issues with the newsstand app, the progress bar does not show progress. I just sits at 0 while downloading, and then the download suddenly finishes. Everything else works just fine.

Running on 4.3.

Am I missing something?

Thanks,

/Bo

**Comment by nin9creative** [comment]
How are you hosting the file for download?

Andrew


________________________________

**Comment by bsjosten** [comment]
I have tried two different alternatives:

On our own website, hosted at Hostgator, and

On the MaxCDN network, in what they call a push zone

The download progress bar works on neither.

/Bo

**Comment by bsjosten** [comment]
I'm wondering if I'm missing something. Is there some setting in the configuration or code I have to change to make it work?

/Bo

**Comment by MagLoftMagazines** [comment]
That sounds very strange. There are no settings for the downloading bar, so that's not the case.

**Comment by nin9creative** [comment]
Check out this old thread from the other repo.

Not sure if it's a similar issue.

https://github.com/Simbul/baker/issues/752



________________________________

**Comment by bsjosten** [comment]
Checked the thread you suggested, and that helped. It is indeed the "expectedTotalBytes" that gets set to zero. Unfortunately, the .htaccess line suggested didn't solve the problem.

For now I just put in a fixed value for expectedTotalBytes, since all my issues are similar in size. Then at least the progress bar resembles the truth, and the user get the notion that something is happening.

One question/suggestion: The unzipping at the end of the download takes a significant amount of time. It would be nice if another state was added, say "Unpacking" after the download is complete, so the user knows what he is waiting for. Most users have more patience if they know what is going on, and are not just left hanging.

Thanks for the help.

/Bo

**Comment by kcomposite** [comment]
Adding this line to my server's hatches file fixed the problem for me:

<code>AddType application/hpub .hpub</code>
