### ISSUE TITLE
App rejected because "it stores data on iCloud" ???

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#410]
My app was was rejected. Here is the comment I got.

"----- 2.23 -----
We also found that your app does not follow the iOS Data Storage Guidelines, which is required per the App Store Review Guidelines.
In particular, we found that on launch and/or content download, your app stores 2.75 MB. To check how much data your app is storing:
- Install and launch your app
- Go to Settings > iCloud > Storage & Backup > Manage Storage 
- If necessary, tap "Show all apps" 
- Check your app's storage
The iOS Data Storage Guidelines indicate that only content that the user creates using your app, e.g., documents, new files, edits, etc., should be backed up by iCloud. 
Temporary files used by your app should only be stored in the /tmp directory; please remember to delete the files stored in this location when the user exits the app.
Data that can be recreated but must persist for proper functioning of your app - or because customers expect it to be available for offline use - should be marked with the "do not back up" attribute. For NSURL objects, add the NSURLIsExcludedFromBackupKey attribute to prevent the corresponding file from being backed up. For CFURLRef objects, use the corresponding kCFURLIsExcludedFromBackupKey attribute. 
For more information, please see Technical Q&A 1719: How do I prevent files from being backed up to iCloud and iTunes?.
It is necessary to revise your app to meet the requirements of the iOS Data Storage Guidelines. "

I didn't tweet the code of the Framework (latest version) though... Any idea what this is ?

**Comment by jakeosx** [comment]
I would check the settings on your in app purchases. While I was recently updating mine I accidentally set it up so Apple was hosting the data files. 

Not sure if that is it, but first thing that came to mind.

**Comment by NemoMag** [comment]
No, it isn't this. It is more a code-level thing.

**Comment by pieterclaerhout** [comment]
That's really weird. I just confirmed with Baker 4.3 that if you configure it as a Newsstand app, it only stores data in the Caches folder, which is the way it should work. I also tested it for a non-newsstand app, and the result it the same.

One thing you could do is the following:

1. Run the app on your device

2. Hook up the device via the USB cable to your computer

3. Start Xcode and go to Window > Devices

4. Select the correct device and look for your app in the list of installed apps

5. Select the correct app and select "Show Container" from the gear menu. It will list all the files that are in the sandbox of the app and are subject to being backed up.

Based on what files are in there, we can see if these are created by Baker or not.

Is there any customization you have done to the app? Which version of Baker did you use for the app?

**Comment by NemoMag** [comment]
![Uploading Capture d’écran 2015-01-13 à 11.55.45.png . . .]()
Here are the containers. no documents it seems... 
I did not customize the code. Just the settings as mentionned in the Baker tutorial.

**Comment by NemoMag** [comment]
![capture](https://cloud.githubusercontent.com/assets/8971320/5719801/27d7980c-9b1c-11e4-9678-95acf58b85eb.png)

**Comment by pieterclaerhout** [comment]
@NemoMag Do you have iCloud enabled by any chance in your provisioning profile? You can check this in your application id in the provisioning portal.

**Comment by NemoMag** [comment]
No . just checked. Only Game-center/In-app purchases/Push Notifications...
And in Xcode/Capabilities iCloud is OFF.

I'm wondering if there wasn't some mistake on Apple side at verification.
There is no reason the app can uses iCloud if it ain't ON in Xcode or in provisionning, isn't it ?
Somewhere else ?

**Comment by pieterclaerhout** [comment]
It might indeed well be a mistake from Apple during the verification.

Have you check the procedure they suggested?

**Comment by NemoMag** [comment]
Yes i did. I couldn't see any file in iCloud storage in my iPad. Several tries.

**Comment by NemoMag** [comment]
I posted a developer Tech support inquiry.
Here is their answer : 
Hello,

I am responding to your inquiry about how to make sure your app complies with the App Review guidelines.

The reason for this rejection is that you have files in your app which are being backed up to iCloud. iCloud backups are user controlled and any files in the Documents directory (and Library directory as well) will be automatically backed up, regardless of you using iCloud explicitly in your app or not.

The solution for this is to use the Documents and Library directories sparingly, and only for user generated data.
If there are files you are downloading or copying from your bundle into these directories, and they must be located there, then you need to flag them as do-not-backup. This way, they won’t be using iCloud space.

Please follof the directions in this document: <http://developer.apple.com/library/ios/#qa/qa1719/_index.html>

Once you've correctly excluded your data files,  you can run the following tests on your apps:

- Exhaustively test your app in the simulator, and verify directly that the "do not backup" flag is being set correctly in every case.  I'd also recommend checking at several points during the process.  In at least one case, an app was inadvertently setting the attribute before the file was actually created.  The problem fixed itself if the app was run more than once, but since App Review happened to have only run the app once it wasn't working properly.

The simplest way to test this is to run your app in the simulator, then run this command against the relevant files;

xattr -l <file name>

It will list all of the extended attribute attached to that file, and the do not backup attribute should be obvious.

Then test, test, test.  Pay particular attention to the first installation scenario that App Review will experience. Delete your app, install it, run it once, test out all your features, then check your backups.  Do NOT run the app a second time before examining your data, as that could conceal bugs.

**Comment by NemoMag** [comment]
The link for suggested code gives this : 

Listing 1  Excluding a File from Backups on iOS 5.1

- (BOOL)addSkipBackupAttributeToItemAtURL:(NSURL *)URL
{
    assert([[NSFileManager defaultManager] fileExistsAtPath: [URL path]]);
 
    NSError *error = nil;
    BOOL success = [URL setResourceValue: [NSNumber numberWithBool: YES]
                                  forKey: NSURLIsExcludedFromBackupKey error: &error];
    if(!success){
        NSLog(@"Error excluding %@ from backup %@", [URL lastPathComponent], error);
    }
    return success;
}

**Comment by NemoMag** [comment]
btw, I keep on finding no files on my iPad saved by my app in iCloud.
Settings > iCloud > Storage & Backup > Manage Storage has nothing about my app...

**Comment by NemoMag** [comment]
Hello friends! Any idea to help me on this ?

**Comment by pieterclaerhout** [comment]
@NemoMag I would resubmit the app as is and hope that this is just a glitch in their verification process.

If not, try to get in touch with them and ask them if they can tell you which files it's all about.

Just my 2 cents.

**Comment by NemoMag** [comment]
You were right. Second time was ok. How weird ;-)
