### ISSUE TITLE
Update to 4.3

### ISSUE THREAD

**Issue by jblenda** [bakerframework/baker#411]
Hello to all the community, I have a simple and maybe a silly question. 
A year ago I managed to publish a free newstand app following this tutorial (https://github.com/bakerframework/baker/wiki/Tutorial-for-Newsstand-with-Free-issues) and now I want to update my app to 4.3 version.  Do I need to use the same Xcode project and replace some files or should I start from scratch?
Can anybody shed some light on the steps I need to follow to achieve this?
Thank you.
Jose.

**Comment by MagLoftMagazines** [comment]
Hi Jose,

I think the easiest solution for you would be to:

1) download the new version
2) customize it with your settings and graphics
3) create a new version in your iTunes Connect account
4) validate and upload the new Baker version from Xcode

Basically start from scratch.

If you know a little git, then you could clone the latest repo, and pull in changes later as they are added here. Hope this helps.

**Comment by jblenda** [comment]
Yes it helps ;)
Thank you MagLoftMagazines
