### ISSUE TITLE
Baker School

### ISSUE THREAD

**Issue by thejoepeach** [bakerframework/baker#412]
What if we make here a Baker School so anyone can learn all the tricks and tecniques we learn in the road.... i mean we can upload some lessons for newbies and also show how to make the HTML more optimized for baker....

I offer myself as helper in the HTML part.... so what you think?

**Comment by codegeek511** [comment]
I think that would be awesome. There is however a tutorial already on Udemy.com. Made by Peter Moxon (I think that is his name). And he goes through the steps of making a magazine with Baker. However a more detailed on and maybe one including using Mag Rocket for the paid subscriptions would be ver good as well. Also that tutorial costs money so if it were free that would be great as well : )

**Comment by pieterclaerhout** [comment]
I'm quite fond of the idea, but I would try to make it as vendor-independant as possible.
