### ISSUE TITLE
Few 4.3 Questions

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#414]
The button seems to be lower than usual, it looks right on the iPad, this is a screen shot from my iPhone 6 plus. And I am running the newest 4.3 release.

![img_7253 3](https://cloud.githubusercontent.com/assets/5607372/5867864/49f15338-a256-11e4-847d-86e614691370.PNG)

Also in the BakerAsssets.xcassets what is the difference between the newsstand-app-icon and the AppIcon. The newsstand-app-icon is new in the 4.3 version not sure what is different about it.

and lastly my Subscribe button will not show up
Thanks

**Comment by codegeek511** [comment]
@pieterclaerhout  Have you or anyone else had a chance to see this?

**Comment by pieterclaerhout** [comment]
@codegeek511 The reason the subscriptions button is not showing up has probably do with one the following two reasons:

* The product identifiers of the subscription(s) are not entered in the ```Baker/settings.plist``` file.
* The product identifiers are not defined in iTunes connect

For the assets, the newsstand-app-icon is the default cover that is shown the first time you install the app. The AppIcon is used as icon for non-newsstand apps.

For the button, I will have to check what is going on.

**Comment by codegeek511** [comment]
@pieterclaerhout Ok thanks so much. As for the Subscribe button, I though I had the ID for my subscription in the autoRenewableSubscriptionProductIds Array but I accidentally made it outside of the array.

**Comment by codegeek511** [comment]
@pieterclaerhout Have you gotten anywhere on the button height? We are trying to release the app as soon as we can, this issue is not a big deal but I would like to fix it.

**Comment by codegeek511** [comment]
@pieterclaerhout anything new?

**Comment by pieterclaerhout** [comment]
Sorry, no news yet. I've been very busy the last weeks and haven't had time to look into it.

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511,

We've had a similar issue before. try to change the line
```objc
heightOffset = 130 + textLineheight + 10;
```
to
```objc
heightOffset = heightOffset + textLineheight;
```
in [BKRIssueViewController.m line 221] (https://github.com/bakerframework/baker/blob/master/BakerShelf/BKRIssueViewController.m#L221)

**Comment by codegeek511** [comment]
@tobiasstrebitzer Worked like a charm. Thanks!
