### ISSUE TITLE
Twixl Publisher 4.0 released

### ISSUE THREAD

**Issue by pieterclaerhout** [bakerframework/baker#416]
Hi all,

Twixl Publisher 4.0 was released this morning.

Version 4.0 is the first version of Twixl Publisher that supports phones in addition to tablets. But more important, it's the first version that integrates the Baker framework. This opens up our complete toolchain to support the HPub file format in addition to PDF files and Twixl Interactive Publication files.

Currently, HPub is supported for iOS only, but support for HPub on Android will be provided in a future update. Twixl Publisher 4.0 incorporates the Baker framework version 4.3, but has some extra additions not available in the stock version of the Baker framework:

http://docs.twixlmedia.com/m/twixl-distribution-platform/l/284780-how-to-prepare-hpub-publications

You can read all about this release on:

http://blog.twixlmedia.com/twixl-publisher-4-0-is-now-available/

Kind regards,

Pieter
_Twixl Publisher Lead Developer_

**Comment by thejoepeach** [comment]
Amazing pal, i already recomend this solutions to a number of clients, they are amazed...

**Comment by pieterclaerhout** [comment]
Great, thanks. We are working very hard on adding support for Android in the same easy way as what we did with the iOS version.
