### ISSUE TITLE
Issue with iPad rotation in 4.3

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#419]
Issues when I rotate my screen on my iPad. First the issues showed up in a single column when the iPad was portrait, then after a few more rotations it switched to two columns in portrait mode. Also the descriptions get two long  and when in portrait mode they run into the other issues. Only some of the Issues do this though, not all the Issues have the same length of description

The reason I would like to be able to rotate the iPad into landscape is so that the readers can watch the videos in the magazine in landscape view and not be limited to portrait.

On the iPhone it has worked fine so far, but their is still the oddity of different length descriptions.
Is anyone else having this issue?

Thanks.

**Comment by akread** [comment]
Yes, I am having rotation issues on my iPad with 4.3 on iOS 8.1. This issue seems to be only occurring for me in the issue view. See my screenshot attached. This occurs a bit and we cannot push and update in the app store until this is resolved.

I am diving into the code now to see if I can figure out why it is happening.

![image1](https://cloud.githubusercontent.com/assets/6855046/6158083/fc0db7b4-b214-11e4-98f1-c4a7ff3b8063.PNG)

**Comment by codegeek511** [comment]
@akread have you found out anything?

**Comment by MagLoftMagazines** [comment]
I know this is not ideal, but if you grab the latest baker, can you reproduce this behavior? Have you made any customizations?

@akread when you say:

    when the issue is locked in portrait the status bar still rotates

Does this mean your Xcode project is set to portrait only?

**Comment by hecklerguy** [comment]
did you ever fix the descriptions length problem?

**Comment by thejoepeach** [comment]
Hi there, i am using hype for mac wich features one option to make its HTML
output responsive, if you like I can share a template that make your pages
behave right in baker, let me know if you like to have it...

El jueves, 10 de septiembre de 2015, hecklerguy <notifications@github.com>
escribió:

> did you ever fix the descriptions length problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bakerframework/baker/issues/419#issuecomment-139118908>
> .
>


-- 


http://freefallmotion.com/
freefallmotion Motion Graphics

**Comment by hecklerguy** [comment]
Template sounds great but how do I fix the descriptions on the main front page of the app where it displays my mag issues. Some are fine but some get messed up once I start rotating the iPhone back and forth

**Comment by hecklerguy** [comment]
Yes I would like the template as well
