### ISSUE TITLE
Aligning right to left

### ISSUE THREAD

**Issue by Sror** [bakerframework/baker#420]
Is it possible to align UICollectionView row contents from right to left for Arabic and Hebrew?

Thanks

**Comment by pieterclaerhout** [comment]
@Sror As far as I know, this is currently not possible, unless you change it in the code yourself.

**Comment by Sror** [comment]
Hi Pieter, many thanks for your replay. can you please help where (files/line) need to be changed.

Thanks

**Comment by tobiasstrebitzer** [comment]
Hi @Sror, the following stack-overflow answer should work:
http://stackoverflow.com/a/19923873

You can add the code to [BKRShelfViewLayout.m] (https://github.com/bakerframework/baker/blob/master/BakerView%2FBKRShelfViewLayout.m)

Hope that helps

**Comment by Sror** [comment]
Hi @tobiasstrebitzer, many thanks for you help.
 it seems somethings wrong  in my code! tried without good result.

Thanks
