### ISSUE TITLE
Hosting server requirements

### ISSUE THREAD

**Issue by lucasbols** [bakerframework/baker#421]
Hi there. 

I'm designing a book for a client (using indesign+in5+baker). It'll be standalone and free, with more issues coming in the near future (but we don't expect a large volume of downloads). My client wants to host all issues on his own server, but I'm not sure if that server will work OK with apple store/baker app... 

The question is: what are the technical requirements for the server to work flawlessly on this setting? Are there any downsides on hosting the issues on the company's server?

Thanks a lot for your help!

Lucas

**Comment by pieterclaerhout** [comment]
Hi @lucasbols,

I presume you are doing a newsstand app as in Baker, this is the only way you can download issues in the app. In the case of a standalone (non-newsstand app), the issues are embedded in the application.

For the newsstand app, you need to have a server that is capable of hosting the neccesary json files and hpub files. Depending on how you set this up, you basically have two choices:

* You manage the json and hpub files manually, updating the files as soon as a new issue is released
* You use a baker server component such as the Baker Server CE version. You find more info about this on http://www.bakerframework.com/servers/
* You could also use a third party to do the hosting, but that will probably not apply when you want to host your own issues.

In terms of technical requirements, the server itself should be able to run PHP/MySQL if you go for the Baker Server CE version.

**Comment by lucasbols** [comment]
Hi Pieter. Thanks for your answer! The technical requirements are clear now :)
Regarding standalone vs. newsstand, maybe you can give some advise on this:
I want to publish more than one issue (let's say once or twice a year) but I'll prefer to have my own app icon outside the Apple Newsstand. 
As far as I understand, it is possible to have a Standalone app with multiple issues, but all issues must be delivered at the same time packed into the app. In that case, if I want to add a new issue (or modify a existing one) I'll need to resubmit the entire app to Apple as if it was a 2.0 version....  Am I right?
That could be a little crazy (and of course I cannot have subscriptions, etc.) 
Is there any other way to achieve this (to have my app outside of the Newsstand app but still delivering multiple issues)?
Thanks a lot for your time!

**Comment by pieterclaerhout** [comment]
@lucasbols Yes, when you want to have a multi-issue app outside of Newsstand with Baker, you need to bundle the issues with the app and resubmit the app every time you want to add a new issue.

If you're open to other solutions, you might want to take a look at Twixl Publisher (I'm the lead developer there). Twixl Publisher does allow you to create a multi-issue app based on HPub which you can put outside of Newsstand. You can then add support for things like subscriptions etc, but of course, this option is not a free option. You can find more information about this on http://twixlmedia.com/en/publisher/solution.

**Comment by lucasbols** [comment]
Hi Pieter
I've just had a quick look at Twixl and it looks really promising. Maybe it's not for this particular project I'm working on, but we are starting to develop this kind of publications and your solution has a nice balance between features and cost, which is really interesting. I'll download the demo and play a little bit to see what it can do :)
Thanks again for you answer!

**Comment by pieterclaerhout** [comment]
That's great to hear. If you need any more info, feel free to get in touch with me on pieter@twixlmedia.com.
