### ISSUE TITLE
From inDesign - in5 - Bakerframework - Magazine App - App store (Help with the process) 

### ISSUE THREAD

**Issue by Vegals** [bakerframework/baker#427]
Hello there, firstly I'd just like to say thanks so much for taking the time to help me (and maybe others who read this forum and have the same confusion) on how to go about these issues. 

I am incredibly new with creating Newsstand apps and have a very rough idea on how to create a Magazine to send off to the Newsstand application as affordable as possible. But, nevertheless, here is what my concept consists of. 

A: Create the particular "Issue" via inDesign
B: Export the issue with "in5" to an HPUB format (Link to plugin - http://ajarproductions.com/pages/products/in5/?ref=footer) 
C: One thing I need help on - Import the .json created from in5 to Bakerframwork via xCode. (Anyone 

know any tutorials or exactly whats happening when I do this?) 
- From there I am under the assumption it some how links up with your actual "Magazine App" (What downloads when you click on the magazine name in the Newsstand store") How's this work? 

Now, when it actually comes to the application it's self (Issue container section) is where I get pretty nervous. I do not consider myself an App developer and am pretty much completely confused on what to do when it comes to this. I've been looking at alternative methods for being able to create that Magazine app / Issue purchaser / container section and have come across a template container (Link to site - http://www.appdesignvault.com/newsstand-app-ios/ ) and was hoping this would work with the HPUB i've generated out of in5. Does baker framework still need to be used? (Just a bit confused on exactly what bakerframework does) 

I am trying my hardest to completely understand what's actually happening throughout this process but the way I am going about it seems to be only one way out of plenty to actually create a Newsstand app. So, what I suppose I need help on is what are the file extensions that are generated when I export them? What is the file extension of the "issue" and how does it link to my "Magazine app" and how does this all tie in with baker framework?

**Comment by MagLoftMagazines** [comment]
Hey @Vegals,

I took the liberty to reformat your post so it's more readable :)

Baker is your all in one solution for setting up your own digital magazine. If you use the Baker Cloud Edition PHP software on your own server, then you have all you need to run an iOS magazine in the newsstand. You do not need to mess around with customizing the various book.json or shelf.json files.

The only thing you need to do is customize the Baker Xcode app with your colors, graphics etc and go through the app submission process (which can be very difficult if it's the first time). But you do not need to use any other software like AppDesignVault. Baker is free.

@nin9creative has made some really good videosthat show the entire process here:
http://www.bakerframework.com/bakercloudce/

I suggest you watch the videos first, as I'm sure Baker (Xcode) and Baker Cloud Console (server) is all you need.

**Comment by Vegals** [comment]
Thanks so much for clearing things up for me! All starts to blur into one giant mess the first time going about stuff, but hey! You can’t learn if you don’t try. 

I appreciate all your help! I’ll definitely get on to watching some of those videos, I’ve been dying for some visual learning! 

Thanks so much again, 

Regards, 
Justin

**Comment by Vegals** [comment]
Sorry to bother again, but would you say it may be a good idea go ahead with the template app and (somehow) export the files from inDesign with in5 and upload those files to work with the Template App I’ve purchased and then as I keep learning how to do it all manually go those means you’ve provided guidance on earlier? 

Sorry! I’m still trying to understand the A to B to C process with everything. Hopefully here after a few days of learning I’ll be able to make a logically move forwards. :) 


Regards, 
Justin

**Comment by MagLoftMagazines** [comment]
As far as I remember, that template app does not support HPUB but PDF only (I could be wrong but that was the case when I looked at it some time ago). Since you have already bought it you probably want to give it a stab, but not sure if you can find help customizing it for the Baker backend in this forum?

My suggestions would be to drop the template app and use Baker instead. Baker is another "template app" if you will, but more powerful in my humble opinion. With the Baker app, you can hook it up to the free Baker Cloud Console, which is an online management software for adding issues dynamically to your app, and also allows you to sell single issues and subscriptions.

**Comment by Vegals** [comment]
Awesome! Yeah, I'm actually looking into the videos you provided me earlier, it's clearing up a lot of back end confusion I have been having. 

I haven't yet purchased the template, I'm just a bit intimidated with xCode and don't have the slightest clue on where to get started with creating the Magazine app it's self. If it isn't hard due to the baker frame work than I might as well do something the right way the first time ey? 

Using the Baker cloud console sounds awesome! From what I'm actually watching right at this moment (Still getting through it all in the video) is MagRocket seems to have something similar to what the baker cloud console is doing by being able to upload "Issues" directly to the bakerframwork (Magazine app) without getting deep into code and staying within MagRocket. Forgive me if I'm wrong, but MagRocket seems easy enough to set-up. Have had decent experience inside cPanel and what not. :)

**Comment by MagLoftMagazines** [comment]
Hehe MagRocket IS Baker Cloud Console ;) The videos are slightly out dated, but still explain it all very well.

**Comment by Vegals** [comment]
Haha, I'm such an idiot. Disregard my vagueness. Lol

**Comment by Vegals** [comment]
So, please correct me if I'm wrong with this thought. (Takes me awhile to fully understand things, and you're the first one who's spoken to me about it. Sorry. Lol.)

I make the Magazine app in baker - Put Magrocket on my server - Upload Baker Mag app - Hop into indesign and make issue - export with in5 for baker frame work - Take that .Hpub export made and upload it through magrocket as well. For the raw basics of making things act like their working? lol.

**Comment by MagLoftMagazines** [comment]
With Baker + Baker Cloud you only have to upload your issue to the Baker Cloud. The Baker app will fetch the issue from your server (where Baker Cloud is installed) when readers request it through the app.

Hey no worries man, this was crazy confusing for me as well when I first got started ;)

**Comment by Vegals** [comment]
Haha, thanks so much! It's all starting to become much more clear. You've essentially eliminated a good 65% of my concerns in one blow. Lol. 

I'd love to be able to come back to you for a couple issues I'll most likely have in the future if you're willing to give some help here and there. I could compensate you some $$ if you're willing. Via Paypal or something. Just having someone who's been there and done it around once and a while can be a great thing to have. :)

**Comment by MagLoftMagazines** [comment]
@Vegals, you're in great company here. Many people here will be happy to help you out. We've all been where you are now, and it's great to be able to help. I might not be able to answer as quickly as today, but I'm sure others will step in :)

**Comment by Vegals** [comment]
No Problem! Thanks so much for all your help! Before you head off would you happen to know anyone who explains some customizing features of the baker framework look? I'd love to get into some basic things, importing fonts, and at least the basics on getting it to be decently 'your own.'

Thanks so much and I hope you have a great morning / night!

**Comment by MaverickWar** [comment]
The above template app does support both PDF and HPUB. so is fully acceptable to use for your app, however, it is not linked to any backend services... This means you need to host your content hpub or pdf files and link to them.

Easy enough to do though, the app itself is very well designed and in my opinion its ahead of the curve from a design point of view. But sadly it lacks a few features at present.

**Comment by MagLoftMagazines** [comment]
Thanks for clearing that up @MaverickWar
