### ISSUE TITLE
confirm_purchase response was 404 not found

### ISSUE THREAD

**Issue by QwertyPong** [bakerframework/baker#430]
Hi.
I have a problem when i use Baker Cloud CE.
When i try to subscribe or buy the issue, there is an error like my picture.
And the log is : 
2015-02-25 17:08:45.637 Magazine [905:60b] ERROR: Completed transaction for mag.juni2015, which is not a Product ID this app recognises
2015-02-25 17:08:45.846 Magazine [905:60b] [ERROR] Failed POST request to http://api.example.com/confirm_purchase/xxx/xxx: response was 404 not found
Could anyone help me to solve it?
Thank you
![img_4799](https://cloud.githubusercontent.com/assets/7358198/6368727/f8e133b0-bd11-11e4-9fc6-e91d9f792c75.PNG)

**Comment by QwertyPong** [comment]
It solved

**Comment by reefmag** [comment]
How did you solve this? I am having the same notification popping up in my app.

**Comment by QwertyPong** [comment]
It is because i put the wrong url on setting.plist. The url must : 

newstandManifestUrl -> http://api.xxx.com/issues/:app_id/:user_id
purchaseConfirmationUrl -> http://api.xxx.com/confirmpurchase/:app_id/:user_id
purchaseUrl ->http://api.xxx.com/purchases/:app_id/:user_id
postApnsTokenUrl -> http://api.xxx.com/apns/:app_id/:user_id

**Comment by reefmag** [comment]
I have the urls correctly setup, not sure what else it could be.
Thanks for though!

**Comment by reefmag** [comment]
Actually, I had this url incorrect purchaseConfirmationUrl ->
http://api.xxx.com/confirmpurchase/:app_id/:user_id

I had "confirmation" instead of "confirmpurchase", not sure how that
happened.
That solved the issue.

Thanks for your help!

**Comment by QwertyPong** [comment]
i'm glad to hear that.
