### ISSUE TITLE
Index at bottom or left side

### ISSUE THREAD

**Issue by ignaciolirio** [bakerframework/baker#432]
What preference decides if the index of an HPUB magazine appears to the bottom or to the left margins?

By default, it appears at the bottom, how can I change this in order to appear to the left?

Thanks

**Comment by AlmondFace** [comment]
@ignaciolirio 

use this value "-baker-index-width": 300," // 300 is the width of the menu, edit as you wish.
and remove the baker-index-height, this defaults the menu to the left hand side of the screen
