### ISSUE TITLE
App crashes when click on "Subscribe" button

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#433]
It just closes the app, and when connect to Xcode is shows this screen.
![screen shot 2015-02-26 at 3 55 57 pm](https://cloud.githubusercontent.com/assets/5607372/6404718/0669a698-bdd0-11e4-98ec-723a0ade8532.png)

**Comment by feralbob** [comment]
Add an exception breakpoint -
https://developer.apple.com/library/mac/recipes/xcode_help-breakpoint_navigator/articles/adding_an_exception_breakpoint.html

Once the breakpoint is there run it in the debugger and it'll show you
exactly what line is causing the exception.

Also try looking in the console logo for details of the exception

**Comment by codegeek511** [comment]
Ah ha! Thanks @feralbob! It was the 2nd line in the code from https://github.com/bakerframework/baker/issues/321#issuecomment-75163929
@MagLoftMagazines

**Comment by MagLoftMagazines** [comment]
Are you currently getting an error from the code I pasted in the other thread? Any way to share some more details? It's working fine for us.

**Comment by codegeek511** [comment]
@MagLoftMagazines Yes the link I posted above...that code. Nothing much more I can say, just that when that code you posted is in use it crashes when I click on the "Subscribe" button. I ran the exceptional breakpoint that @feralbob suggested and it told me it was this line of code

SKPaymentTransaction *transaction = [notification.userInfo objectForKey:@"transaction"];

which is the 2nd line.

**Comment by codegeek511** [comment]
@MagLoftMagazines UPDATE: It isn't just your code that makes the app crash when you hit the "Subscribe" button. Apparently it just started doing it when I added your code. However....it is the same function that breaks the code in both instances, both with the original code and in the new code. So somewhere I am doing something wrong and their is a bug.

**Comment by codegeek511** [comment]
@MagLoftMagazines do you yet why this would happen? Is there something I can do to try and fix it?

**Comment by MagLoftMagazines** [comment]
Not sure why this is happening. If you want, you can try our MagLoft Baker version http://www.bitbucket.com/magloft as it works fine there. Also has Parse implemented,just add your keys in settings plist.

**Comment by codegeek511** [comment]
@MagLoftMagazines Ok thanks. @nin9creative do you why this could be happening?

**Comment by codegeek511** [comment]
@MagLoftMagazines So I downloaded that project and I ran it and it has an error saying I am missing the LaunchVideo.mp4 

where do I get it from? and why isn't it just included or made optional

**Comment by MagLoftMagazines** [comment]
Hi @codegeek511 sorry about that, there is a reference to this file under Build Phases --> Copy Bundle Resources and you can just remove it from there.

Can you screenshot your settings here or share your manifest url?

**Comment by codegeek511** [comment]
@MagLoftMagazines I fixed the Issues not showing up, I forgot to add the bundle ID......my bad. Thanks

**Comment by MagLoftMagazines** [comment]
Awesome, glad to hear you're up and running :)

**Comment by reefmag** [comment]
I tried your code too @MagLoftMagazines but it unlocks all the back issues even though the Baker Console is set to "Unlock Only Issues Within Subscription Term". Is there something within the code I need to change?

**Comment by MagLoftMagazines** [comment]
Hi @reefmag, thanks for letting us know about that. We will check it out asap.

**Comment by MagLoftMagazines** [comment]
Actually I see that it's simply due to the fact that we don't support the unlocking of back issues on subscription. We will add that to MagLoft today or tomorrow.

**Comment by reefmag** [comment]
Yea, all the back issues were unlocked, when I tested a subscription, I
don't want them unlocked. Only wanted the issues within the subscription
period unlocked.

Looking forward to the changes! Thanks!

**Comment by codegeek511** [comment]
@reefmag What do you mean by unlocked issues?

**Comment by reefmag** [comment]
An unlocked issue is one that is available for download. 

So, I have 8 issues and when I hit the subscribe button, all 8 issues were immediately available for download or "unlocked".
Even though in Baker Cloud I have setup subscriptions to "only unlock the issues within the subscription period". 

Only the latest issue should have been instantly available for download or "unlocked" when subscribed and the remaining back issues should have kept their prices and be available for purchase.

I tried out as Magloft's code and as Nick pointed out there is an update that is needed.
Hope that helps.

**Comment by MagLoftMagazines** [comment]
Hi @reefmag, I must have been half sleeping when replying to your initial post. The app itself should not control how many issues are unlocked and displayed in the app. This is all done by the backend. In this case, Baker Cloud will unlock issues based on subscription settings and send these issue to the app via the manifest endpoint. Our baker app version shouldn't be the cause of unlocking all issues for a subscription.

Sorry to ask a silly question, but did you try both options from Baker Cloud?

**Comment by nin9creative** [comment]
What are the publication dates on the issues in Baker Cloud?
The subscription logic goes to the beginning of the month in which the subscription was purchased.
Andrew

**Comment by reefmag** [comment]
Hey Nick,
I will definitely, try both again. And let you know how it goes.

Andrew, these are the dates I have setup in baker Cloud for each issue.

2015-04-16 - Issue 8
2015-03-11 - Issue 7
2015-02-01 - Issue 6
2014-12-30 - Issue 5
2014-12-01 - Issue 4
2014-11-11 - Issue 3
2014-10-01 - Issue 2
2014-08-24 - Issue1

**Comment by nin9creative** [comment]
Also, if you are using the Baker Cloud console and the setting is for "sandbox mode" - keep in mind that all of the issues are unlocked when a subscription is purchased for ease of testing.  When in production - this will not occur.  It then will use the subscription term setting.

| // If we are in Sandbox Mode, unlock all issues by default for testing purposes  |
|  |  if(getiTunesProductionLevel($app_id)=="sandbox"){ |
|  |  |
|  |  $result = $db->query("SELECT PRODUCT_ID FROM ISSUES |
|  |  WHERE APP_ID = '$app_id' |
|  |  AND PRICING = 'paid'"); |
|  |  } |
|  |  else{ |
|  |  // If we are in Production - determine based on Subscription Behavior setting |


Andrew

**Comment by reefmag** [comment]
Ok, I used a new test ID and the prices stayed for back issues, and none of the issues were unlocked. 
So all is well. 
Thanks again for all your help!
