### ISSUE TITLE
Error - failed to open first file in zip file

### ISSUE THREAD

**Issue by AlmondFace** [bakerframework/baker#434]
Hi im getting a nightmare error. Ive been used the baker product to develop my hpub. have then gone to upload this to my server and download into my actual app. and am getting the below error.

As far as i can tell from the information below, this is do to with the cache that needs to be cleared on my device. I have tested the hpub in another app that works, so i know it isnt the hpub package itself. but it is not doing so on this app target. 

Any help would be amazing,

Error - Failed to open first file in  zip file

this is the output from the console:

 Error copying file from file:///private/var/mobile/Containers/Data/Application/FB8453D6-86DC-464F-A48D-6768DA1E8E1E/Library/Caches/bgdl-185-f94d1638a355344c.zip to /var/mobile/Containers/Data/Application/FB8453D6-86DC-464F-A48D-6768DA1E8E1E/Library/Caches/Newsstand/4C584040-1ED5-4916-8BB3-9CD9734A43BC/001

**Comment by pieterclaerhout** [comment]
Did you do any customizations to the app?

If you test with the stock version of the Baker framework, does it also have the same problem?
