### ISSUE TITLE
Invalid Products ID

### ISSUE THREAD

**Issue by vincentcabrera** [bakerframework/baker#436]
Hi guys! i have a big problem with the connection between ItunesConnect and xcode.
The product ID of my issue is the same in BakerCloud and ItunesConnect but xcode not recognize 
What happening?
![captura de pantalla 2015-03-04 a las 12 48 03](https://cloud.githubusercontent.com/assets/11278584/6486916/ef7b0e8a-c26c-11e4-91f9-59af809e1e35.png)

![captura de pantalla 2015-03-04 a las 12 37 40](https://cloud.githubusercontent.com/assets/11278584/6486819/4d4a6d4a-c26c-11e4-897b-1c7ab50814e5.png)
![captura de pantalla 2015-03-04 a las 12 37 24](https://cloud.githubusercontent.com/assets/11278584/6486820/4da07bc2-c26c-11e4-9a4c-39dd52e559f9.png)

**Comment by feralbob** [comment]
Are you running in the simulator or on the device?

**Comment by vincentcabrera** [comment]
On the device, an iPad

**Comment by pieterclaerhout** [comment]
One thing that might cause this is well is if you didn't setup the contracts for payments in iTunes Connect:

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/da/jumpTo?page=contracts

Have you setup the proper contracts in there?
