### ISSUE TITLE
Info Box

### ISSUE THREAD

**Issue by vincentcabrera** [bakerframework/baker#437]
Hi Guys, how I can Delete de "info button"

**Comment by MagLoftMagazines** [comment]
Hi @vincentcabrera, if you remove the info.html file from the BakerShelf/info folder, then the icon won't show up.

**Comment by vincentcabrera** [comment]
It does not work. I deleted the file info.html but the button "Info" is still there. When clicking the app falls.
I added the file again does not work.
:(

**Comment by pieterclaerhout** [comment]
If you do a clean and then build again, does that fix the problem?
