### ISSUE TITLE
Baker on the News

### ISSUE THREAD

**Issue by thejoepeach** [bakerframework/baker#438]
I find this post on a tech blog that talk about one of my apps made in Baker, so i decide to share it here:

http://www.talkingnewmedia.com/2015/03/06/one-small-world-changeboard-press-perspectives-show-not-one-way-create-digital-edition-newsstand/

Again the Baker name on the news....

**Comment by MagLoftMagazines** [comment]
Hey Joe,

Your mag looks awesome! Love the idea of pushing ebooks as issues :) The TNM post actually features two Baker mags as the Freeport Press is also done with Baker but for the clients PDF version. Go baker :)

**Comment by thejoepeach** [comment]
really? thats great, i love the desing of that App... big cheers to Baker and keep on meking it better...
