### ISSUE TITLE
How to set Newsstand shelf cover to the latest available issue cover

### ISSUE THREAD

**Issue by lauratraveler** [bakerframework/baker#439]
Hi,

Is there a way to set the Newsstand shelf cover to the latest available issue cover, not the latest downloaded cover?

The latest downloaded cover is really confusing for the user, as they actually have to open the app to see if there are any new issues to download. Most magazine apps out there automatically display the latest available issue cover in the Newsstand shelf without the user having to take action.

**Comment by tobiasstrebitzer** [comment]
Hi Laura,

you can delete lines 120 to 122 in [BakerShelf/BKRIssuesManager.m (]https://github.com/bakerframework/baker/blob/master/BakerShelf/BKRIssuesManager.m#L120):

```objc
// delete these lines:
if ([[issue getStatus] isEqualToString:@"downloaded"]) {
  return;
}
```

Doing so, your app will always set the latest issue cover whenever the issue list is being refreshed (application launch, or pressing the refresh button).

**Comment by lauratraveler** [comment]
Hi Tobias,

I've tried that already, but unfortunately, there is no change. The Newsstand icon is still the last downloaded one and it changes with each newly downloaded issue. I have deleted and reinstalled the app on my devices, cleaned and rebuilt the project :(

Just to make sure we are not talking about two different things, I mean the cover that shows in the Newsstand, the screen where all the other magazine covers are shown. Thanks!

**Comment by tobiasstrebitzer** [comment]
Just to be 100% sure, you've enabled "newsstandLatestIssueCover" in settings.plist, right?

The next step is to set a debug-marker in the "updateNewsstandIcon" method, to find out if it's stepping into the correct lines of code. I can also have a look at your project if you don't mind sharing your source code (tobias.strebitzer@magloft.com).

**Comment by lauratraveler** [comment]
Ok, so I've sorted this out by deleting this lines from BKRIsuse.m

UIImage *coverImage = [UIImage imageWithContentsOfFile:self.coverPath];
    if (coverImage) {
        [[UIApplication sharedApplication] setNewsstandIconImage:coverImage];
    }

But I would like the issue list to be refreshed and the new cover to show up in the Newsstand shelf whenever a new issue is available, not only on application launch or by pressing the refresh button. 

I do not want to download new issues automatically, but simply to refresh the app whenever a new issue is available.
