### ISSUE TITLE
Removing Android app permissions

### ISSUE THREAD

**Issue by lauratraveler** [bakerframework/baker#441]
The number of permissions that come as a default with Baker for Android is overwhelming and I believe some are unnecessary. Right now in the AndroidManifest.xml are the following permission as per Baker: 

<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

```
<uses-permission android:name="com.android.vending.BILLING" />
<!-- Required to access Google Play Licensing -->
<uses-permission android:name="com.android.vending.CHECK_LICENSE" />

<permission
    android:name="com.baker.abaker.permission.C2D_MESSAGE"
    android:protectionLevel="signature" />

<uses-permission android:name="com.baker.abaker.permission.C2D_MESSAGE" />

<uses-permission android:name="android.permission.READ_PHONE_STATE" />
```

I tried to delete some or all of them, but every time I generate the signed APK the permissions get generated in the 'intermidiates' file and I am stuck with 13 permissions. 

How can I successfully remove some of these permissions?

**Comment by tobiasstrebitzer** [comment]
1. The 'intermediates' files should be correctly re-build when you build your app. Please try to "Clean" the project and see if that has any effect. Make sure you edit the correct manifest file (not the one underneath the ```build/``` directory.
2. There's an alternate baker android repository here: [baker-android-refactor](https://github.com/bakerframework/baker-android-refactor). In case you haven't made a lot of modifications, you should consider switching over to this repository.
