### ISSUE TITLE
Newsstand notifications not working

### ISSUE THREAD

**Issue by lauratraveler** [bakerframework/baker#442]
I would like my magazine app to badge the Newsstand icon every time a new issue is available for download and inside the Newsstand the small blue dot to show under my new magazine cover that should update automatically when a new issue is available. 

Initially I followed the tutorial here - https://github.com/bakerframework/baker/wiki/Tutorial-for-Newsstand-with-Free-issues - without bothering with this optional step (8. (optional) Set purchaseConfirmationUrl to the URL where you want to receive the ping when a user subscribes to your app (see Subscription-pingback).). When I published the second issue of my magazine, there was no notification, no icon badging, no cover change, nothing!! So how can the reader know there's a new issue available if they don't actually check the app, right?

So I followed the link trail to https://github.com/Simbul/baker-server-example, and I uploaded those files on my server and added the 'postApnsTokenUrl' in the settings.plist

In the BKRAppDelegate.m I have this:

```
// Let the device know we want to handle Newsstand push notifications
if ([application respondsToSelector:@selector(registerUserNotificationSettings:)]) {
    UIUserNotificationSettings *notificationSettings = [UIUserNotificationSettings settingsForTypes:(UIRemoteNotificationTypeNewsstandContentAvailability|UIRemoteNotificationTypeBadge|UIRemoteNotificationTypeSound|UIRemoteNotificationTypeAlert) categories:nil];
    [application registerUserNotificationSettings:notificationSettings];
} else {
    [application registerForRemoteNotificationTypes:(UIRemoteNotificationTypeNewsstandContentAvailability|UIRemoteNotificationTypeBadge|UIRemoteNotificationTypeSound|UIRemoteNotificationTypeAlert)];
}
```

The app does NOT badge automatically when a new issue is available for the reader to download. The cover doesn't change to the latest available cover, so there's no way of knowing if there's a new magazine issue unless you go inside the Newsstand and open the app. 

Does anyone else have the same problem or do you have any ideas how to sort this out? Is there a way to also send lock screen notifications so I can let readers know there's a new issue available?

Is it mandatory to have a shared secret key for my app to receive notifications?

**Comment by pieterclaerhout** [comment]
What's the content of the push notification you are sending?

If you send a text notification to your device, does that actually arrive?

**Comment by lauratraveler** [comment]
As mentioned in another comment, after installing Parse I started receiving text notifications with sound. But the app icon doesn't badge no matter what I do, nor the app gets refreshed when a push notification from Parse arrives. 

I don't know if there's any way of refreshing the app when a push from Parse arrives, but in case there isn't, I guess I'll have to come back to the above mentioned tutorial and handle the notifications on my own server. 

Is it mandatory to have a shared secret key for my app to receive notifications? Since my magazine is completely free, I don't have a shared secret. 

Also, is there a tutorial that explains how to send a push using the code above? Not to mention that the disclaimer says "it should never be used in production". Then what should be used in production? I'm confused :(

**Comment by lauratraveler** [comment]
I've just tried this:

{
"alert": "Text",
"badge": "Increment",
"content-available": "1",
"sound": "default"
}

The badge increments if there's new content available, the Newsstand shelf cover changes to the last cover and the text message arrives ok with sound, but the shelf of my app doesn't always refresh so the last issue is not always there after the Newsstand icon was badged.
