### ISSUE TITLE
Running Exception with Categories dropdown 

### ISSUE THREAD

**Issue by alemachado** [bakerframework/baker#445]
First of all, congratulations for the framework!

I'm trying to work on my first project using baker and It's mandatory to organize the issues on it. So maybe the categories filter should help (even if a search field would be perfect).
The problem is that when I try to Build and Run on a device, after clicking on the categories dropdown the app returns an exception:

>"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (2) must be equal to the number of items contained in that section before the update (2), plus or minus the number of items inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'"

in this test I'm using two issues each one with one category. The Dropdown appears correctly but when I try to select one option occurs the exception

Have you any idea what could be wrong?

thanks again

**Comment by pieterclaerhout** [comment]
Hi, can you point us to the shelf json file you are using? That way, we can see if we can simulate the problem.

**Comment by alemachado** [comment]
hi @pieterclaerhout 
this is the json that I'm using: http://ngalsospace.com/publications/shelf.json
thanks

**Comment by tobiasstrebitzer** [comment]
Hi @alemachado,

i just tried your manifest url in a fresh installation of the latest baker version, and categories work without errors. Which version of baker are you using?

**Comment by alemachado** [comment]
Hi @pieterclaerhout  
I'm using the last 4.3... I didi few changes (only for design elements), anyway, I'll try to reinstall

**Comment by alemachado** [comment]
Hi @pieterclaerhout 
I've just checked that the problems occurs not when I use the ios Simulator (with simulator everything goes right), but when I use a device to test it.  I've tried with an iPad and an iPhone and the exceptions occurred with both.

**Comment by snowywolfie** [comment]
Hi, I am facing the same problem as Alemachado. Any solution for this problem yet?

**Comment by tobiasstrebitzer** [comment]
Hi @alemachado and @snowywolfie,

we have prepared a pull request with storyboard integration. In there, we did a major refactor of the baker shelf (which is causing the issue, after filtering using categories). I'm curious if the issue persists after the refactor.

Please give it a try using #476 ... [(Download Source ZIP)](https://github.com/bakerframework/baker/archive/975abf4ea02e4db38e78265fe30687fc8c527ae4.zip)

**Comment by snowywolfie** [comment]
Great!  It is working now.  Thank you so much @tobiasstrebitzer!!
But is that possible I copy and paste the modified code and storyboard to my current project? If yes, which parts should I copy ?

**Comment by tobiasstrebitzer** [comment]
Great! @alemachado please re-open if the issue persists for you.
