### ISSUE TITLE
Newsstand refresh

### ISSUE THREAD

**Issue by lauratraveler** [bakerframework/baker#446]
Does the Newsstand app refresh periodically by itself, fetching new issues to display on the shelf, or is the shelf only updated when the user launches the app?

Does the 'background fetch' need to be enabled for the app to update automatically?

**Comment by pieterclaerhout** [comment]
The Newsstand app refreshes only when it gets a push notification with "content-available" flag in there. On top of that, in appstore versions, it only looks at this once every 24 hours.

Background fetch should be enabled as far as I know.

**Comment by lauratraveler** [comment]
Ok, I am very new to this, so I don't know exactly what needs to be done. I am only interested in the Newsstand app at this point. I have integrated push notifications from Parse in my app, but the Newsstand app does't refresh when a push notification arrives. 

I have this in my AppDelegate.m

- (void)application:(UIApplication*)application didReceiveRemoteNotification:(NSDictionary*)userInfo {
    
    if (![BKRSettings sharedSettings].isNewsstand) {
        return;
    }
    
    NSDictionary *aps = userInfo[@"aps"];
    if (aps && aps[@"content-available"]) {
        [self applicationWillHandleNewsstandNotificationOfContent:userInfo[@"content-name"]];
    }
    
    NSLog(@"[Parse] Remote notification opened");
    // Parse handles push notifications
    [PFPush handlePush:userInfo];

    
    if (application.applicationState == UIApplicationStateInactive) {
        // The application was just brought from the background to the foreground,
        // so we consider the app as having been "opened by a push notification."
        [PFAnalytics trackAppOpenedWithRemoteNotificationPayload:userInfo];
    }
}

And this in IsusesManager.m

- (void)refresh:(void (^)(BOOL))callback {
    [self getShelfJSON:^(NSData *json) {
        if (json) {
            NSError* error = nil;
            NSArray* jsonArr = [NSJSONSerialization JSONObjectWithData:json
                                                               options:0
                                                                 error:&error];
            
            [self updateNewsstandIssuesList:jsonArr];
            
            NSMutableArray *tmpIssues = [NSMutableArray array];
            NSMutableArray *tmpCategories = [NSMutableArray array];
            [jsonArr enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
                BKRIssue *issue = [[BKRIssue alloc] initWithIssueData:obj];
                
                // Append categories
                [issue.categories enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
                    if(![tmpCategories containsObject:obj]) {
                        [tmpCategories addObject:obj];
                    }
                }];
                
                // Add issue to temporary issue list
                [tmpIssues addObject:issue];
            }];
            
            // Sort categories
            [tmpCategories sortUsingSelector:@selector(compare:)];
            _categories = tmpCategories;
            
            // Sort issues
            self.issues = [tmpIssues sortedArrayUsingComparator:^NSComparisonResult(id a, id b) {
                NSDate *first = [BKRUtils dateWithFormattedString:[(BKRIssue*)a date]];
                NSDate *second = [BKRUtils dateWithFormattedString:[(BKRIssue*)b date]];
                return [second compare:first];
            }];
            
            [self updateNewsstandIcon];
            
            if (callback) {
                callback(YES);
            }
        }
        else {
            if (callback) {
                callback(NO);
            }
        }
    }];
}

Is a shared secret key necessary in order to send push notifications?

**Comment by lauratraveler** [comment]
Ok, I've just used this in Parse.

{
    "alert": "Text",
    "badge": "Increment",
    "content-available": "1",
    "sound": "default"
}

The badge increments if there's new content available, the Newsstand shelf cover changes to the last cover and the text message arrives ok with sound, but the shelf of my app doesn't always refresh and the last issue is not always there after the Newsstand icon was badged.

**Comment by tobiasstrebitzer** [comment]
Hi @lauratraveler did you manage to solve this issue?
