### ISSUE TITLE
Lost all my issues of my app

### ISSUE THREAD

**Issue by jdurhamrtm** [bakerframework/baker#447]
I went to look at my app that has been running fine for over a year and I just got the error that I wasn't connected to the internet, and all my issues disappeared. I hooked my device to xcode and went to run it and it flagged this error:

[ERROR] Failed GET request to http://api.mydomain.com/issues/com.realtruthmatters.Real-Truth-Matters-Magazine/device_key?environment=debug: response was 500 internal server error.

Please help.

**Comment by feralbob** [comment]
The 500 indicates that there was an internal error in whatever served the
response.  If you visit the proper full URL do you see the results you
expect?

**Comment by jdurhamrtm** [comment]
Ok, when I went to my API this morning I see absolutely nothing. I'm assuming I probably should re set that back up. I am using the Baker CE by the way.

**Comment by feralbob** [comment]
The logs of the web server running Baker CE should have some clues... other
than that not sure what else to suggest.

Should look into why the invalid response removes the cached local copy of
the shelf

**Comment by jdurhamrtm** [comment]
Checking the logs I see nothing recent. It's all from last year actually. So I am really confused as to what happened.

**Comment by jdurhamrtm** [comment]
I think some how my API glitched and it has caused all of the errors.

**Comment by jdurhamrtm** [comment]
I've even re-installed the API side of Baker Cloud Console and it's blank. No errors no nothing.

**Comment by jdurhamrtm** [comment]
Found the problem, my web server made a change that lowered the PHP version which isn't supported by Baker CE. I went back and changed it and it worked. Thanks!
