### ISSUE TITLE
A Developer Says, "THANK YOU!"

### ISSUE THREAD

**Issue by LuxViz** [bakerframework/baker#453]
My name is Rick Carmichael, and after working for Apple in Cupertino for about 10 years, I took a layoff package, worked freelance as a web designer and photographer for a while in Santa Cruz, CA, and then in 2007 I "ran away" to Bali to form LuxViz. My company develops mobile apps, provides very skilled architectural photography, 360˚ interactive panorama tours, and creates a variety of social media to be used in promoting indulgent luxury travel. In the 7 years I've been living in Bali, I've shot - and professionally edited - about 120,000 photos, mostly of Bali's finest villas.

We're still a VERY small firm with clients in the luxury travel and lifestyle market. Our first app was Bali's Finest Villas, which we plan to republish as new (standalone) editions every 3 months. Each issue of Bali's Finest Villas features 10 of the most gorgeous and luxurious villas in Bali, along with close to 500 stunning architectural photos, dozens of 360˚panorama tours, hundreds of pages of villa content, and numerous articles about the people and the culture of The World's Best Island.

In the one year since we started working with Baker, we have published a total of 26 standalone apps: 13 iOS apps and 13 Android apps. Again, these are all standalone apps, and NOT magazines or books. 

The next app we’re working on now is called Bali’s Boutique Villas and it will feature the more “mid-range” villas in Bali. BBV will also be a quarterly publication, with each issue featuring 20 villas, along with information about the people and culture of Bali.

**iOS STANDALONE APPS DEVELOPED USING BAKER**
Here is a list of the iOS apps we’ve created in the last one-year period.

Bali's Finest Villas - SD Version (for iPads with normal displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-sd-english/id879332125?ls=1&mt=8

Bali's Finest Villas - HD Version (for iPads with the retina displays)
https://itunes.apple.com/us/app/balis-finest-villas-1-hd-english/id880005823?ls=1&mt=8

The View at THE edge
https://itunes.apple.com/us/app/the-view-at-the-edge/id888174007?ls=1&mt=8

Villa Sungai
https://itunes.apple.com/us/app/villa-sungai/id888575675?ls=1&mt=8

Jagaditha
https://itunes.apple.com/us/app/jagaditha/id888597640?ls=1&mt=8

The Sanctuary Bali
https://itunes.apple.com/us/app/the-sanctuary-bali/id888637329?ls=1&mt=8

Villa Arika
https://itunes.apple.com/us/app/villa-arika/id888654168?ls=1&mt=8

Villa Sound of the Sea
https://itunes.apple.com/us/app/villa-sound-of-the-sea/id888979485?ls=1&mt=8

Jeeva Saba
https://itunes.apple.com/us/app/jeeva-saba/id888993802?ls=1&mt=8

Villa Shambala
https://itunes.apple.com/us/app/villa-shambala/id889006817?ls=1&mt=8

Villa Taman Ahimsa
https://itunes.apple.com/us/app/villa-taman-ahimsa/id889015098?ls=1&mt=8

Villa Ombak Laut
https://itunes.apple.com/us/app/villa-ombak-laut/id889019237?ls=1&mt=8

Qunci Villas - Lombok
https://itunes.apple.com/us/app/qunci-villas-lombok/id899099183?ls=1&mt=8

For the Qunci Villas app, we used Baker again to develop a visually stunning and totally engaging app for this stunning hotel property in Lombok Indonesia. The app is a collection of about 13 linked, 360˚ panorama tours for showing off that property. And... the opening screen in the app is an aerial 360˚ of the property shot out over the ocean from a remote-controlled, drone octocopter.

**ANDROID STANDALONE APPS DEVELOPED USING BAKER**
And then here is a list of the Android apps we’ve created in the last one-year period - actually within the last 2 months.

Bali's Finest Villas - SD Version (standard-definition for normal displays)
https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillasSD1

Bali's Finest Villas - HD Version (high-definition for retina displays)
https://play.google.com/store/apps/details?id=com.luxviz.balisfinestvillas1HD

The View at THE edge
https://play.google.com/store/apps/details?id=com.luxviz.theView

Villa Sungai
https://play.google.com/store/apps/details?id=com.luxviz.villaSungai

Jagaditha
https://play.google.com/store/apps/details?id=com.luxviz.jagaditha

The Sanctuary Bali
https://play.google.com/store/apps/details?id=com.luxviz.sanctuaryBali

Villa Arika
https://play.google.com/store/apps/details?id=com.luxviz.villaArika

Villa Sound of the Sea
https://play.google.com/store/apps/details?id=com.luxviz.soundOfTheSea

Jeeva Saba
https://play.google.com/store/apps/details?id=com.luxviz.jeevaSaba

Villa Shambala
https://play.google.com/store/apps/details?id=com.luxviz.villaShambala

Villa Taman Ahimsa
https://play.google.com/store/apps/details?id=com.luxviz.tamanAhimsa

Villa Ombak Laut
https://play.google.com/store/apps/details?id=com.luxviz.ombakLaut

**STANDALONE APP DEVELOPMENT MARKET?**
We initially used the Adobe DPS system for developing Bali’s Finest Villas. However, once we completed the prototype and began looking at the implementation issues, we realized that our business model simply would not support paying the hefty download fees they were wanting to charge developers. So, we had to look for other development platforms. Which is how we came to find out about Baker.

We initially were using Baker to design a Newsstand app, but because our content is totally focused on promoting bookings in some of Bali's finest luxury villas, Apple wouldn't approve as a Newsstand app. So... we basically flipped the switch in Xcode from Newsstand to Standalone, rebuilt and resubmitted the app, and now we're up to THIRTEEN apps approved on the iTunes App Store and the same 13 also published using the beta versions of Baker for Android on the Google Play store. All 26 are standalone apps.

I think you guys might be missing out on an enormous chunk of the app development market because your verbiage and examples seem to be totally focused on digital (newsstand) publications.

The top headline on your website states: "Baker is a HTML5 based digital publication framework for publishing interactive books & magazines on iPad & iPhone using simply open web standards."

(To be fair, you DO mention both Newsstand and Standalone under Item 3 - Publish. But, the majority of your examples and verbiage on the site are geared towards magazine-like apps.)

Just my 2 cent's worth! 

**GETTING LISTED AS A BAKER DEVELOPER?**
We'd love to be included in your list of developers on your website.

We're using a combination of the following tools in producing our apps:

HTML 5
CSS
JQuery/Javascript
Objective C
Xcode
Java
Android Studio
and, of course, the Baker Framework!

My programmer has done a VERY SIGNIFICANT amount of custom coding to get our Android apps functioning as closely as possible to the iOS Baker apps. We would be happy to provide source code to you guys if you’re interested in seeing what we did.

Thank you from the bottom of my heart for allowing me to carve out a brand new service niche for my small company in Bali!

Best wishes,
Rick

![01 cover](https://cloud.githubusercontent.com/assets/9841038/6822209/053db972-d319-11e4-8404-9145d57ca34a.jpg)
![02 villa sungai](https://cloud.githubusercontent.com/assets/9841038/6822210/053e742a-d319-11e4-960d-b56f08481e11.jpg)
![03 sanctuary bali](https://cloud.githubusercontent.com/assets/9841038/6822212/0542f270-d319-11e4-9f4a-7db039fc4cf6.jpg)
![04 sound of the sea](https://cloud.githubusercontent.com/assets/9841038/6822211/05421436-d319-11e4-8f27-c3b87f89ab69.jpg)
![05 bali article](https://cloud.githubusercontent.com/assets/9841038/6822213/0543aba2-d319-11e4-8113-b756289ea6dc.jpg)

**Comment by fransimo** [comment]
I was asking the timing for this feature #15 

@pieterclaerhout, recommend me Twixl. But we need another approach.

We started working with Mag+ ( http://kamaleon.travel/magazine-apps/ ) but their new prices are absolutely out of or clients budget.

The problem we want to solve is another change of prices. Twixl is more close to our need but even that we can't trust in a third service. 

We are seriously thinking in develop a new HPUB compatible Swift app, or to add this functionality to Baker. We are not interested on payed downloads. In any case we would pay a developer to do it.

@LuxViz may be we have to think on some "joint venture"... We are still thinking about this.

**Comment by LuxViz** [comment]
We are still programming around HPUB with Javascript - even in this environment, I think it's possible to implement the functionality through code - but I'm sure it would be better is there was a Swift framework to wrap around HPUB content... which would allow for in-app purchases of content for one app to display. 

We also looked at Twixl, but their prices are totally out of our league.

For the time being, we're pressing ahead with multiple standalone apps - each with the same base name and with the issue number being appended to the end.

@fransimo - we would be happy to try to collaborate on the functional spec for a Swift app, but my programmer currently does have any Swift programming experience - though that could change very quickly

**Comment by MagLoftMagazines** [comment]
Rick (@LuxViz) I'm so impressed with what you guys have done! 

We (MagLoft) are also getting requests for standalone apps that support subscriptions and single issues, and I know my Co-founder @tobiasstrebitzer is also very eager to get this up and running as a MagLoft service. 

We should all meet for coffee and have a chat. Call me on 0811 386 185 ;)

**Comment by fransimo** [comment]
We decided to invest on this functionality, we didn't decide yet if we are going to start from scratch with Swift or if we are going to use Baker. we either decide if we are going to make it open source.

@LuxViz // @MagLoftMagazines  // @tobiasstrebitzer Did you finally met?

**Comment by LuxViz** [comment]
@fransimo yes as a matter of fact, we met with @MagLoftMagazines  and @tobiasstrebitzer yesterday! And I shared with them a different perspective that we have been thinking about - this is specifically related to our objective of wanting to become recognized as a leading developer of luxury travel & hospitality apps...

IF we implemented/adopted the approach of only having 1 stand alone app that supported in-app downloads and purchases of various issues, the main benefit would be of consolidating app ratings and download stats. However, the downside of that approach is that people viewing our app portfolio would only see 1 app.

We are now thinking it will provide a much stronger picture of our expertise as developers to have dozens, or even hundreds of individual apps displayed in our portfolio (on our developer pages in iTunes and Google Play) which are all focused on the luxury travel & hospitality areas.

**Comment by nin9creative** [comment]
Would be interested to see where this goes.

**Comment by tobiasstrebitzer** [comment]
Update: iOS 9 will be released soon, which shuts down newsstand, and all newsstand apps will convert to standalone apps. #470

**Comment by shutterflypro** [comment]
@LuxViz Is there anyway that I could get ahold of the android version of Baker that you have.  This has been a thorn in my side for the past couple of years.
