### ISSUE TITLE
Share on Facebook from within the hpub

### ISSUE THREAD

**Issue by lauratraveler** [bakerframework/baker#455]
Hi! How can I share a custom message + the URL of the iOS app + image on Facebook? I suppose I need to use fb:// but I'm not sure what's the syntax. 

I have used fb://profile/id for opening the app to like the page and this works fine. 

Now I would like for the readers to be able to share certain article from inside the magazine with their friends on FB.

Many thanks!

**Comment by fransimo** [comment]
There are to pull request to implement it
https://github.com/bakerframework/baker/pull/454
and 
https://github.com/bakerframework/baker/pull/78

**Comment by lauratraveler** [comment]
@fransimo I would be happy with something local. For sharing on Twitter I used twitter://post?message=text, and I was hoping for something similar for Facebook.

**Comment by pieterclaerhout** [comment]
#454 has been merged to the repository, so you should be able to just use it.

We still need to update the documentation though.

**Comment by espilber** [comment]
Hi, there's a problem with merge #454, doesn't work on ipad with ios8. No problem on iPhone ios7 & ios8, and ipad ios7. The problem seems related with activityViewController on iPad with ios8: http://stackoverflow.com/questions/25644054/uiactivityviewcontroller-crashing-on-ios8-ipads

**Comment by thejoepeach** [comment]
hi there, it still crash on iOS 8 when try to share via email.... FYI

**Comment by pieterclaerhout** [comment]
@thejoepeach Do you get a stack trace by any chance as I'm not able to simulate this...
