### ISSUE TITLE
Title Screens?

### ISSUE THREAD

**Issue by KrossMorris** [bakerframework/baker#456]
I am very new to this. Does anyone know if there is a way to create a title screen, similar to that of a video game, that would allow for easy initial navigation to things like credits, tutorials, and then the book itself? Would this be a simple matter or difficult using this framework, since I know it indexes all the page files?

Thanks,
- Kevin

**Comment by thejoepeach** [comment]
Hi @KrossMorris  i create this app using Baker and using the single book configuration:

https://itunes.apple.com/mx/app/mazda-interlomas/id649100642?mt=8

As i always said, Baker is a canvas that allows to create anything you want, the limit is just your imagination.... give a try and you will love it....

https://itunes.apple.com/us/app/impossible-machines/id927111388?mt=8
In this app i give a good use of the book donloading but is in fact more close to an app than a book.... so its up you you buddy...

Happy baking™

**Comment by nin9creative** [comment]
Just like @thejoepeach said, whatever you can create in HTML will work with Baker.
