### ISSUE TITLE
Free & Paid issues available to Subscribers

### ISSUE THREAD

**Issue by billybaughman** [bakerframework/baker#457]
I currently offer two free non-consumable issues and a free subscription. In order to encourage users to subscribe (for free) to my magazine I want to begin selling future issues. Do I make each future issue an inApp purchase? If so, will those issues then be available to those that subscribe? Thanks!

Billy Baughman
Brix Magazine for iPad

**Comment by nin9creative** [comment]
You will need to use a backend server such as Baker Cloud Console CE in order to manage paid subscriptions and issues....

**Comment by MagLoftMagazines** [comment]
Hi Billy,

Yes you would make each future issues an in-app purchase. It's important you create one for each issue and not give all issues the same IAP product id, as you would then sell all for the price of one.

As for your other question, it would depend on which publishing solution you would use. By default with MagLoft, your free subscribers would remain free and only have access to the free issues. All new subscribers would have to pay.
