### ISSUE TITLE
The Periodic Journal - Baker Hybrid - New Release

### ISSUE THREAD

**Issue by AlexAlmond** [bakerframework/baker#458]
Hi there,

We have just released our latest interactive magazine which is free to download for Auckland based magazine - The Periodic Journal - A slow living journal with beautiful photography, articles on food, health, and beauty. 

The app is a hybrid of Baker using only the HPub reader but our own development logic for everything else. Issue 01 has just been released and is for all generation iPhones, iPod Touches and iPads.

https://itunes.apple.com/app/the-periodic-journal/id969291361?mt=8

Would be great to get any feedback,
Any requests or messages to a@wearealmond.com

thanks all,

best,

Alex

![img_0286](https://cloud.githubusercontent.com/assets/11307307/7019824/cc5175a2-dd0b-11e4-9d2d-07d013f0d63b.jpg)

![img_0285](https://cloud.githubusercontent.com/assets/11307307/7019826/cc545c40-dd0b-11e4-8e0f-15780932d0fd.jpg)

![img_0283](https://cloud.githubusercontent.com/assets/11307307/7019828/cc55f37a-dd0b-11e4-933c-01e430b10127.jpg)

![img_0282](https://cloud.githubusercontent.com/assets/11307307/7019825/cc52d352-dd0b-11e4-96dc-4154d2b1de50.jpg)

![img_0280](https://cloud.githubusercontent.com/assets/11307307/7019827/cc55ef24-dd0b-11e4-9e65-2fb1b9a1657e.jpg)

![img_0279](https://cloud.githubusercontent.com/assets/11307307/7019829/cc56f1bc-dd0b-11e4-8249-dbbb212690d6.jpg)

**Comment by pieterclaerhout** [comment]
Hi @AlexAlmond, looks great, but there is a problem when you rotate your tablet to landscape. The issues are still shown in portrait...

**Comment by AlexAlmond** [comment]
Thanks for flagging @pieterclaerhout , if our book.json defines     "orientation": "portrait",
why would this still be the case? Any ideas?

**Comment by AlexAlmond** [comment]
@pieterclaerhout thanks for flagging, ill edit this :)

**Comment by AlexAlmond** [comment]
We have also released just last week, Issue 7 for London Magazine Noble Rot - fully interactive for iPhone + iPad. Portrait only on this one - https://itunes.apple.com/gb/app/noble-rot-magazine/id900613257?mt=8

**Comment by pieterclaerhout** [comment]
@AlexAlmond, which version of the Baker framework was used?

In any case, add a breakpoint ot the "supportedInterfaceOrientations" method in BKRBookViewController to check if it returns the correct value there...
