### ISSUE TITLE
Constants.h missing

### ISSUE THREAD

**Issue by douglance** [bakerframework/baker#459]
Where do I locate the constants.h file? I cannot find it in the master downloaded a few days ago. Thanks.

**Comment by douglance** [comment]
Nevermind. The constants were moved to BKRSettings.h. The FAQ should be updated.

**Comment by nin9creative** [comment]
Yeah, we need to update some of the documentation related to 4.3 changes...

**Comment by shutterflypro** [comment]
Does anyone have what needs to be done to setup the new iOS version of Baker.  I went to upgrade my apps and have no clue where to start with this new stuff

**Comment by PhoolR** [comment]
Seriously? This was flagged for Documentation Maintenance 10 months ago and it STILL isn't right??? I have no clue as to how to amend this file (BKRSettings.h) correctly. When I put in the free subscription details the way I expect to (@"com.myfreesubdetails.etc") it gives me an error (Expected and Objective-C directive after '@'). Really not helpful.

**Comment by RolandMarianna** [comment]
Bonjour,

J'ai quitté la société Newsco Group.

Cordialement,

**Comment by PhoolR** [comment]
Helpful RolandMarianna, I'm sure Newsco Group miss you, but not sure what this has to do with the price of eggs.
