### ISSUE TITLE
Does an App with Baker need internet connection to run

### ISSUE THREAD

**Issue by KrossMorris** [bakerframework/baker#461]
If I use baker framework to make an interactive book app, will the people who download it have to have an internet connection to read the book?
- Kevin

**Comment by pieterclaerhout** [comment]
No, they won't need an internet connection.

**Comment by uncledent** [comment]
If you make a book, it does not. But if you make a Newsstand Magazine, it does. But the issues are being downloaded, so users can also read them offline after downloading.
