### ISSUE TITLE
Completely customizing the baker shelf page

### ISSUE THREAD

**Issue by KrossMorris** [bakerframework/baker#462]
Can anyone walk me through if there is a way to customize the shelf page? I was hoping that instead of the page that exists now, I could have a custom menu with several buttons for things like "Read," "Credits," etc. 

Thanks,
- Kevin

**Comment by AlexAlmond** [comment]
You can customise this by implementing a storyboard for UI instead opposed to code only. I have done this for my apps Example here: http://geni.us/2wVr

This will give you more control over the UI while using the same Baker Methods. 

![noblerot-web](https://cloud.githubusercontent.com/assets/11307307/7389376/309531d8-ee65-11e4-9cb3-eebc5e8b480e.jpg)

**Comment by KrossMorris** [comment]
That's great! But how did you do that? In a nutshell

**Comment by AlexAlmond** [comment]
Hi @KrossMorris in a nutshell - create your interface with a storyboard using autolayout for iPhone and iPad, and then wire up all the methods to the UI objects. Remove any code not needed.

**Comment by thejoepeach** [comment]
@AlexAlmond Hi, it gonna be good if you show us how to do that to all not coders here... its a very complicated thing to catch up when code is not your thing...

**Comment by tobiasstrebitzer** [comment]
Thanks for the great suggestion! we prepared a pull request that integrates a storyboard #476. Upgrade is possible, but you'll need to re-do the UI customizations in settings.plist in the storyboard.

**Comment by carlosajh** [comment]
Hi @AlexAlmond,
Please, how i do customize the self? some instructions? I am not developer!!!

Thanks in advance.

**Comment by MagLoftMagazines** [comment]
Hi guys, we are working on getting the Baker up to date with the latest MagLoft changes, but it's takes a little while as we are super busy at the moment. You can see a video about how we have updated the shelf to a storyboard view and how to lightly customize it here: https://youtu.be/JZiiqj1_9as

The MagLoft Baker Repo is here:
https://bitbucket.org/magloft/magazine-application-distribution

Hope this helps a bit and looking forward to getting all this into Baker.

**Comment by omegah3** [comment]
i keep getting this error when run the fie in Xcode

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation

**Comment by nicholasmartin** [comment]
Hi @omegah3 this project requires you to install Cocoapods now (https://cocoapods.org/)

**Comment by omegah3** [comment]
@nicholasmartin in you video on Youtube you said you would provide a link to setup cocoapods. 
And i'm still getting the above error even after installing cocoapods. 
What are my missing here ?

**Comment by tobiasstrebitzer** [comment]
Hi @omegah3, 

once cocoapods is installed, you need to run "pod install" in the magazine-application-distribution directory.

Open **Terminal** (Applications / Utilities / Terminal), and then:

```bash
# Navigate into your project directory (this could be a different location)
cd Documents/magazine-application-distribution

# This command will setup the project for you
pod install
```

Once done, close XCode, and open the File "Baker.xcworkspace".
_(Note: Opening "Baker.xcodeproj" will NOT work.)_
