### ISSUE TITLE
Stop Audio Playing on Page Swipe

### ISSUE THREAD

**Issue by AlexAlmond** [bakerframework/baker#463]
Hi, 

i am looking to use audio in one of our publications, however while using -three-cards- the audio carries on playing on the next page, but i need it to stop when the next page comes into view.

I know that removing three-card mode will do this, but i require this function for the preloading of the pages.

Any ideas how i can action this?

thanks for your time,

**Comment by aspek** [comment]
```javascript 
   $(window).focus(function() {
        console.log('Focus');
    });

    $(window).blur(function() {
        console.log('Blur');
    });

**Comment by NemoMag** [comment]
@aspek : Hi! and thanx fro this. It may answer my own question (Sound continuing when going back to home #450). But could you elaborate a bit ? Where do we put this ? In each html page ? How does it work ?

**Comment by AlexAlmond** [comment]
Hi @aspek @NemoMag thanks for the feedback, i found conflicts on this, so i developed a custom js audio handler which sorts it out instead.

thanks

**Comment by NemoMag** [comment]
so we put this as a js fonction loaded onload of the page ?
If yes, that's cool, thx !
