### ISSUE TITLE
Push notifications tutorial

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#464]
Hi friends! 
This would help and I couldn't find any tutorial on this anywhere in Github, Baker Tutorials or cloud console stuff.

I have some APNS tokens in my CloudConsole, but what to do with it ?
I guessed that a provider is needed. Is it true ?

**Comment by AlexAlmond** [comment]
Hi @NemoMag ,

Yes you can use a service such as Parse to handle your push notifications. https://parse.com/
Parse is free up to a certain point. If you need any help implementing drop me a line at a [at] wearealmond [dot] com. 
I currently use Parse to handle downloads and action background downloading for my apps.

**Comment by NemoMag** [comment]
I'm digging this with parse.
Seems I need to implement it on a new version of my app : it requires some specific code in it and I can't activate it on my already "on-store" app. Is that right ?

**Comment by AlexAlmond** [comment]
Yes you'll need add the Parse code to your app delegate, and then send an app update to the AppStore.
