### ISSUE TITLE
Publishing multiple ebooks on one shelf

### ISSUE THREAD

**Issue by epublisher** [bakerframework/baker#465]
Hi there. I am totally new baker.
I need to know can I publish multiple ebooks on one bookshelf but publish it not as a newsstand app but like a single app. As I understand when I have multiple issues in baker I need to publish it as a newsstand app. I need to publish it as a simple app like a ebook store.
Thanks.

**Comment by MagLoftMagazines** [comment]
Hi @epublisher you can currently publish a stand alone version, where you can include all the books you want. Readers will see a shelf when they launch your app with the different book titles. A few things to keep in mind with a stand alone version:

1) You can only (currently) price the app itself and not sell individual books inside.
2) You can't add new books instantly, and need to add them to your app (books folder) and submit a new version.

Hope this helps.

**Comment by epublisher** [comment]
Thanks for response.
As I understand Baker is for magazines since we can't add books instantly.
I really love Baker Framework.
What do you think is it possible to do some modifications to get what I want?
I really need something to publish my ebooks as "store app".
