### ISSUE TITLE
Change Shelf VIEW

### ISSUE THREAD

**Issue by epublisher** [bakerframework/baker#466]
Hi there. Help me please with this.
I want to add some extra spaces for book shelf view.
At this moment we have only Title and Description.
I wan't to add for example Author, ISBN and other fields to the shelf view.
![screen shot 2015-05-04 at 3 11 14 pm](https://cloud.githubusercontent.com/assets/6705018/7452579/f4839bc4-f267-11e4-8c2e-a25d5b8acde8.jpg)
Also I want to add search field to the shelf view.
Thanks

**Comment by tobiasstrebitzer** [comment]
Hi @epublisher we prepared a pull request that integrates a storyboard #476, which will make customizations like this very easy (a little coding is required, but you can basically copy the behaviour of 'info label').

**Comment by Kaze919** [comment]
@tobiasstrebitzer I'm having issues properly downloading the files from your pull request is it possible to package them to download elsewhere?

**Comment by carlosajh** [comment]
@tobiasstrebitzer Please, how i do customize the self? some instructions? I am not developer!!!

Thanks in advance.

**Comment by MagLoftMagazines** [comment]
Hi guys, we can package the latest version of our MagLoft Baker app and create a video, but we have implemented CocoaPods in our version, so you might want to look into getting your machine updated to be able to run pod install.

We have also added a few other features like universal login and issue settings, but these currently require our backend to work. You can see a demo of the latest iOS MagLoft Baker app here: https://www.youtube.com/watch?v=rRqC2-eW_dk (skip to 24:30 in the webinar).

We love this community and we will be sharing all the cool stuff that we come up with. At the moment we are branched out a lot, but I know @tobiasstrebitzer want's to share all the goodies as soon as we can. Until then, if you are interested in using our system, we will make sure to offer you a great deal coming from this Baker community, just let me know.
