### ISSUE TITLE
strange behavior in version 4.3.2

### ISSUE THREAD

**Issue by Jonathanfoo85** [bakerframework/baker#469]
Hi Guys, 

I am quite new to this, i have recently discovered a strange glitch. when we are designing a page that is longer than 1024px. single tap on a specific area on the iPad screen will move the page down. (picture attached highlighted the specific area). i am not sure its a feature or a glitch. but it prevented us from placing any button etc  on that area in our html. Using the same book "study-in-scarlet" i have tried different versions to build the app and tested, baker 4.2.1 works fine. so i am pretty sure its not our html that is causing the issue. 

hopefully this is a newly discovered glitch. i am really thankful for this framework. 
thanks again. 

![problem](https://cloud.githubusercontent.com/assets/8066225/7787332/dd0d4b12-0238-11e5-986f-456fba3ed282.jpg)

the above picture highlights the affected area on a iPad screen. Same thing happened to other pages. Same area as highlighted.

**Comment by tobiasstrebitzer** [comment]
Hi @Jonathanfoo85,

thanks for sharing this, i can confirm the glitch.

I've investigated the code and found the following section:
```
- (void)setTappableAreaSizeForOrientation:(NSString*)orientation {
    //NSLog(@"[BakerView] Set tappable area size");

    CGFloat screenWidth = [[UIScreen mainScreen] bkrWidthForOrientationName:orientation];
    int tappableAreaSize;
    if ([orientation isEqualToString:@"portrait"]) {
        tappableAreaSize = screenWidth / 16;
    } else {
        tappableAreaSize = screenWidth / 7;
    }

    upTapArea    = CGRectMake(tappableAreaSize, 0, screenWidth - (tappableAreaSize * 2), tappableAreaSize);
    downTapArea  = CGRectMake(tappableAreaSize, screenWidth - tappableAreaSize, screenWidth - (tappableAreaSize * 2), tappableAreaSize);
    leftTapArea  = CGRectMake(0, tappableAreaSize, tappableAreaSize, screenWidth - (tappableAreaSize * 2));
    rightTapArea = CGRectMake(screenWidth - tappableAreaSize, tappableAreaSize, tappableAreaSize, screenWidth - (tappableAreaSize * 2));
}
```

1. The "tappable area" is not calculated correctly.
2. There is a setting to disable horizontal tap (switch page): bakerPageTurnTap; there should be an equivalent setting to enable/disable vertical taps (scroll up/down).
