### ISSUE TITLE
Image issue 

### ISSUE THREAD

**Issue by omegah3** [bakerframework/baker#472]
All the HTML images on a Newsstand Magazine app i made in Baker Framework are showing up very dark on iOS devices, but when viewed on the regular browser they show up normal.

What might be the issue, please help.

**Comment by jakeosx** [comment]
(sorry for the delayed response)

i would check the color pallet-- if your images are CMYK you'll get that, they should be RGB

**Comment by tobiasstrebitzer** [comment]
@omegah3 did you manage to solve this issue?
