### ISSUE TITLE
This error again Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker#477]
I opened my current version of baker to run it in iOS 9 and I had this error for some reason
![screen shot 2015-06-11 at 12 34 31 pm](https://cloud.githubusercontent.com/assets/5607372/8116332/5edb45a8-1036-11e5-97a8-3e57d92768b8.png)

I remember getting it before and to fix it I had to add the Bolts framework. But the bolts framework is already there, I re added it but not luck. Doesn't work in Xcode 6 or in Xcode-beta 7

**Comment by MagLoftMagazines** [comment]
Hi @codegeek511 I saw this one as well earlier, and I believe @tobiasstrebitzer already has a fix for it. He will check this out as soon as Europe wakes up today :)

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511,

i ran into the same problem once. It seems that you've added the Parse (+Bolts) framework to your project, but didn't select 'copy files to project dir' when doing so. Your frameworks therefore were linked from outside your project dir. I assume the files got removed (or moved) eventually, and since then xcode complains that it can't find the frameworks in the remote location ("parse-library-1.4.1").

Try to remove all references to this folder (using project-wide search for "parse-library-1.4.1", also look in the library search path), and afterwards drag Parse and Bolts framework into your project frameworks, and choose 'copy files to project dir'.

Let me know if that works.

Cheers, Toby

**Comment by codegeek511** [comment]
Hi @tobiasstrebitzer sorry I took so long to get back, I have been very busy this last month. I finnaly had a chance to look at this and it did fix that error, but then like good old classic programming fixing that error caused 10 more to pop up ¯\_(ツ)_/¯. I deleted the references then re added them, this is what i did:
![screen shot 2015-07-15 at 11 20 59 am](https://cloud.githubusercontent.com/assets/5607372/8706328/1727a5bc-2ae4-11e5-946c-a1c7be9398bf.png)

after doing so these came about 
![screen shot 2015-07-15 at 11 24 57 am](https://cloud.githubusercontent.com/assets/5607372/8706346/2bac69d2-2ae4-11e5-86a3-e22fa8ee331a.png)

so something isn't completely right with the added frameworks yet. Is their another way to add them? Cause no where did I see copy files to project dir

**Comment by codegeek511** [comment]
UPDATE: @tobiasstrebitzer So I have been looking at this more, I cleaned the build folder re added the frameworks only to get to a new set of errors. now it is complaining about the Google Analytics Library which is already there and I haven't touched it.

![screen shot 2015-07-21 at 3 41 22 pm](https://cloud.githubusercontent.com/assets/5607372/8814254/357477a4-2fbf-11e5-9e40-197f0e3c062e.png)

I don't no what's going on really.

**Comment by codegeek511** [comment]
ANOTHER UPDATE: So I fixed the last errors by re adding the Google Analytics folder (which I had never touched before hand) and now its saying it can't find the GAI.h file, which is in the Google Analytics folder. This is really frustrating because I'm not even using Google Analytics. And I can't just delete the folder.

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511, do you mind sharing your xcode project with me (toby@magloft.com), then i'll have a quick look at it myself.

**Comment by Kaze919** [comment]
I am also getting this error specifically after implementing the analytics.

**Comment by codegeek511** [comment]
@tobiasstrebitzer @MagLoftMagazines Haven't heard back from you in over a month. I emailed the project but have heard nothing since, iOS 9 release is right around the corner.....should I just start over on a fresh build? Do you guys have an iOS 9 version ready yet?

**Comment by codegeek511** [comment]
@MagLoftMagazines @tobiasstrebitzer @nin9creative Is anyone there?

**Comment by MagLoftMagazines** [comment]
Hi @codegeek511 sorry for the delay, I think we are all super busy.

There could be several reasons for this error, and we have moved to CocoaPods to manage external libraries. I'd be happy to share our latest Xcode version with you and give you a quick tour of how it works. 

In order for you to run our version, you need to setup CocoaPods on your Mac:
https://guides.cocoapods.org/using/getting-started.html

We don't have any issues running CocoaPods and with our version you'd get a few more features like fully implemented Storyboard and two different layout options. I'll be back later with setup instructions and a tour of the Storyboard.

**Comment by MagLoftMagazines** [comment]
I know this isn't a fix but perhaps a way around the current problem. Here is our public repository for the MagLoft Baker version: https://bitbucket.org/magloft/magazine-application-distribution

And here is the short video I promised on how to customize the new Storyboard shelf:
https://youtu.be/JZiiqj1_9as

Let me know what you think?

**Comment by nin9creative** [comment]
I'm not able to check right now, but perhaps @pieterclaerhout can chime in if he sees this.
Andrew

**Comment by codegeek511** [comment]
@nicholasmartin Sorry for the late response, I have been digging my head into TVOS lately. I finally downloaded the new Xcode proj and I installed Cocoa Pods. I do need some help on add the cocoa pods to the project. After that I think between your video and my know how I will be up and running again.

**Comment by codegeek511** [comment]
@nicholasmartin good news I figured it out (I think). I thought I had to make Podfiles, but then I realized all I had to do was run pod install in the directory of the project, after that I opened the workspace and built it, and it worked! :)

**Comment by nicholasmartin** [comment]
Great happy to hear that :)
