### ISSUE TITLE
iOS9 and beyond

### ISSUE THREAD

**Issue by Liamam** [bakerframework/baker#479]
I watched Apple's keynote and saw the introduction of the News app - and I thought 'oh crap' then I watched Ed Dales video which showed all the previous Newsstand apps in a new generic folder called Newsstand -  and I felt much better. He said that the News app is a great opportunity to promote your 'ex' Newsstand app especially with iAd integration. 

I then thought further about what other publications have done outside Newsstand and the Fast Company app sprung to mind which provides magazine issues as well as a newsfeed. 

So I thought if this is something that could be done for Baker? I would like to give it a go myself by adding the feed when the user presses the info button (which could become news). I'm not a coder, but have done bits and bobs so would be flying blind. I thought about somehow using this example on App Coda which uses Parse as a back end  CMS >> http://www.appcoda.com/ios-programming-app-backend-parse. 

Ed Dales video on NewsStand Carnage can be found at >> http://www.eddale.co/general/newsstand-carnage

Anyway would be interested in hearing peoples thoughts as i personally think this could give the best of both worlds.

**Comment by MagLoftMagazines** [comment]
I think it's a great idea. With Baker shelf now being transformed to a story board (https://github.com/bakerframework/baker/pull/476) it opens up for a lot of variation. Perhaps we will give it a stab as well or for sure willing to help hint hint @tobiasstrebitzer. We already have plans for a HTML header so publishers can update content there without having to publish a new app version.

**Comment by bobwol** [comment]
Hi all,

I found an official Apple page talking about the iOS 9 changes regarding Newsstand: https://developer.apple.com/newsstand/

Updates in iOS 9
Changes are coming to Newsstand this fall with iOS 9. While **publishers can still distribute periodicals on the App Store with auto-renewing subscriptions**, the Newsstand app will no longer be pre-installed.

What to Expect
**Individual Newsstand apps will now install directly to the Home screen**. If a customer had Newsstand apps installed prior to updating to iOS 9, Newsstand will become a folder titled “Newsstand” and their existing apps will be placed in this folder.
**Newsstand app icons will no longer be the cover of the latest issue**. You should review and update your App icons.
You will still be able to update your issue preview screenshots and metadata without submitting a new binary.
Background downloads will continue and **existing subscriptions will be unaffected**.
 

------------------
- No mention about NewsstandKit deprecation. Sounds a good news.


Any new thoughts on this?

**Comment by pieterclaerhout** [comment]
From what I can see and what we've tested, all NewsstandKit things will keep on working on iOS 9. The only different is that the apps will be installed directly on the home screeen and will show their app icon instead of the cover of the latest issues.
