### ISSUE TITLE
SVG. Huge performance difference: web page and Baker

### ISSUE THREAD

**Issue by divlv** [bakerframework/baker#480]
Hi, All!
I've crated a Baker page with SVG content.
In fact this is a converted PDF page with text and embedded graphics.
So, I noticed a huge performance difference between viewing this page on mobile Safari
and viewing it as a Baker page.
Viewing it on Baker is really slow.
Why so?
And... how to speed up this?

(btw, splitting to the several pages and showing in html table improves performance a bit, but, it's still slow)

**Comment by pieterclaerhout** [comment]
I think this is caused by the fact that Baker uses UIWebView which doesn't have a JIT compiler. In Mobile Safari, WKWebView is used which is a lot faster. However, we cannot use thus yet in Baker as it doesn't support loading files over the file protocol (which is crucial for Baker).

**Comment by MagLoftMagazines** [comment]
@pieterclaerhout is absolutely right on this. We tried to utilise SVG but there was no way to get performance at a level that was even readable. Apps would run out of memory and crash. See http://www.openradar.me/radar?id=5839348817723392 for the bug report.
