### ISSUE TITLE
IAP restore doesn't work

### ISSUE THREAD

**Issue by quba88** [bakerframework/baker#483]
hi all. 
I'm trying restore purchases, in sandbox mode work properly, but after review, recovery doesn't work.
I've no idea what had happened.

I'm working with baker 4.3, Xcode 6.3.2, Newstand app

Can anybody help me with this?

Thank you!
quba

**Comment by nin9creative** [comment]
What backend are you using?

**Comment by quba88** [comment]
BakerCC (Baker cloud)
