### ISSUE TITLE
Could not read the shelf from the device

### ISSUE THREAD

**Issue by madrenderman** [bakerframework/baker#484]
Hello guys, 
sorry if this was asked before but I searched on the forum and didn't find a solution.
I'm testing an app created with baker Android on the device (a Samsung Galaxy Note 3 Neo), everything works fine but when I launch the app on the device it returns the error  'Could not read the shelf from the device' and the app close.
Inside Android Studio I changed all the paths in the 'strings.xml' file so I don't know what I'm doing wrong
Anyone can help me ?

This is the path to the json file: http://www.thefridgefoundation.org/rivista/shelf.json

Thank you

Ray

**Comment by nin9creative** [comment]
You might have better luck on the Android Repo...

https://github.com/bakerframework/baker-android-refactor

**Comment by madrenderman** [comment]
Thank you I'll try

2015-07-13 4:50 GMT+02:00 Andrew <notifications@github.com>:
