### ISSUE TITLE
HPUB Packaging Software

### ISSUE THREAD

**Issue by shutterflypro** [bakerframework/baker#486]
Ok, I have been floating around and using Baker for over a year now.  It is by far the best software out there.  The only design I saw was having anyway that could put the magazine together after we finished designing it.  We even bought the InDesign Plugin that is out there but had way to many problems and were always having to tweak our layout or something to get it to output properly.  A process that usually took us hours.  InDesign produced lovely PDFs that we needed to send to have the magazine printed anyway so I was thinking, wouldn't it be nice to have software that could break-down my PDF and package it as a PDF.  I waited and waited and no solution ever came about, so I wrote one.

Its pretty easy to use.  A single screen.  Drag that PDF onto the folder & choose your output folder.  Make a couple of selections that are needed in the HPUB and hit process.  It will do everything for you and leave you with the zipped HPUB that is ready to upload to your server.  It even cleans up after itself.  It creates a nice deliverable that is an ideal size.  Did I mention that it is fast!  My magazines process in under a minute.

Currently it is available on the Mac App Store.  If there is a huge demand I will make a Windows Version.
https://itunes.apple.com/us/app/mag-creator/id1012036539?ls=1&mt=12

Currently it does not handle interactive media and videos.  This is a feature I am working on and will release shortly.

Other features, please let me know what you need or what you want and I will integrate them as soon as possible.  This software was developed for Baker and HPUB. Let me know your thoughts.

**Comment by thejoepeach** [comment]
Amazing, if need a few testers just let me in...

**Comment by Kaze919** [comment]
Interesting. Find a way to get videos and simple animations like fade ins and fly ins and I'm sold.

**Comment by Sror** [comment]
very expensive, and the price does not encourage to test a product just released!

**Comment by Kaze919** [comment]
Well it's cheaper than in5 which is almost 5x more.

**Comment by nin9creative** [comment]
Seems like a pretty nice solution..  What has been the user feedback so far?

**Comment by corsa** [comment]
Looks interesting. Can you link to a sample HPUB that was exported using this app? Am curious as to whether each page is rendered in HTML, or if each page is turned into a big image file that is embedded in an HTML page, or is a PDF file embedded on each page in the HPUB, or what. Thanks.

**Comment by shutterflypro** [comment]
As of right now it is an image rendered into each page.  I will be more than happy to add other formats and ways of doing it if people show an interest in it.

This was built in a way that I needed to make work.  I know there are lots of other ways to do things and they should be relatively easy to add in, just need people to show me a little support.

Raymond

**Comment by corsa** [comment]
Cool, thanks for the reply. We are evaluating using the Baker framework for an upcoming project, and workflows like the one you have made possible are definitely points in the favor of using the framework.

**Comment by MagLoftMagazines** [comment]
Very cool stuff @shutterflypro! That's basically what we did in MagLoft as well. You can upload a PDF and MagLoft will transform it into an HPUB. You are also able to open the issue in our editor and overlay with Soundcloud, YouTube, Vimeo and other interactive widgets as well.

Up until now, MagLoft has only been a premium offering, but we will very soon be releasing our freemium offering, where publishers and bloggers can get their free apps published in app stores, powered by advertisements. We are looking for a few people to BETA test this feature, and I couldn't think of a better crowd then you guys in here. If you're interested, please let me know by emailing support@magloft.com

**Comment by thejoepeach** [comment]
@nicholasmartin Amazing, your freemium offer seems pretty nice, let me be your beta tester if you like....

**Comment by nicholasmartin** [comment]
Thanks @thejoepeach we will let you know :) The Free version just got beefed up as it will sport a list building feature to collect emails. More to come :)
