### ISSUE TITLE
Change selected issues to Download after subscribed

### ISSUE THREAD

**Issue by snowywolfie** [bakerframework/baker#487]
I trying to unlock the selected book after subscribed. I was able to subscribed but it unlocked all the existing issues. How can I just unlock specific issues only instead of all of them?

Btw i read the guides in https://github.com/Simbul/baker/wiki/Baker-Server-API,
but I have no clue where to include the following code, which is what i want.
{
  "issues": ["com.example.MyBook.jan2013", "com.example.MyBook.feb2013", "com.example.MyBook.mar2013"],
  "subscribed": false
}

**Comment by nin9creative** [comment]
You are writing your own backend to handle this?

I would look at the logic in the Baker Cloud CE API for how things work there.
