### ISSUE TITLE
PHP Error encountered while running PHP 5.6 / Baker Cloud Console

### ISSUE THREAD

**Issue by Kaze9** [bakerframework/baker#489]
I was troubleshooting some things because I'm not totally familiar with SQL databases and subdomains and whatnot but I was getting a PHP error for a few items related to the Cloud Console source files. I was on with my hosting provider's support line and my PHP version was 5.6. When they downgraded it to 5.5 everything began working fine.

Is there a specific issue with running PHP 5.6 that needs to be fixed or was there something I did incorrectly in the setup?

**Comment by corsa** [comment]
I got errors too when trying to run it under PHP 5.6, downgraded to 5.5 and worked again, so I think it is an issue in Baker Cloud Console.

**Comment by nin9creative** [comment]
Yeah, I haven't tested it on newer versions of PHP.  It's on my list to look into.

**Comment by Manbur** [comment]
any solution for this problem?

**Comment by drhounsell** [comment]
Has anyone solve this problem? My provider just upgraded to PHP 5.6, and now I get an error with Baker Cloud, and the app can't download any content.

**Comment by GennadyK** [comment]
You may try to go over this list:
http://php.net/manual/en/migration56.incompatible.php
I would start from these one:
json_decode() <http://php.net/manual/en/function.json-decode.php>
<http://php.net/manual/en/migration56.incompatible.php#migration56.incompatible.json-decode>
