### ISSUE TITLE
Background turns gray when swipe

### ISSUE THREAD

**Issue by Rexios** [bakerframework/baker#490]
With baker 4.2.1 and ios 8.4, when I swipe page background turns gray, with double tap turns white.
I publish quartly but this behaviour is only in the last number.

**Comment by Kaze919** [comment]
Did you revert back to the original study in scarlet file when you made this previous issue? The default background was gray. It was set in the book.json file as an image.

**Comment by Rexios** [comment]
Thank you very much, I try as soon as possible.
Emanuele

Inviato da iPad
