### ISSUE TITLE
iOS9 Testing

### ISSUE THREAD

**Issue by drhounsell** [bakerframework/baker#491]
Has anyone tested their app with iOS9 yet? 
Besides the app not being in Newsstand anymore, I was wondering if anyone has found any bugs or errors. 

Thanks!

**Comment by MagLoftMagazines** [comment]
Hi @drhounsell,

We have been testing and the biggest "problem" now is the deprecation of transactionReceipt in iOS7 is crashing iOS9 apps. See this for more info: http://stackoverflow.com/questions/18903879/transactionreceipt-for-in-app-purchase-is-deprecated-in-ios-7-what-can-i-replac?rq=1

Also, the new receipt format will require all backends to handle the receipt data slightly differently as the format has changed. Now you only get 1 receipt from Apple with all the IAP for that app. Currently we get a receipt for each IAP.

These are the two main things that need to be solved. A part from that it seems to be working fine outside of Newsstand :)

**Comment by drhounsell** [comment]
Thanks Nick!
Will this require an update to Baker Cloud along with Baker Framework?

**Comment by MagLoftMagazines** [comment]
Yes, all baker NEWSSTAND apps and the Baker Cloud will have to be updated. I am not sure about standalone apps, as they don't offer IAP, but due to the new way of handling receipts from iOS9, we will have to update apps using IAP and the backend needs to be updated to handle the new receipt format.

**Comment by drhounsell** [comment]
I couldn't find any comments on iOS 9, but I did see some differences in my PurchasesManager.m file and the new one. Is it just a matter of me replacing this file? Is there any documentation on what needs to be done to Baker Cloud?

**Comment by drhounsell** [comment]
So I recreated the app with the latest baker master, and downloaded the latest Xcode 7 beta. I'm getting These warnings, and in the simulator I'm getting a "no internet connection" message (and shelf not showing). In Xcode 6, everything appears to be working fine. Also I did the "update to recommended setting" shown in the screen shot, didn't fix it. 

![screen shot 2015-07-22 at 2 04 36 pm](https://cloud.githubusercontent.com/assets/8028631/8833952/84a79278-307f-11e5-8521-f8a209df0aa0.png)
![screen shot 2015-07-22 at 2 04 50 pm](https://cloud.githubusercontent.com/assets/8028631/8833951/84a757fe-307f-11e5-86cb-25052083b721.png)

**Comment by pieterclaerhout** [comment]
The no internet connection is probably caused by the new App Transport Security feature that is part of iOS 9. If you are not connecting to an https url, there are extra steps you need to take to make it work:

http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

Also, in regards to the transactionReceipt deprecation, just commenting out the new code is not enough. It does fix the deprecation warning, but the parsing of the receipts will fail on both the end of the app and on the end of the server backend...

**Comment by drhounsell** [comment]
Thanks, that link fixed the “no internet connection” problem. If I did change the server that Baker Cloud is on from HTTP to HTTPS would I need to make any changes to the app?

Now I’m getting “Purchase failure, Cannot connect to iTunes Store” with the IAPs. This must be what you meant by “the parsing of the receipts will fail”

I’m trying to get a jump on this before iOS9 drops to prevent angry readers. Does anyone have a fix for this yet? My background is graphic design so I have relied heavily on this community (which is awesome, btw) to create and keep my app running smoothly.

**Comment by pieterclaerhout** [comment]
From what I can see in the documentation of Apple, the transactionReceipt property has been deprecated since iOS 7, but it's still there in iOS 9 and it still works (at least, that's what our testing is showing). The Baker framework should eventually transition to the new unified transaction receipt, but iOS 9 will not break an existing app if you keep on using the deprecated transactionReceipt.x

**Comment by nin9creative** [comment]
@pieterclaerhout I think you are correct.  I'm hoping that iOS9 doesn't break things because as you mentioned there will need to be changes on both ends.

**Comment by MagLoftMagazines** [comment]
As long as the deployment target in Xcode is set to 7 it should work. When I was initially testing I had it set to 8 or 9. This buys us a little more time :)

**Comment by uncledent** [comment]
@MagLoftMagazines, we have to do nothing right now? The app should not be updated?

**Comment by drhounsell** [comment]
I put iOS 9 beta on my iPad today and the app is running fine. The "purchasing failure" error I mentioned earlier appears to only happen inside the Xcode simulator. I'm so glad iOS 9 isn't going to be a big problem.

**Comment by lumierephoto** [comment]
I was having the same issues with the network connection on iOS 9. The the link provided about App Transport Security helped.

See link:  http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

Especially this portion:
     
     <key>NSAppTransportSecurity</key>
          <dict>
      <key>NSExceptionDomains</key>
          <dict>
      <key>yourserver.com</key>
          <dict>
          
          <key>NSIncludesSubdomains</key>
             <true/>
             
           <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
              <true/>
           
            <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.1</string>
               </dict>
             </dict>
           </dict>
