### ISSUE TITLE
iOS 8.4 subscription problem

### ISSUE THREAD

**Issue by uncledent** [bakerframework/baker#492]
Lately we discovered a problem, that the latest issue has not been opened after a subscription purchase on 8.4. I took a look at the log and yes, it is being recognised as an issue_ not a subscription. Here is the log from the web app:

Confirming purchase for APP ID - Sandbox Receipt used in Production, retrying against Sandbox iTunes API: com.test.myapp USER ID: 77B7C67C-E619-425D-8CA5-B89F675F5C46 TYPE: issue

Have anyone had this problem? It is a big issue for us, as we have many complaining users.

**Comment by MagLoftMagazines** [comment]
This might be a silly question, I haven't actually tried/tested this before, but is there any chance that the product_id's got mixed up in Xcode?

**Comment by uncledent** [comment]
It was an issue with $type variable in the /confirmpurchase/ part of api. $type is not set which caused an error. I have no idea why it worked before and stopped working suddenly. I have just removed this variable to make things work again.

**Comment by mghazaly** [comment]
uncledent, how did you resolve this issue.... can you explain with a little more detail?

I have looked at /confirmpurchase/ and it seems that the variable $type is being used throughout. How did you remove it?

**Comment by uncledent** [comment]
Just remove it in the PHP code, it is not assigned.

**Comment by mghazaly** [comment]
Sorry, I still don't understand. How can I remove `$type` while it is being used, for example, like below:
```
// If successful, record the user's purchase
			if($type == 'auto-renewable-subscription'){
				markIssuesAsPurchased($iTunesReceiptInfo,$app_id,$user_id);
			}else if($type == 'issue'){
				markIssueAsPurchased($iTunesReceiptInfo->receipt->product_id, $app_id, $user_id);				
			}else if($type == 'free-subscription'){
				// Nothing to do, as the server assumes free subscriptions don't need to be handled in this way			
			}		
```

Thanks!

**Comment by mghazaly** [comment]
I think the variable `$type` is important since it is used to differentiate between a single issue purchase or a subscription.

The current problem I'm facing is that when I click restore purchases (I'm already subscribed), I get a pop-up message saying "Processing...." and nothing else happens.
