### ISSUE TITLE
Encoding problem for Newsstand Atom Feed

### ISSUE THREAD

**Issue by uncledent** [bakerframework/baker#493]
Cyrillic characters are being shown incorrectly in the atom feed, even though utf-8 is set. What could cause this?
<img width="1430" alt="screen shot 2015-07-28 at 08 53 19" src="https://cloud.githubusercontent.com/assets/6542981/8925210/311a254a-3506-11e5-9f9c-dd1f129fc99f.png">

**Comment by nin9creative** [comment]
How is the Atom feed being generated?

**Comment by uncledent** [comment]
@nin9creative it is a backend feature, we haven't made anything by ourselves, it was already there. domain.com/itunes/app_name
