### ISSUE TITLE
Index Menu Open at Startup

### ISSUE THREAD

**Issue by Kaze9** [bakerframework/baker#498]
Is there a way to prevent my Index Bar from popping open momentarily when my magazine loads? It's very distracting and unsightly to have happen every time a magazine is loaded.

**Comment by nin9creative** [comment]
Are you talking about when you click on the magazine from the shelf and it transitions to the magazine view?

**Comment by Kaze919** [comment]
When I click on the "Read" button from the shelf view it launches the magazine and the Index window (what pops up when you double tap) is open then closes.


Also for the life of me it keeps opening on a different page despite having start on page field set to 1
