### ISSUE TITLE
Side panel links do not react on iPad

### ISSUE THREAD

**Issue by anitannesh** [bakerframework/baker#500]
Hi all,

The e-book I have designed has side panels to display extra information (see screenshot). 
These panels have links (the icons on the top) to navigate through them, but they do not seem to work on the iPad. When I test them on a browser they work just fine. Any idea what could be happening here?

Thank in advance.

Cheers,

Ana
![img_0557](https://cloud.githubusercontent.com/assets/13909865/9419648/63db5a8c-4855-11e5-947c-b18587183449.PNG)

**Comment by anitannesh** [comment]
Can it have something to do with the internal links within the book? I have looked everywhere...
This is a prototype for my major project, so if anybody could help that would be great...

**Comment by tobiasstrebitzer** [comment]
Hi @anitannesh,

how did you create this sidebar? is it using an iframes or javascript to switch between the panels?

Can you share a snippet of the code?

**Comment by nicholasmartin** [comment]
Hi @anitannesh, is there anything to report on this issue? Can you share a little more info with us?

**Comment by anitannesh** [comment]
Hi all, 

At the end I created multiple panels to solve this, but this is the code that I was using when the navigation did not work: http://www.petelepage.com/blog/2011/07/showing-hiding-panels-with-html-and-css/
