### ISSUE TITLE
Cookie support in Baker?

### ISSUE THREAD

**Issue by particleandparcel** [bakerframework/baker#501]
Hi all,

I've been using Baker to develop an app that serves as both a project book for prospective clients to download, and a presentation tool for employees to use with prospective clients in person. So we're wondering whether we can show/hide UI elements based on whether the user can authenticate as an employee.

Does BKRBookView support cookies like a standard web browser? I was initially thinking I could put in a "Login" button, and then make an Ajax call to a tiny little service on our web server which would validate username against a database, and store boolean yes/no in a cookie.

If not, has anyone experimented with iOS username/password login?

I'm not an iOS programmer so writing that code from scratch feels pretty daunting, but I studied some C in college, so I can at least follow along with an example. (For example, I was able to get Analytics running.)

Thanks!

**Comment by MagLoftMagazines** [comment]
We have just recently implemented this in our Baker versions of iOS and Android and I know @tobiasstrebitzer will be sharing that implementation here as soon as he has a little spare time. It's really much more a backend implementation then Obj-C (at least the way we did it). The Baker app already allows you to send app_id and user_id via JS (https://github.com/bakerframework/baker/wiki/Use-baker-javascript-events). Anyways, Tobias can explain a lot better then I can :)

**Comment by tobiasstrebitzer** [comment]
Hi @particleandparcel,

we solved this by placing an iframe in the Info Tab (info.html), opening a backend view to handle the login. Alternatively you can also do that inside an issue.

We've created a login- and signup- form in our backend to handle the workflow. Additionally, we're submitting the device user_id and app_id to our backend (for unlocking issues between different devices).

This is how our login form looks like:
http://www.magloft.com/readers/sign_up

***index.html:***
```html
<iframe id="login"></iframe>

<script type="text/javascript">
  var iframeElement = document.getElementById("login");
  if(iframeElement) {
    # you need to inject the user_id and app_id into your info.html
    # and update the iframe source to pass along user_id and app_id to your backend.
    iframeElement.setAttribute("src", "http://www.magloft.com/readers/sign_up?user_id="+payload.user_id+"&app_id="+payload.app_id);
  }
</script>
```

**Comment by MagLoftMagazines** [comment]
Hi @particleandparcel did this help you? Can we close this topic?

**Comment by particleandparcel** [comment]
Sorry, I missed the original e-mail notification. I'll have to try this.
However, my understanding is that info.html is only rendered for
Newsstand publications, right? We're doing a single-issue build.


On Wed, Sep 23, 2015, at 09:33 PM, Nick Martin wrote:
> Hi @particleandparcel[1] did this help you? Can we close this topic?


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/particleandparcel
  2. https://github.com/bakerframework/baker/issues/501#issuecomment-142778546
