### ISSUE TITLE
Media: audio still playing in page after I close the ebook

### ISSUE THREAD

**Issue by Hikarikun92** [bakerframework/baker#503]
I created a sample ebook and added attribute "-baker-media-autoplay": true in my book.json file so that I could play an MP3 in my page using HTML5's audio tag. However, when I closed the book while being on that page, the audio still kept playing, and if I entered the ebook again, the song played again (that is, two audios playing at the same time).
I was able to do a workaround by adding the following code to "viewWillDisappear" in BKRBookViewController:

[self.currPage loadHTMLString:nil baseURL:[NSURL URLWithString:@"#"]];

I'm not sure if that's the best solution, but that solved my problem. I'm also not sure if that will clean up the memory. Using "nil" as arguments to that method showed a log message saying "about:blank" was not supported.

I was using iOS Simulator with XCode 6.2.

**Comment by eivanphils** [comment]
Hello @Hikarikun92 ,

Try this code:

<div class="dossier-start-bg">
    
    <audio id="music"><source src="images/dossier-01/song/music.mp3" type="audio/mpeg"/></audio>
 
    <a class="play1" id="play" onclick="playSong()"></a>
</div>

<script type="text/javascript">
    function playSong(){
    	$('#music')[0].play();
    	$('#play').attr("onclick","pauseSong()");
        $("#play").removeClass("play1");
        $("#play").addClass("pause1");
    }
    function pauseSong(){
    	$('#music')[0].pause();
        $('#play').attr("onclick","playSong()");
        $("#play").removeClass("pause1");
        $("#play").addClass("play1");
    }

    window.addEventListener("blur", function stopSong() {
        $('#music')[0].pause();
        $('#play').attr("onclick","playSong()");
        $("#play").removeClass("pause1");
        $("#play").addClass("play1");
    }, true);
   </script>



-------------------------Style Css--------------------------------------------
/*This style is only if you need to give a position element*/
.play1 {
	position: absolute;
    left: 35.46%;
    top: 5.04%;
    width: 35%;
    height: 15.58%;
    background-repeat: no-repeat;
}


audio, audio:active { outline: none; }
audio {
	display: block;

}
.songs{
	display: block;
	margin: 0px;
}




I hope it helps you.

**Comment by Hikarikun92** [comment]
The audio must be played automatically in my application, there must not be any user interaction other than the page loading and the book being closed...
