### ISSUE TITLE
hanging up on buying after purchase 

### ISSUE THREAD

**Issue by hecklerguy** [bakerframework/baker#505]
So Ive had a few people saying when they go to purchase an issue of my mag that it goes through iTunes and they can purchase but after they buy and it goes back to the app the buy icon just keeps spinning and so they refresh the page and it goes back to them having to pay again but when they click on it tells them they have purchased it but keeps spinning and does not go to the download button. But they keep trying and it eventually comes up and they can download.  How can I fix this as some customers won't know to keep trying and it does not happen to all customers. Not sure if its because of how they are paying or what. I saw a post on here with a similar issue- https://github.com/bakerframework/baker/issues/499

**Comment by nicholasmartin** [comment]
Hi @hecklerguy, this sounds very familiar and something that was previously tackled. Have a look at some of these older issues:
https://github.com/bakerframework/baker/issues/309
https://github.com/bakerframework/baker/issues/357
https://github.com/bakerframework/baker/issues/293

What Baker version are you using? If you have your tracked in git, have you tried to update to latest master?

**Comment by nicholasmartin** [comment]
Actually there was just a similar report not long ago with a fix here: https://github.com/bakerframework/baker/issues/499 Check that out first.
