### ISSUE TITLE
Upgrading to Ubuntu 14.04.1 LTS for Baker cloud?

### ISSUE THREAD

**Issue by lumierephoto** [bakerframework/baker#507]
Currently, I'm on Ubuntu 12.04.5 LTS and I haven't updated it. I'm afraid it will break all the hard work I've done and I'm not a backend developer really.

Has anyone updated or running Ubuntu 14.04.1 LTS?  Did it break anything?

Thanks

**Comment by nin9creative** [comment]
The backend is more dependent on the PHP version more than anything.  I haven't actually tested it with newer versions of the PHP framework.  I'm hoping to get some time shortly to make some updates...

**Comment by lumierephoto** [comment]
Oh OK, so it's the PHP version that's dependent. That makes sense. 

I think I'm going to stay at Ubuntu 12.
