### ISSUE TITLE
call facebook url from book fail

### ISSUE THREAD

**Issue by nevoeiro** [bakerframework/baker#510]
Hi there,

When I try to access a facebook url from my book I get a blank page and the link doesn't open. On my code I'm using

<a href="https://www.facebook.com/profile.php?id=100008240922259?referrer=Baker"><i class="fa fa-facebook fa-lg"></i> &nbsp; Facebook DP</a>

**Comment by nevoeiro** [comment]
someone can help with this?

**Comment by Manbur** [comment]
Can this be what you need?

https://github.com/bakerframework/baker/issues/273

**Comment by aspek** [comment]
@Manbur  It does not work anymore. 
@nevoeiro I found solution here
http://stackoverflow.com/questions/17677792/not-able-to-load-facebook-fan-page-wall-in-uiwebview
Please let me know if this will work.
