### ISSUE TITLE
internal browser keeps alive after press back button

### ISSUE THREAD

**Issue by nevoeiro** [bakerframework/baker#511]
When I access a youtube webpage from my book and play a video, then I tap the Back button to get back to Baker app, the internal browser is not erased but simply put aside. And if the video is playing and you don't stop it before going back you can hear the audio "in background" while using your app.

What can I do to change this behavior? I want to destroy the browser or stop the video..

Thanks
n

**Comment by nevoeiro** [comment]
someone can help with this?
thanks

**Comment by GennadyK** [comment]
I'm using script to go back to the shelf by using single tap and I added document.getElementById("video1").pause();
to pause the video (HTML5 local, youtube will not be available offline) before exiting the book:
<script>
  $(document).ready(function() {
    $("body").swipe( {  // this code to support toggleBars on single tap
      tap:function(event, target) {
        if ($(target).hasClass('baker-prevent-navigation') || $(target).prop('tagName').toLowerCase() == 'area' || $(target).parents('area').length > 0) {
            return;
        }
        document.getElementById("video1").pause();
        window.location.href = 'book://toggleBars';  // toggleBars is case-sensitive!!!
      },
      threshold:5
    });
  });
</script>
