### ISSUE TITLE
newsstandManifestUrl - No internet Connection

### ISSUE THREAD

**Issue by dernoncourt** [bakerframework/baker#512]
Hello,

I have a problem with the connection to the newsstandManifestUrl on iOS9 and Xcode 7.1. I have the message "No Internet Connection". 
I have wifi on my ipad connected. I don't understand, everything work before.

Someone can help me?

Thank you!

**Comment by Entwurfswerk** [comment]
I have the same problem. Xcode console reports a security warning from:

 " 2015-10-05 07:40:26.048 Baker[8831:277565] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file."

but i did not find any paramters for this.
and there must be a nother "official solution" 
is it necessary that the adress must be "https"

i think sice they updated xcode any user has the same problem

thanks Stephan

**Comment by corsa** [comment]
This is the new App Transport Security feature in Xcode 7. All apps that access web content must use an https connection by default.

If you cannot use an https connection, you are supposed to "whitelist" the URL(s) you want to access in your app's Info.plist file.

You can also disable ATS completed (although Apple does not recommend it.) To disable it, add an "NSAppTransportSecurity" item of type Dictionary to your app's Info.plist file, with a dictionary entry of "NSAllowsArbitraryLoads" set to "true".

**Comment by Entwurfswerk** [comment]
did you now if i must change Apps which are already in the app store?

**Comment by corsa** [comment]
Apps that are already in the App Store and were compiled with Xcode 6.x / iOS 8 or older SDK are fine and do not need to be updated. However, once you start using Xcode 7 / iOS 9 SDK to build your app, you will need to deal with this.

**Comment by Entwurfswerk** [comment]
thanks

**Comment by dernoncourt** [comment]
Thanks for your answers!

**Comment by NemoMag** [comment]
@corsa : How do exactly I do that ? Any **screenshot** to show where to type or select stuff please ?
-----> You can also disable ATS completely (although Apple does not recommend it.) To disable it, add an "NSAppTransportSecurity" item of type Dictionary to your app's Info.plist file, with a dictionary entry of "NSAllowsArbitraryLoads" set to "true".----
Many thanx for your help!

**Comment by NemoMag** [comment]
Did it. Here's a small screenshot to make it more visual. 
And a more precise "how to" ;
-> use "+" to create an entry.
-> set it as Dictionary entry. 
-> Type "NSAllowsArbitraryLoads" in its name (left); It becomes automatically "App Transport Security Settings" 
-> use its "+" to add an item (in this dictionary).
-> rename the "item" as "NSAllowsArbitraryLoads".
-> select Boolean as its type of item.
-> choose YES as value for this boolean stuff.
And it works!

But remains insecure. I guess that the perfect thing would be to change the server side of the Baker system to allow these https request....
![capture d ecran 2016-01-30 a 12 25 07](https://cloud.githubusercontent.com/assets/8971320/12695407/62abeed4-c74d-11e5-921b-0b68e5ecf7eb.png)
Cheers, friends!

**Comment by tobiasstrebitzer** [comment]
Thanks @NemoMag i've [added this to the wiki](https://github.com/bakerframework/baker/wiki/Error:-No-internet-Connection)
