### ISSUE TITLE
Error "Failed to launch IBCocoaTouch..."

### ISSUE THREAD

**Issue by eivanphils** [bakerframework/baker#515]
Hi everyone,

I have an issue with my app, when im trying to play the app it shows me the following message:

"Failed to launch IBCocoaTouch ImageCatalogTool via core simulator spawn" 

Days ago the app was running without any problem.

Thanks in advace.

Looking foward to hear from you.

**Comment by kinott** [comment]
I had that issue too.
Just make Product -> Clean and run the app again.
