### ISSUE TITLE
Touch and hold

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#516]
Hi! 
since OS9, touch and hold feature produces specific actionswhen you touch on content of pages .
Sometime a magnifying lens, sometime a small search box
can this feature be disabled? How do we can tweak this in the Xcode baker project ?

**Comment by aspek** [comment]
``CSS-webkit-touch-callout: none;
-webkit-user-select: none;
``

**Comment by NemoMag** [comment]
thx!
