### ISSUE TITLE
"No Internet Connection" when testing 

### ISSUE THREAD

**Issue by douglance** [bakerframework/baker#518]
My app is displaying the error "No Internet Connection" when testing and it does not display my list of issues. 

I am using all https:// urls in the latest version of Baker. 
 
<img width="773" alt="screen shot 2015-11-15 at 6 58 54 am" src="https://cloud.githubusercontent.com/assets/4741454/11168650/605e1026-8b66-11e5-910c-c56475ce7f13.png">

What else could be causing the error?

**Comment by douglance** [comment]
I tried adding this code: 

 <key>NSAppTransportSecurity</key>
      <dict>
  <key>NSExceptionDomains</key>
      <dict>
  <key>yourserver.com</key>
      <dict>
      
      <key>NSIncludesSubdomains</key>
         <true/>
         
       <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
          <true/>
       
        <key>NSTemporaryExceptionMinimumTLSVersion</key>
            <string>TLSv1.1</string>
           </dict>
         </dict>
       </dict>

To solve the issue, but it made no difference.

**Comment by douglance** [comment]
I changed my ManifestURL to

    https://api.xxx.com/issues/:app_id/:user_id

And it works now. I'm confused, but happy.

**Comment by douglance** [comment]
Now when I try to make purchases it is calling an http://api.xxx.com address rather than https:// and throwing an error. It shouldn't matter because I allowed for all subdomains to be accessed on http or https with the above code.

**Comment by feralbob** [comment]
Does the https server meet the requirements for ATS

https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40016240

Try `/usr/bin/nscurl --ats-diagnostics https://api.fictionmagazines.com --verbose`

**Comment by dernoncourt** [comment]
I think your shelf.json was not good.

**Comment by eivanphils** [comment]
I had the same problem with the internet connection which I solved adding the following code to the Baker-Info.plist file

<key>NSAppTransportSecurity</key>
      <dict>
  <key>NSExceptionDomains</key>
      <dict>
  <key>yourserver.com</key>
      <dict>
      
      <key>NSIncludesSubdomains</key>
         <true/>
         
       <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
          <true/>
           </dict>
         </dict>
       </dict>

After that, it shows the latest magazine edition to download but, after its installed it doesn't work and throws a message error. (See the attached file) 

![captura de pantalla 2016-01-05 a las 2 27 50 p m](https://cloud.githubusercontent.com/assets/1909869/12147441/0ffc6d70-b46b-11e5-92b4-ea8ac77a1403.png)

I want you to know that the zip file of the app its not corrupted and Xcode doesn't have any error log.

**Comment by NemoMag** [comment]
Solved on a different thread of this issue section.
I even wrote a how to and give you a screenshot of what & where.
Enjoy! : 
https://github.com/bakerframework/baker/issues/512
