### ISSUE TITLE
Subscription not working

### ISSUE THREAD

**Issue by mghazaly** [bakerframework/baker#519]
Hi,

We are using the latest version of Baker with the Baker Cloud Console (CE). We have published 3 different magazines on iTunes and realised that the Subscription feature is not working. Individual issues can be purchased with no problems, i.e. once I purchase any issue, the icon will change from displaying its price to Download.

However, for subscription after I have successfully subscribed for a year, I am expecting that the latest issue to be marked as Download-able but instead it still displays the normal per issue price.

Anyone experienced this before? How can I fix this?

Thanks.

EDIT: We discovered the issue was due to our own mistake. When publishing in Baker, we backdated the published date to correspond to the physical magazine's publication date. Once we changed the date to the actual publishing date on Baker, the Download button appears.

**Comment by nicholasmartin** [comment]
Nice catch :)
