### ISSUE TITLE
Colors on the magloft version of Baker

### ISSUE THREAD

**Issue by travisday** [bakerframework/baker#520]
@nicholasmartin Hey, you may remember me as @codegeek511, I made a new account. I am working with your version of Baker and for the life of me can't change the colors. I am in the settings.plist but the changes I have made are not showing up. Is there anything else I need to do?

**Comment by nicholasmartin** [comment]
Of course, and you may remember me as @MagLoftMagazines :D Hmm if you have the latest version of ours, then these colors are no longer set in settings but in the storyboard. Have a look in BakerView/ui/BKRStoryboard.storyboard and from there you should be able to edit all the colors. I also made a video some time back that I think covers most of the questions: https://www.youtube.com/watch?v=JZiiqj1_9as

Hope this helps.

**Comment by travisday** [comment]
@nicholasmartin Thanks for the video! I was up and running with Pods but then I got another linker error.

<code>
ld: library not found for -lBolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code>

:( Not sure whats wrong, I did a fresh download from bitbucket, and then a new pod install but I still have this error

**Comment by travisday** [comment]
@nicholasmartin Hey I've been gone for a while (just submitted a tvOS app, woo hoo!) and need to get back into my magazine app. I forked your guys' repo on bit bucket and did a fresh dl and pod install and I am still getting that error I mentioned above. Any ideas? Hope everything is well over at magloft.

**Comment by travisday** [comment]
@nicholasmartin Hahahhaha I decided to watch that video and get going on the layout and saw I had Xcode open while doing it. Its all good. :)

**Comment by nicholasmartin** [comment]
Hi @travisday very happy to hear that you got it running! It's the smallest pitfalls that just break everything, thanks Apple :) We're doing really well thanks and also incredibly busy, which makes it so hard to come here and support. We really want to do more for the open source community, we just need to grow the team with a few more people first :)
