### ISSUE TITLE
Restore purchases not working?

### ISSUE THREAD

**Issue by mghazaly** [bakerframework/baker#523]
I already have a Baker Framework app on the AppStore and it is working perfectly together with Baker Cloud Console CE. This new problem started when I am trying to update the app to Version 2.0 - with some minor updates, including integration of Parse for notifications.

I have just started testing on my own device (i.e. compile from Xcode and run on my iPhone) and noticed that when I click on "Restore purchases", there is a pop-up window that says "Processing....." and this box will stay there forever.

Even though I have an active subscription for the magazine, I am not able to restore all of the issues that I am eligible to. This only happens with the test app that I compile from Xcode and run on my iPhone.

If I delete the test app and re-download the Version 1.0 app from the AppStore, then I have no problems in using "Restore purchases" to get all the issues I deserve.

Anyone else faced this problem before and know how can I overcome it?

Thanks!

**Comment by navu13** [comment]
hi,

did you solve this problem, I have the same issue

**Comment by mghazaly** [comment]
no, unfortunately it is still unresolved and we still haven't updated our Version 1.0 app :-(

please let me know if you manage to fix this later!

**Comment by navu13** [comment]
hi, partly,

Apple rules for newsstand explains that you need subscription. I added free subscription (issues remains payable) and add to Xcode project > Baker > settings.plist > freeSubscriptionProductId. Then it should work. Dirty solution (( but Apple passed app

**Comment by tobiasstrebitzer** [comment]
Please reopen if this is still an issue
