### ISSUE TITLE
Baker for entreprise

### ISSUE THREAD

**Issue by dernoncourt** [bakerframework/baker#524]
Hello community,
I am sorry for my English, i am french.
I use Baker for making presentation content for B2B. We carry documents to presentations on living. We provide catalogs for businessman on a server. We install the application via an "Apple develop enterprise" account.
For the content we realize it with Adobe Muse and Edge Animate then through a back office we can publish content and update it.
On iOS it works fine on Android by cons it is not working fine. I am not a developper, can you tell me if your Framework will be updated and if the Android version will be debugged.
Thank you for your answers and if you have questions about our method of use please do not hesitate to ask us.
Best regard

**Comment by tobiasstrebitzer** [comment]
Hi @dernoncourt,

**Here's the short answer:**
Baker Android is not actively maintained, but the app itself is functional. The problematic part is rendering the issues (the HPUB viewer). Newer Android devices (KitKat +) will probably work correctly, while older devices will most likely not render correctly.

**Here's the long answer:**
Sadly there's some severe challenges we're facing with Android WebViews. Up until Version 4.4 (KitKat), Android was using an older browser that doesn't support new features of HTML5 and CSS3. Many features like animation and correct positioning are broken, and until today there is no reliable way to fix this. If you publish an app using Baker Android, users with older devices will probably report errors.
The only good news is that users are (slowly) migrating to newer Android Versions. It is very likely that within the next 6 or 12 months, the majority of android users will be running on 4.4+ (the supported android version).

If you haven't, check out [baker-android-refactor](https://github.com/bakerframework/baker-android-refactor). This is an updated version of baker-android that tackles the rendering issues of older devices.

**Comment by tobiasstrebitzer** [comment]
Please re-open if this is still an issue.
