### ISSUE TITLE
Double tap to show navigation menu broken for iPhone 6s Plus

### ISSUE THREAD

**Issue by danluong** [bakerframework/baker#525]
I've tried building the Baker framework using the demo A Study in Scarlet book on the simulator and my iPhone 6s Plus, and double tap to open the navigation does not work on the actual device. Oddly enough, it does work in the simulator. When I tried an iPad, both the simulator and the device would show the menu.

**Comment by uncledent** [comment]
Yes, this is broken for our magazines too. Any idea, someone?

**Comment by tobiasstrebitzer** [comment]
The new iOS 10 Beta release broke the index completely, which - ironically - led us to a solution for the iPhone 6S as well.

Related Issue: #540

**Comment by tobiasstrebitzer** [comment]
Fixed in #541, and merge into master.
