### ISSUE TITLE
Migrating from InDesign to Baker Framework

### ISSUE THREAD

**Issue by everton-schumacker-clansoft** [bakerframework/baker#527]
Hi!

First of all, I would like to thank anyone that took the time to read this post, specially those that took the time to help me with any possible answer!

I am from Brazil and new in the publishing business. I am facing a very complicated situation in my internship and I couldn't find any good solution to efficiently solve it. I already researched extensively all forums about InDesign, but none of the answers seem to be viable to me.

We published an interactive eBook using InDesign 2014 and Adobe's DPS system, but Adobe changed its licensing policies in 2015, which made impossible to small companies to update and release new apps . The problem is that we would like to divide this whole book into 5 more apps, because it is a complete and extensive book (so we would like to make smaller apps, each one of them covering one chapter of the book). The thing is: we don't want to redo all the content in HTML5, so we are looking for a way of converting InDesign folio into hPub efficiently. In5 does a really good work in this case, but the problem is that it apparently can only convert a single INDD file. Since we have a huge amount of files is this book, it would be very difficult to merge everything into a single file.

I would like to know if any of you guys could please take the time to answer any of this questions, since any of then would solve my situation:

Is there any other INDD to HTML5 converter that can converte the whole folio?
Is there any way to converte the whole folio into hpub using in5? If not, is there any tool that automatically merges the whole folio into a single .indd file to be used with in5?
Is there any way of merging multiple hPubs into a single hPub?
Is there any way to build a single app that joins multiple HPUBs into a single interactive eBook?
Again, thank you very much for your attention, help and support!

PS: Sorry for my bad English. As I said, I'm from Brazil and it have been a long time since I wrote a message as long as this one. lol

**Comment by pieterclaerhout** [comment]
Hi,

it might be better to look at a solution like Twixl Publisher. You can find more information about it on http://twixlmedia.com. If you need more information, feel free to contact me on pieter@twixlmedia.com.

Kind regards,

pieter

**Comment by everton-schumacker-clansoft** [comment]
Thanks, Pieter.

Unfortunately, I already have contacted Twixl, but the pricing (at least here in Brazil) is way beyond I can afford for this project right now. =/

**Comment by nicholasmartin** [comment]
Hi @everton-schumacker-clansoft,

Sorry to hear you guys also got hit by Adobe's license change. We have had quite a few clients switch from DPS to MagLoft because of that. I understand your challenge, and I will ask @tobiasstrebitzer to have a look to see if there is any way to help with the conversion. It may require that we have a look at your InDesign project, would that be a problem?

Perhaps you can give a brief overview of how your project is constructed? It sounds like you have an indd file for every page on your books?

**Comment by everton-schumacker-clansoft** [comment]
Hi, Nicholas.

Thanks for your support. It is not a problem at all, he can have a look in our project. It is not an indd file per page, but it is divided by sections. For each chapter we have an indd for the cover, one for index, then we have one file for each section of the chapter, and finally one indd for each training(exercises). 

Does you or Tobias have any e-mail for contact?

Thank you very much.

**Comment by nicholasmartin** [comment]
You can email Tobias at tobias.strebitzer@magloft.com

**Comment by tobiasstrebitzer** [comment]
Hi Everton,

I think I have an idea how this could work. As i understand, you will need separate HPUB documents for each chapter of your book. Each of these 5 HPUB documents will be packed in its own app.

1. You will first need to generate one combined PDF for each of your chapters, so you end up with e.g. chapter-01.pdf, chapter-02.pdf, chapter-03.pdf, etc... You can use tools like Adobe Acrobat to combine PDF documents of one chapter.
2. Convert each PDF document to HPUB format. There's not many tools for this out there, but you can use MagLoft.com for this. Create a free account on magloft.com and log into the Portal (www.magloft.com/portal)
3. In the "Create Content" area, upload all PDF files so they show up in the issue list.
4. Next, click "Pack" and afterwards "Download" to get all HPUB files.

Additional thoughts:
* An alternative approach could be to offer a single app (priced free), that offers the 5 chapters of your book as individual downloads (in-app purchases). This way you'll only need to market one app, and should have benefits in app store listing once you get some good reviews in. For this option you will need a backend service to host your issues:
  * [Baker Cloud - Free/Selfhosted](http://www.bakerframework.com/bakercloudce/)
  * [MagLoft - Paid](http://www.magloft.com/)
  * [twixlmedia.com - Paid](http://www.twixlmedia.com)
* Just to avoid any confusion: Even though your PDF is converted to HTML, it doesn't mean that you'll get any interactive or responsive behaviour, at least not automatically. If you do want to achieve this, have a look at [Ajar Productions' in5](http://ajarproductions.com/pages/products/in5/)

Kind Regards,

Toby

**Comment by lucasbols** [comment]
Hi there!

As far as I understand, In5 creates an html file for each page on your indesign file, plus an index.html file, and a book.json listing all the "pages".

The pages are exported as numbered html files (0001.html, 0002.html and so on)

If you need to merge different hpubs into one, you can put all your html files into one folder, rename the files to make them correlative, and create one book.json with all the pages on it. You will need to manually create the index, but the rest of the process should be pretty straightforward...

You can also contact Justin at Ajar Productions to see if they can help you with your In5 settings: support@ajarproductions.com

Cheers!

**Comment by everton-schumacker-clansoft** [comment]
Thank you very much!

I was able to build the book, but I’m still getting some minor bugs. I will email Justin.

Thank you very much for your support!

Cheers!

**Comment by zetaequis** [comment]
MagLoft and twixlmedia.com are worse than Mag+, the best digital publising company (but expensive). Only Baker Framework is for free. You can build a html5 project with dreamweaver (or other) or convert inDeisgn document with in5 plugin after paying 299$/year.

**Comment by tobiasstrebitzer** [comment]
Closing this issue as the original request was resolved using Ajar Productions In5.
