### ISSUE TITLE
Page name display removing ?

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#530]
Hi!
I just can find how to remove the html page name to appear while a page is loading.
Page names are not very user friendly (name_1.html or so), and when pages take long to load, this makes the whole thing look "unfinished" (unpolished if I may ?) 

so how and where can I remove the fact that baker displays the html page's name while loading a page.

**Comment by GennadyK** [comment]
You may just change the title tags inside your html files, as this is the place from where Baker takes page names, e.g.
`<!DOCTYPE html>`
`<html>`
`<head>`
`  <title>Page Name or just empty</title>`

**Comment by GennadyK** [comment]
To remove page names from the app:
1. In /BakerView/ui/BKRPageTitleLabel.m find this line:

`            NSString *titleText = [[fileContent substringWithRange:matchRange] gtm_stringByUnescapingFromHTML];`

and replace it with this one:

`            NSString *titleText = @"";`
