### ISSUE TITLE
No Internet Connection error with ios 9.3 / xcode 7.3

### ISSUE THREAD

**Issue by bsjosten** [bakerframework/baker#532]
Hi,

After upgrading to ios 9.3 and xcode 7.3 I get a "No Internet Connection" error when trying to run my Baker 4.3 Standalone application on my devices. This happens on both the iPad and iPhone.

No changes have been made to the project, it used to run just fine before the upgrades.

The newsstand project previously uploaded to the App Store (also based on Baker 4.3) runs just fine on both devices.

Hard to develop new issues with being able to run in standalone mode. Any ideas on what has changed?

Thanks,

/Bo

**Comment by ajurcevic** [comment]
This be cause of Apple's App Transport Security.

Here is a quick link to bypass it by adding a value to the info.plist:
http://iosdevtips.co/post/121756573323/ios-9-xcode-7-http-connect-server-error

I would recommend getting security setup on your connections/server i.e. HTTPS.
