### ISSUE TITLE
Baker | BakerShelf/Constants.h

### ISSUE THREAD

**Issue by AndrewAZ** [bakerframework/baker#533]
I'm trying to create a new app and the constants.h file is gone.  

In another support request, someone said to edit the  BKRSettings.h file (which I copy and pasted below)

In the old constants.h file, I could just enter my ai aniformation. Do I put this same line of code to define it below? Or do I edit something differently?
        #define NEWSSTAND_MANIFEST_URL @"http://api.mydomain.com/issues/:app_id/:user_id"

If somebody could provide an example of waht to put here, that would help a lot.

// ----------------------------------------------------------------------------------------------------
// Mandatory - This constant defines where the JSON file containing all the publications is located.
// For more information on this file, see: https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON
// E.g. @"http://example.com/shelf.json"
@property (nonatomic, readonly) NSString *newsstandManifestUrl;

@property (nonatomic, readonly) BOOL newsstandLatestIssueCover;

// ----------------------------------------------------------------------------------------------------
// Optional - This constant specifies the URL to ping back when a user purchases an issue or a subscription.
// For more information, see: https://github.com/Simbul/baker/wiki/Baker-Server-API
// E.g. @"http://example.com/purchased"
@property (nonatomic, readonly) NSString *purchaseConfirmationUrl;

// ----------------------------------------------------------------------------------------------------
// Optional - This constant specifies a URL that will be used to retrieve the list of purchased issues.
// For more information, see: https://github.com/Simbul/baker/wiki/Baker-Server-API
// E.g. @"http://example.com/purchases"
@property (nonatomic, readonly) NSString *purchasesUrl;

**Comment by nicholasmartin** [comment]
Hi @AndrewAZ did you get it up and running? Yes you need to edit the Settings.plist and it's much easier to do that in Xcode.

**Comment by tobiasstrebitzer** [comment]
Closing for now, @AndrewAZ please reopen if the problem persists.
