### ISSUE TITLE
Update Parse to Self Hosted Parse with Heroku - MongoDB

### ISSUE THREAD

**Issue by proteuscanvas** [bakerframework/baker#535]
Hi,

I have used Baker to build an iOS app and now that Parse have announced that they are closing down their hosted service I have been forced to migrate to my own self hosted Parse app on Heroku/MongoDB. Now I am trying to update my code in my ios app. I have replaced the following:
setApplicationId:NEW-ID
clientKey:NEW-KEY
But I also need to add in the **server** http://myapp.herokuapp.com/parse 

Where do I add the server details?

Thank you.

**Comment by ahvink** [comment]
In the Appdelegate.swift:

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Enable storing and querying data from Local Datastore.
        // Remove this line if you don't want to use Local Datastore features or want to use cachePolicy.
        Parse.enableLocalDatastore()
        
        let parseConfiguration = ParseClientConfiguration(block: { (ParseMutableClientConfiguration) -> Void in
            ParseMutableClientConfiguration.applicationId = "myAppId"
            ParseMutableClientConfiguration.clientKey = "myMasterKey"
            ParseMutableClientConfiguration.server = "https://anotherdarntest.herokuapp.com/parse"
        })
        
        Parse.initializeWithConfiguration(parseConfiguration)

Fort a full example project check out:

http://www.robpercival.co.uk/wp-content/uploads/2016/02/ParseServerStarterProject.zip

**Comment by proteuscanvas** [comment]
Thank you Ahvink I should have explained that my application is written in Objective C.
I can in the appDelegate I have this code
`[Parse setApplicationId:@"myAppId"
                  clientKey:@"myMasterKey"
     ];
`
I tried to add the following code 
`    // server:@"https://anotherdarntest.herokuapp.com/parse"`

And in the framework edited the Parse.h file 
`
+ (void)setApplicationId:(NSString *)applicationId clientKey:(NSString *)clientKey  server:(NSString *)server;

/*!
 @abstract The current application id that was used to configure Parse framework.
 */
+ (NSString *)getApplicationId;

/*!
 @abstract The current client key that was used to configure Parse framework.
 */
+ (NSString *)getClientKey;

+ (NSString *)getServer;
`
There are no errors in the code but when I build the project I get the following error in the log:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[Parse setApplicationId:clientKey:server:]: unrecognized selector sent to class 0x1f4234'

Thank you for your help.
Joe

**Comment by ahvink** [comment]
This should provide some answers:

https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#using-parse-sdks-with-parse-server

**Comment by tobiasstrebitzer** [comment]
Closing this issue for now. Please re-open if Parse Integration didn't work out @proteuscanvas
