### ISSUE TITLE
Issues won't show up on shelf

### ISSUE THREAD

**Issue by travisday** [bakerframework/baker#536]
@nicholasmartin Hey dude! So I have set up most things and the app is running (almost flawlessly) The only thing is the issues are not showing up on the shelf. It is not working with a static json file or my magrocket backend. Not sure what would make this happen. Also I plan to update to the Baker Cloud Console this will still be supported correct?

**Comment by travisday** [comment]
@nicholasmartin have you had a chance to see this?

**Comment by travisday** [comment]
@nicholasmartin anyone home? hahahaha I bet your super busy I just can't seem to get these issue to show up!

**Comment by nicholasmartin** [comment]
Hi @travisday so sorry for the delayed response. Yeah we are definitely kept busy by building MagLoft.

Can you tell me which branch you have setup your app with? Is the the Baker-MagLoft version? Can you see anything in the log in Xcode when you launch the app? It could give you some hints as to what's wrong. Can you also share your manifest URL that you are using?

**Comment by travisday** [comment]
@nicholasmartin No worries dude! We are using the magloft baker version [https://bitbucket.org/magloft/magazine-application-distribution](here) 

Here is the log, could it maybe be that my provisioning profiles aren't set up correctly yet? I have tried my test .json file here http://living-health.net/TEST_LIVING_HELATH_ISSUES/shelf.json
I have also tried my magrocket url here http://living-health.net/api/issues/:app_id/:user_id

`2016-06-02 15:40:50.645 Baker[76029:13332550] Settings: {
    autoRenewableSubscriptionProductIds =     (
        "net.livinghealth.sub.autorenewable"
    );
    enableFacebookSDK = 0;
    enableLaunchVideo = 0;
    freeSubscriptionProductId = "";
    freeTrialSubscriptionProductId = "";
    googleAnalyticsID = "";
    isNewsstand = 0;
    issuesActionBackgroundColor = "#474747";
    issuesActionButtonColor = "#ffffff";
    issuesActionFont = "Helvetica-Bold";
    issuesActionFontSize = 11;
    issuesArchiveBackgroundColor = "#bc242a";
    issuesArchiveButtonColor = "#ffffff";
    issuesArchiveFont = "Helvetica-Bold";
    issuesArchiveFontSize = 11;
    issuesCoverBackgroundColor = "#ffffff";
    issuesInfoColor = "#929292";
    issuesInfoFont = Helvetica;
    issuesInfoFontSize = 15;
    issuesLoadingLabelColor = "#bc242a";
    issuesLoadingSpinnerColor = "#929292";
    issuesPriceColor = "#bc242a";
    issuesProgressbarTintColor = "#bc242a";
    issuesShelfOptions =     {
        backgroundFillColor = "#f3f3f3";
        backgroundFillGradientStart = "#f3f3f3";
        backgroundFillGradientStop = "#f3f3f3";
        backgroundFillStyle = "";
        headerBackgroundColor = transparent;
        headerHeightPadLandscape = 215;
        headerHeightPadPortrait = 215;
        headerHeightPhoneLandscape = 107;
        headerHeightPhonePortrait = 107;
        headerImageFill = 0;
        headerSticky = 0;
        headerStretch = 1;
    };
    issuesTitleColor = "#000000";
    issuesTitleFont = Helvetica;
    issuesTitleFontSize = 15;
    magazineTitleColor = "#000000";
    magloftAccessToken = "";
    modalViewBackgroundColor = "#929292";
    modalViewBarTextColor = "#ffffff";
    newsstandLatestIssueCover = 1;
    newsstandManifestUrl = "http://living-health.net/TEST_LIVING_HELATH_ISSUES/shelf.json";
    parseApplicationID = 5tI7ux3xEZRJ3ale04FP4cXLtkf2u0xwjtICIrpH;
    parseClientKey = myPVJCxJlVFL097P774SkZwshazUEUPJPZouMG4C;
    postApnsTokenUrl = "";
    purchaseConfirmationUrl = "";
    purchasesUrl = "";
    ratingOptions =     {
        daysUntilPrompt = 3;
        enabled = 1;
        previewMode = 0;
        usesUntilPrompt = 5;
    };
    requestTimeout = 15;
    showPageIndex = 1;
    showSocialShareButton = 1;
    useiTunesConnectLocalizations = 0;
}
2016-06-02 15:40:50.654 Baker[76029:13332550] iRate verbose logging enabled.
2016-06-02 15:40:50.771 Baker[76029:13332550] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///Users/Travis/Library/Developer/CoreSimulator/Devices/4D5B71CE-BF93-4791-B827-2F47F32565B3/data/Containers/Data/Application/35D74591-F0B4-4431-A98E-5661996EDD0E/Library/Cookies/net.livrepress.livinghealth.binarycookies
2016-06-02 15:40:50.825 Baker[76029:13332655] iRate is checking http://itunes.apple.com/US/lookup?bundleId=net.livrepress.livinghealth to retrieve the App Store details...
2016-06-02 15:40:50.827 Baker[76029:13332550] iRate did not prompt for rating because the app has only been used 3 times and only 0 events have been logged
2016-06-02 15:40:50.842 Baker[76029:13332655] iRate found the app on iTunes. The App Store ID is 703986459`

**Comment by travisday** [comment]
@nicholasmartin any luck?

**Comment by nicholasmartin** [comment]
Hi @travisday sorry man, been very busy! There could be several reasons for this not to be working. I know we have updated a LOT of things with new features etc, and it could also be there are new requirements for the manifest json file. I'm tagging @tobiasstrebitzer here as he might be able to point you in the right direction. Also our open source version you have is quite outdated so it could be a problem there as well.

Have you considered just using MagLoft instead of fighting with the code? 💃 I know it's a bit of a plug, but our open source app is just so far behind at the moment. We're also happy to give you a good discount since you're coming from Baker.

Either way, let's see what Tobias comes up with :)

**Comment by travisday** [comment]
@nicholasmartin @tobiasstrebitzer Hey guys! Ya I am not sure we'd be ready to go into magloft financially. The open source app was great for what we needed but the issues not showing up is a pretty big problem in development hahahaha.

**Comment by MrKistic** [comment]
So you've built a commercial product based on the open source Baker framework, and while being maintainers on the open source framework you're too busy to update it because you're working on your private commercial version of it? And now you're suggesting we should just use your commercial version instead? Yep, that's the open source spirit.

I guess we may as well just call this project dead and all move on.

**Comment by nicholasmartin** [comment]
Hi @MrKistic I can see how this may look to the outside. We really wish we could invest more time into the open source version and it's something we speak about often in the team. Without a shadow of doubt we will be contributing more to Baker again as soon as we can.

We will also be offering a freemium version of our product and at that time I would love to do something extra special for the Baker community. Hopefully soon we can share more information about this.

**Comment by tobiasstrebitzer** [comment]
@MrKistic we'll be releasing an update to the Open Source version of Baker/MagLoft soon. Yes, we do have a commercial version, but we have no intention to push open-source users towards our commercial product.

@travisday i've had a closed look at your manifest, and the only difference i can see is the missing categories key. Not sure if this causes the problem, but try this:
```json
[
    {
        "name": "201510_October",
        "title": "October 2015",
        "categories": [], <--_ADD_THIS_LINE
        "info": "This is a test for the iPhone phone This is a test for the iPhone phone This is a test for the iPhone phone",
        "date": "2014-01-01 10:10:10",
        "cover": "http://living-health.net/TEST_LIVING_HELATH_ISSUES/thm-image-000.jpg",
        "url": "http://living-health.net/TEST_LIVING_HELATH_ISSUES/Test_Issue.hpub"
    }
]
```

I hope this helps

**Comment by tobiasstrebitzer** [comment]
Please also check [Wiki - Error: No Internet Connection](https://github.com/bakerframework/baker/wiki/Error:-No-internet-Connection)
