### ISSUE TITLE
Baker Cloud gives issues on PHP 7.0.7

### ISSUE THREAD

**Issue by ahvink** [bakerframework/baker#537]
Baker Cloud CE has issues with PHP 7.0.7.
<img width="548" alt="screenshot" src="https://cloud.githubusercontent.com/assets/697422/16040525/4a53302e-3230-11e6-8a42-14995893dea2.png">

**Comment by tobiasstrebitzer** [comment]
Hi @ahvink,

please create an issue for this in [bakercloud-ce-console/issues](https://github.com/bakerframework/bakercloud-ce-console/issues), as this issue tracker is only adressing the iOS App.

**Comment by drhounsell** [comment]
ahvink, did you solve this problem?

**Comment by ahvink** [comment]
No, I haven't.
But sofar it hasn't impacted the functionality.

**Comment by drhounsell** [comment]
I received this error when the server was upgraded to PHP 5.6 and now nothing can be downloaded.

**Comment by ahvink** [comment]
Probably because I only get the Notice, somehow I don't get the warning.

Alfred
