### ISSUE TITLE
Looking for Data Collection

### ISSUE THREAD

**Issue by melanieanntarr** [bakerframework/baker#538]
Dear Baker Community,  

Is anyone collecting data in any of the newsstand apps developed.  I'm wanting to have a go at this functionality but cannot find anything on the forum that addresses "data collection".

Is it under another name.  Or do you just go ahead and use a standard css form in the framework?

Thanks in advance
Mel

**Comment by tobiasstrebitzer** [comment]
Hi Melanie,

are you referring to collecting feedback and surveys from your users? We have had great success with this by simply adding a standard HTML form inside the HPUB pages. You could also easily embed your custom form as an iFrame using tools like [surveymonkey](www.surveymonkey.com).

The only limitation with an HTML-based solution (compared to a native integration) is that it's not available offline.

**Comment by melanieanntarr** [comment]
Hi Tobias,
Thank you so much.  What other information is available to me, could I time the amount of time it takes to read each page?
Melanie

**Comment by tobiasstrebitzer** [comment]
Hi Melanie,

It is not currently in the Baker App, but there's a way to do this. It requires two things:
1. Some code needs to be modified within the App. I can point you in the right direction if you're coding yourself or if you have someone who does.
2. You need a suitable Backend to view the Reports. In our initial ambitions to do this, we hit a limit on how well Google Analytics can do this (there might be a way but it's complicated). We have then decided to use [Mixpanel](http://www.mixpanel.com), which works extremely well for this, and it's free (if you have less than a couple thousands of readers per day).

**If you're not in a rush:** We're updating the Open Source MagLoft Version of the Baker App soon, and we'll have Mixpanel Integration available in there.

Here's a screenshot of such a report:
![screen shot 2016-08-10 at 18 29 38](https://cloud.githubusercontent.com/assets/222509/17550668/a78b3c30-5f28-11e6-981c-f6f7cf31f348.png)

Or as Table View (Average time spent per page, exportable to Excel):
![screen shot 2016-08-10 at 18 30 27](https://cloud.githubusercontent.com/assets/222509/17550677/b6b79712-5f28-11e6-9cc1-7405303d895b.png)

And these are the settings in Mixpanel to create this report:
![screen shot 2016-08-10 at 18 29 31](https://cloud.githubusercontent.com/assets/222509/17550687/c1aa9796-5f28-11e6-8a17-956915272719.png)

Feel free to get back to me if you need more information or assistance.

**Comment by melanieanntarr** [comment]
Hi Tobias,

Thank you - this is comprehensive.  From what I gather there are not many
people analysing interactive magazine data.  I will look at Mixpanel and
get back to you.

Thanks again for your generosity.

Melanie

On Wed, Aug 10, 2016 at 6:34 PM, Tobias Strebitzer <notifications@github.com
