### ISSUE TITLE
Table of Contents and iOS 10 beta 3

### ISSUE THREAD

**Issue by corsa** [bakerframework/baker#540]
We have several Baker apps, and I've noticed in testing them on iOS 10 beta 3 that the Table of Contents no longer comes up when double-tapping the screen. The top nav still appears on double-tap though.

This is using the non-MagLoft version of Baker...does the MagLoft open source version have this problem also under iOS 10 beta 3? Does anyone have any tips for fixing this? Obviously iOS 10 release is still a couple of months away, but we'd like to be ready for it.

**Comment by corsa** [comment]
Update: I tried out the Magloft open source version and it has the same problem under iOS 10 beta 3.  Anybody else having this problem, and/or have a solution?

**Comment by corsa** [comment]
The problem still exists with iOS 10 beta 4. I have tracked it down to the following bit of code in BKRIndexViewController.m, it seems the Javascript method to determine the size of the index web view always returns 0 in iOS 10:

`- (CGSize)sizeFromContentOf:(UIWebView*)webView {
    /*
    // Setting the frame to 1x1 is required to get meaningful results from sizeThatFits when
    // the orientation of the is anything but Portrait.
    // See: http://stackoverflow.com/questions/3936041/how-to-determine-the-content-size-of-a-uiwebview/3937599#3937599
    CGRect frame = view.frame;
    frame.size.width  = 1;
    frame.size.height = 1;
    view.frame = frame;
    return [view sizeThatFits:CGSizeZero];
     */
    
    CGFloat contentWidth  = [[webView stringByEvaluatingJavaScriptFromString:@"document.width"] floatValue];
    CGFloat contentHeight = [[webView stringByEvaluatingJavaScriptFromString:@"document.height"] floatValue];
    return CGSizeMake(contentWidth, contentHeight);
}
`

**Comment by corsa** [comment]
Okay, I was able to fix it. Replace the above code with the following:

```
- (CGSize)sizeFromContentOf:(UIWebView*)webView {
    
    CGRect frame = webView.frame;
    frame.size.width = 1;
    frame.size.height = 1;
    webView.frame = frame;
    CGSize fittingSize = [webView sizeThatFits:CGSizeZero];
    return CGSizeMake(fittingSize.width, fittingSize.height);
}
```

**Comment by tobiasstrebitzer** [comment]
Hi @corsa, thanks for this! It works fine on all devices except iPhone 6S and iPhone 6S Plus.

I know @febbyrg is working on a solution for the 6S, should be ready soon.

**Comment by febbyRG** [comment]
Hi @corsa, I've solution for Index View not showing on iOS 10 Beta & iPhone 6s.
#541

**Comment by corsa** [comment]
Great, thanks guys!

**Comment by tobiasstrebitzer** [comment]
Closing for now, please re-open if problems with issue bar or double-tap persist.
