### ISSUE TITLE
Call top navigation bar on single tap

### ISSUE THREAD

**Issue by GennadyK** [bakerframework/baker#544]
Hi all,
We are moving from Adobe DPS Classic platform and would like to keep Baker app interface maximally close to Adobe's Viewer app. We need, please, help with 2 things for now:

1. Ability to switch double tap to single - I think I saw a few places in the code with number of taps =2, but not sure exactly what should be changed. Also quite some people were asking the same. Maybe this functionality could be moved into Book.json Baker extension parameters:
https://github.com/bakerframework/baker/wiki/Book.json-baker-extension-parameters
Something like this:
Behaviour properties:
-baker-navbar-taps: ( number, 1 or 2, default: 2 ) - since 4.4: Defines the number of taps to call top navigation and index bars.

**UPDATE to 1:** this needs to be replaced in 2 places inside the BKRBookViewController.m. Sorry for not trying it first:
touch.tapCount == 2   ->   touch.tapCount == 1
But now I got another connected problem: 1 tap does both - activates the HTML element on the screen and at the same time calls navigation bar. How I can, please, change it, so navigation bar appears only if tapped on the area without active elements underneath? This is how it works in Adobe's Viewer app.
After testing everything, I see that it's not that easy to switch to 1 tap. It definitely requires more changes. :( 

2. We also have at least one book, that we use app custom URL link inside to exit to the shelf, as that book wasn't developed by us and is capturing all the touch controls on the screen, making tap to navigation bar not working. In this post there are 3 app links added to call navigation bar:
https://github.com/bakerframework/baker/issues/403
So we would like to add the 4th one:
"baker-toc://shelf"
Although those special app links are not working for some reason - I’m not getting that NSLog line in debugger,
could, please, someone help with what and how that exitToShelf function should be called inside the code below and how to fix the code so those custom URLs will start work again:

                else if ([[url scheme] isEqualToString:@"baker-toc://shelf"])
                {
                    NSLog(@"[BakerView] - exitToShelf"); // call exitToShelf function
                    return NO;
                }

UPDATE to 2:
As baker-toc:// links were not working, I just changed code for the book:// link inside the BKRBookViewController.m to handle 2 special links:
book://toggleBars
book://shelf

                else if ([[url scheme] isEqualToString:@"book"])
                {
                    if ([[url absoluteString] isEqualToString:@"book://toggleBars"])
                    {
                        [self toggleBars];
                        return NO;
                    }
                    else {
                        // if "book://shelf" then will exit to shelf and try to download nonexistent book
                        [self toggleBars]; // this to have navBar in Shelf view after exiting
                        [self performSelector:@selector(handleBookProtocol:) withObject:url afterDelay:0.4];
                    }
                }

Thank you so much,
Gennady

**Comment by GennadyK** [comment]
For single tap for now we are using jQuery solution with the book://toggleBars link - see the 2. above. Please note that we are using 'area' element for image maps, you will need to exclude links and buttons that you are using. See also https://github.com/bakerframework/baker/issues/403:
`...`
`<head>`
`...`
`<script src="js/jquery-1.11.2.min.js"></script>`
`<script src="js/jquery.touchSwipe.min.js"></script> <!-- to support toggleBars on single tap; plugin to use:  https://github.com/mattbryson/TouchSwipe-Jquery-Plugin -->`
`...`
`</head>`
`<body>`
`...`
`<script>`
`  $(document).ready(function() {`
`    $("body").swipe( {  // this code to support toggleBars on single tap`
`      tap:function(event, target) {`
`        if ($(target).hasClass('baker-prevent-navigation') || $(target).prop('tagName').toLowerCase() == 'area' || $(target).parents('area').length > 0) {`
`            return;`
`        }`
`        window.location.href = 'book://toggleBars';  // toggleBars is case-sensitive!!!`
`      },`
`      threshold:5`
`    });`
`  });`
`</script>`
`</body>`
`</html>`

**Comment by iusondemand** [comment]
I ask to reopen the issue to discuss with you a solution working for me on ipad4mini 10.x

In BKRviewbookcontroller.m lines there is:

    if (shouldPropagateInterceptedTouch) {
        if (userIsScrolling) {
            [self userDidScroll:touch];
            NSLog(@"[BakerView] scrollxx Tap:  ");
        } else if (touch.phase == UITouchPhaseEnded) {
            [self userDidTap:touch];
            NSLog(@"[BakerView] noscrollxx Tap:  ");
        }
    } 


I've added

    if (shouldPropagateInterceptedTouch) {
        if (userIsScrolling) {
            [self userDidScroll:touch];
            NSLog(@"[BakerView] scrollxx Tap:  ");
        } else if (touch.phase == UITouchPhaseEnded) {
            [self userDidTap:touch];
            [self toggleBars];
            NSLog(@"[BakerView] noscrollxx Tap:  ");
        }
    } 

To me seems to work fine. Navigation bar appears only when I not swipe or scroll.

**Comment by GennadyK** [comment]
Hi Valentino,
If you can also click on the links/buttons/image map links within the pages without the navigation bar popping out, then it is a good alternative solution.

Regards,
Gennady

**Comment by iusondemand** [comment]
Hi @gennadyk.
Yes, I agree, but I was looking for a user interaction more friendly, like a click also  in blank spaces or on text.

**Comment by GennadyK** [comment]
Hi Valentino,
Sorry, it's not so clear as to what you agree with and also "I was looking for a user interaction more friendly" compare to what?
In any case if your solution works for you then you should use it.

**Comment by iusondemand** [comment]
Sorry if I reply so late.
I try to explain better, in my bad english, what is a "user interaction more friendly".
If I'm reading a page i can swipe left or right and scroll up and down. It's very friendly.
Now i want more. I can double tap in every part of the screen, and the navigation bar will appear.
This is almost familiar for many users, but not all. New interfaces of other apps simple need one fast tap, eventually allowing more features with a long single tap.
I was looking for a simple way to open the navigation bar with a single tap also on text, on the center of the display. What I've found does it.
It could be upgraded supporting long taps, to open menus or share options, but I'm not a c++ developer even if I can read it.
Thank you @GennadyK

**Comment by GennadyK** [comment]
Hi Valentino,
Yes, the solution with jQuery, described above, allow us to call navigation bar with the single tap anywhere on the screen, but active (clickable) HTML elements. And it is sufficient for us, so we are not planning to change anything or add any long single taps.

Thanks,
Gennady

**Comment by iusondemand** [comment]
I agree with you, it is sufficient and can be activated or not, instead mine is always on (that is ok for me).

If you think useful you could add in the source code but commented, so people can activate it only if desidered. Perhaps a link to this issuee with the 2 solutions could help, just an idea.

Thank you. For me, you can close the issue.

**Comment by GennadyK** [comment]
Hi Valentino,
I'm relativly new to GitHub and my understanding is that you need to search issues and pull requests for the features/questions. You may also edit docs under the Wiki tab by yourself. If you have a good place in mind where to add link to this issue please point me to it and I'll do it.

Regards,
Gennady
