### ISSUE TITLE
Index not working anymore

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#545]
Hi friends,
Working on a News Baker-bases project, I updated to the last version of Xcode. But now on every baker project (lastest version 4.3), The double tap does not Bring the index anymore.  :-(
The bar with link to the shelf still appears, but no index on sight.

Hoh to bring it back ?

**Comment by GennadyK** [comment]
Hi,
The easiest and most proper way would be to restore your previous version
and then investigate (compare two codes). Also latest baker-master has
index working for me.

Thanks and good luck,
G.

**Comment by GennadyK** [comment]
Just wonder if you did this:
https://github.com/bakerframework/baker/pull/541/files

**Comment by NemoMag** [comment]
Working perfectly with this edit. Thanx a lot, Tobias.
