### ISSUE TITLE
Book Update Feature (New)

### ISSUE THREAD

**Issue by GennadyK** [bakerframework/baker#546]
Hi guys,
Can't find anything about handling book updates. Can't see anything to support this in specification for shelf.json (as date is used for ordering books on the shelf). Adobe viewer changes title of the book to the "Update Available" and offers update every time you tap on the cover. Does anyone have it implemented?
As for the optional "updated" field we can use the same format as for the date, e.g. "2016-11-14 11:11:11".
And there is also the way to use notifications and ask user archive and re-download specific book manually. 

Thanks,
Gennady

**Comment by corsa** [comment]
This seems like such an essential feature, really would love to see this implemented.

**Comment by GennadyK** [comment]
Book Update Feature

What it does: it checks if "book_updated" field in shelf.json changed (or added) and adds "Update" button for that book in the shelf view. It is advisable to add "book_updated" field right after the "date" field,e.g.:
    "date": "2017-01-11 13:01:25",
    "book_updated": "2017-01-23 12:12:11",

Here is how it's implemented:
1. When book is downloaded to the iOS device, "book_updated" is saved to the local "bookUpdated.property" file inside the book's storage folder.
2. Every time book status is checked and if it == "downloaded", "book_updated" for that book is read from the "bookUpdated.property" file into downloadedBookUpdated to be compared with the bookUpdated from the shelf.json.
3. Every time shelf view is refreshed for downloaded books bookUpdated is compared to downloadedBookUpdated and if different then this reveals the "Update" button.
Please note: adding "book_updated" field to the book is treated as an update (from nil to the new value).
4. ”Update" button is assigned in the storyboard to the updateButtonPressed function, that removes old and re-downloads updated book.

And here are the corresponding changes to the code (text file with the code for copy/pasting is attached):
[Book Update Feature.txt](https://github.com/bakerframework/baker/files/752416/Book.Update.Feature.txt)


1. Find these line in the BKRIssue.m:
            if (unzipSuccessful) {

and add this code right after it:
               // GennadyK Book Update functionality ->
                self.downloadedBookUpdated= self.bookUpdated;
                // Write bookUpdated.property to file
                NSURL *URL = (NSURL*)[NSString stringWithFormat:@"%@/%@", destinationPath, @"bookUpdated.property"];
                NSString *string = self.bookUpdated;
                NSError *error;
                BOOL ok = [string writeToURL:URL atomically:YES
                                    encoding:NSUTF8StringEncoding error:&error];
                if (!ok) {
                    NSLog(@"Error writing file at %@\n%@", URL, [error localizedFailureReason]);
                }
               // <- GennadyK Book Update functionality

2. Also add in the initWithIssueData function:
        self.bookUpdated= issueData[@"book_updated"];

3. Find:
- (NSString*)nkIssueContentStatusToString:(NKIssueContentStatus) contentStatus{
    ...
        return @"downloaded";
    }
    return @"";
}

and insert this code just before << return @"downloaded"; >> line:
        // GennadyK Book Update functionality ->
        // Read bookUpdated.property from file
        NSString* path = [NSString stringWithFormat:@"%@/%@", self.path, @"bookUpdated.property"];
        NSError* error = nil;
        self.downloadedBookUpdated= [NSString stringWithContentsOfFile:path
                                                      encoding:NSUTF8StringEncoding
                                                         error:&error];
        if(error) {
            NSLog(@"ERROR while loading from file: %@", error);
        }
           // <- GennadyK Book Update functionality

4. And as we added two new fields to issue data, bookUpdated and downloadedBookUpdated, we need to add those in BKRIssue.h:
@property (nonatomic, copy) NSString *date;
@property (nonatomic, copy) NSString *bookUpdated;
@property (nonatomic, copy) NSString *downloadedBookUpdated;

5. In BKRIssueCell.m find archiveButtonPressed function:

- (IBAction)archiveButtonPressed:(id)sender {
    UIAlertView *updateAlert = [[UIAlertView alloc]
    …
}

and after it add this new function:

- (IBAction)updateButtonPressed:(id)sender {
    BKRReachability *reach = [BKRReachability reachabilityWithHostname:@"www.google.com"]; // add to imports above: #import "BKRReachability.h"
    if ([reach isReachable]) { // allow update only if the internet is ON
        [self.delegate issueCell:self requestsArchiveActionForIssue:self.issue];
        [self.delegate issueCell:self requestsDownloadActionForIssue:self.issue];
    } else {
        UIAlertView *updateAlert = [[UIAlertView alloc] initWithTitle:NSLocalizedString(@"INTERNET_CONNECTION_UNAVAILABLE_TITLE", nil)
                                                              message:NSLocalizedString(@"INTERNET_CONNECTION_UNAVAILABLE_MESSAGE", nil)
                                                             delegate:nil
                                                    cancelButtonTitle:NSLocalizedString(@"INTERNET_CONNECTION_UNAVAILABLE_CLOSE", nil)
                                                    otherButtonTitles:nil];
        [updateAlert show];
    }
}


Add to imports: #import "BKRReachability.h"


Create and assign your "Update" button to updateButtonPressed inside the storyboard the same way it's done for "Archive" button:
Create "Update" button and then:
1) choose the "Update" button in the left components panel;
2) in the right “Utilities” panel choose the far right icon for “Connections inspector”;
3) open “Assistant editor” (icon with the two crossed rings) and find BKRIssueCell.m > updateButtonPressed function;
3) in the “Connections inspector” > “Sent Events” find “Touch Up Inside”, click on the round icon to the right (image will change to the plus) and drag the mouse to the updateButtonPressed function inside “Assistant editor” panel;
4) verify that updateButtonPressed function is added to “Touch Up Inside” event;
5) find in “Assistant editor” BKRIssueCell.h > @property (nonatomic, strong) IBOutlet UIButton *updateButton;
6) drag with mouse “+” from “Connections inspector” > “Referencing Outlets” > “New Referencing Outlet”to that property;
7) verify that updateButton property is added to “Referencing Outlets”.


6.  In BKRIssueCell.m find:
    } else if ([status isEqualToString:@"downloaded"]) {
        [self.actionButton setTitle:NSLocalizedString(@"ACTION_DOWNLOADED_TEXT", nil) forState:UIControlStateNormal];
        [self.spinner stopAnimating];
        self.actionButton.hidden  = NO;
        self.archiveButton.hidden = NO;

replace it with:

    } else if ([status isEqualToString:@"downloaded"]) {
        [self.actionButton setTitle:NSLocalizedString(@"ACTION_DOWNLOADED_TEXT", nil) forState:UIControlStateNormal];
        [self.spinner stopAnimating];
        self.actionButton.hidden  = NO;
        self.archiveButton.hidden = NO;
        if ([self.issue.bookUpdated isEqualToString:self.issue.downloadedBookUpdated] || (!self.issue.bookUpdated && !self.issue.downloadedBookUpdated))
            self.updateButton.hidden = YES;
        else
            self.updateButton.hidden = NO;

For the rest of statuses (10 more) set it to "YES":
        self.archiveButton.hidden = YES;
        self.updateButton.hidden = YES;


7. BKRIssueCell.h add these two lines accordingly:
@property (nonatomic, strong) IBOutlet UIButton *updateButton;

- (IBAction)updateButtonPressed:(id)sender;



The end.  Please let me know if I missed anything. Everybody is welcome to enhance parts/whole solution. Thanks.
