### ISSUE TITLE
Adding the category thing to the Cloud console

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#547]
Hi friends!
Is there a tutorial for this somewhere ? 
Going back to manual upload of manifest because of the seems a setback, while the cloud console works marvelously smooth...

Or is there a place are I can find Baker-fluent developers that I could hire to do it ?

**Comment by GennadyK** [comment]
Hi NemoMag,
Book categories on the shelf are not working in the latest baker-master. Use this one instead:
https://github.com/bakerframework/baker/issues/445#issuecomment-111429640

**Comment by GennadyK** [comment]
BTW you don't need any Baker-fluent developer, your best contact would be developer of the Cloud Console AKA MagRocket server/api - Andrew Krowczyk from nin9creative: andrew@nin9creative.com
And if he is busy and has no time and you still want to develop Cloud Console categories, I might help with adding this feature. Thanks

**Comment by NemoMag** [comment]
Hi There! Any input or contact of eve that could do this for me. Ready to pay for it.

**Comment by shutterflypro** [comment]
@NemoMag I have been able to add this to the cloud console however the code in the iOS app is having trouble processing this.  I am working on a solution and will update you once I get to the bottom of it.

Have you had any luck with it?
