### ISSUE TITLE
Link to the specific page of the other book on the shelf

### ISSUE THREAD

**Issue by GennadyK** [bakerframework/baker#548]
Hi guys,
We needed this functionality, so I added it using book:// links. So the link is defined as:
book://www.website.com/baker-files/book-name/3/p03.html
where
3 - the number of the page in the book.json:
    ...
    "contents": [
        "p01.html",
        "p02.html",
        "p03.html",
        ...
p03.html - html file to open, could be different than the one defined for the page 3.

If the book is not yet downloaded, then you are switched to shelf and the book gets downloaded and then if you tap READ it will be opened at book-name/3/p03.html.
If the book is already on the device then it will be opened at book-name/3/p03.html right away.
Let me know if anyone is interested in this and I'll add the code here.

Thanks,
Gennady

**Comment by corsa** [comment]
This would definitely be handy.

**Comment by GennadyK** [comment]
Here you go!
Global variables were used for simplicity. Add code in 5 places:

1) In the BKRBookViewController.h define variables right after all imports:
// External book links ->
extern int insideBookPageNumber; 
extern NSString *insideBookLink; 
// <- External book links

2) In the BKRBookViewController.m initialize variables right before the
@implementation BKRBookViewController
line:
// External book links ->
int insideBookPageNumber= 0;
NSString *insideBookLink = @"";
// <- External book links

3) In the BKRBookViewController.m inside the loadBookWithBookPath function add the code to set current page from insideBookPageNumber. Find
lastPageViewed = [bookStatus.page intValue];
And replace it with:
    // External book links ->
    int lastPageViewed = 0;
    if (insideBookPageNumber != 0) {
        lastPageViewed =insideBookPageNumber; // replacing lastPageViewed number with the one from the link
        insideBookPageNumber= 0; // reset used page number
    }
    else
        lastPageViewed = [bookStatus.page intValue]; // standard page processing
    // <- External book links

4) In the BKRBookViewController.m inside the loadWebView function add the code to set html page name from insideBookLink:
- (BOOL)loadWebView:(UIWebView*)webView withPage:(int)page {
    
    NSString *path = [NSString stringWithString:pages[page - 1]];
    
    // External book links ->
    if ( [insideBookLink length] != 0 ) { // build path to the insideBookLink
        NSURL *insideBookLinkPathPart=[[NSURL URLWithString:path] URLByDeletingLastPathComponent];
        NSString *insidePath= [insideBookLinkPathPart absoluteString];
        insidePath=[insidePath stringByAppendingString:insideBookLink];
        if ([[NSFileManager defaultManager] fileExistsAtPath:insidePath])
            path= insidePath; // only modify path if file exists
        insideBookLink=@""; // reset it to empty
    }
    // <- External book links

5) In the BKRBookViewController.m change the handleBookProtocol function as per:

- (void)handleBookProtocol:(NSURL *)url
{
    // ****** Handle: book://
    NSLog(@"[BakerView]     Page is a link with scheme book:// --> download new book");
    
    // External book links ->
    if ([[url pathExtension] isEqualToString:@"html"]) {
        insideBookLink= [[url lastPathComponent] stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding]; // get the page.html
        url = [url URLByDeletingLastPathComponent];
        insideBookPageNumber = [[url lastPathComponent] lowercaseString].intValue; // get the page number
        url = [url URLByDeletingLastPathComponent];
    }
    // <- External book links
    
    NSString *bookName = [[url lastPathComponent] stringByReplacingOccurrencesOfString:@".hpub" withString:@""];
    NSDictionary *userInfo = @{@"ID": bookName};
    
    [[NSNotificationCenter defaultCenter] postNotificationName:@"notification_book_protocol" object:nil userInfo:userInfo];
}

The end. Now create the link to another book and test it.

**Comment by corsa** [comment]
Thanks!
