### ISSUE TITLE
Apple "Free Subscription" option gone

### ISSUE THREAD

**Issue by corsa** [bakerframework/baker#549]
It looks like Apple is no longer allowing the "Free Subscriptions" in-app purchase type. Also, it doesn't seem like you can set an Auto-Renewable Subscription to have a price of 0.

Also, since Baker uses the Newsstand Kit, you can't submit a Baker app for review without at least one subscription. (In previous Baker apps that needed to have free publications, I always used the Free Subscription option.)

Any ideas on how to use Baker for a publication with all free issues?

**Comment by quba88** [comment]
I suggest to remove newsstand kit, and manually download issues.

**Comment by mbjacket81** [comment]
I'm having the same issue so since I need free subscriptions and the magazine is updated monthly, I'm having issues submitting my app to Apple because I have an in-app purchase product that I had to create in order to submit the app and that product is not referenced within the app.  In other words, everything I've tried isn't working...

**Comment by whohitme** [comment]
Hello there, @quba88 could you please explain what you mean by manually downloading issues? I've been playing around with this, but I haven't been able to get anything to work successfully without using Newsstand and Apple is only allowing paid options for Newsstand. Any help or direction? Thank you

**Comment by quba88** [comment]
Hi, @whohitme I'm use NSURLSession (NSURLConnection is deprecated), You can use other libraries i.e. AFNetworking. 
All what you need is replace code in BKRIssue.m/.h files.

**Comment by whohitme** [comment]
@quba88 thanks for your response. I've been looking into NSURLSession and trying to learn what I need to do. So, your app is no longer being submitted as Newsstand in your info.plist file? I don't know Obj-C/Swift, so I'm having a hard time, would you be able to share any code or example of what I need to do? It seems like a pretty big re-coding to get this to work. Thank you.

**Comment by Gamer2000** [comment]
@quba88 .Please share code .How and  where replace code

**Comment by quba88** [comment]
@Gamer2000, @whohitme sorry, I don't have enough time to response
@whohitme Yes I forgot, You must have to change info.plist file :)
 
My tips for you:

in info.plist
UINewsstandApp seto to NO
UINewsstandIcon remove UINewsstandIcon
in capabilities uncheck newsstand download
//Your app no longer uses Newststand  and all newsstand push not working

remove from project  NewsstandKit.framework (method, class etc.)

in BKRIssue.h/.m remove NSURLConnectionDownloadDelegate methods, deprecated as I said

in .m file

 path ==  your path where is saved issue 

**Download mechanism:**
_if You using NSURLSession:_ 
add NSURLSessionDownloadDelegate
init NSURLSession by using  sessionWithConfigurationdelegate:delegateQueue:
and start download using NSURLSessionDownloadTask 

implements delegate methods
URLSession: downloadTask: didWriteData: totalBytesWritten: totalBytesExpectedToWrite:// update progress 
URLSession: downloadTask: didFinishDownloadingToURL: // download finished (unzip)
URLSession: task: didCompleteWithError: // handle error

_When You use AFNetworking all above line you move in one method with blocks_

in getStatus //support status of issue manually

in BKRIssuesManager.m  updateNewsstandIssuesList remove no more newsstand icons

remove subscription sheet from your app

**Comment by whohitme** [comment]
Thank you @quba88 for giving out some tips. Forgive me, I don't know how to work in ObjC very well. I'm still struggling to figure out which parts to leave or not. For the BKRIussue.m file are we removing all methods? It seems like everything refers to Newskit in there, but I'm unsure.
For the status updating, are you still using the getStatus method? I'm confused about how to send the status and progress.
Will this still work with multiple issues listed in a json shelf file? Would it be possible to see a copy of your BKRIssue.m file?
This is what I have so far:
`-(void)download
{
    NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
    NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfiguration delegate:self delegateQueue:nil];
    NSURLSessionDownloadTask *downloadTask = [session downloadTaskWithURL:self.url];
    [downloadTask resume];

}
- (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didFinishDownloadingToURL:(NSURL *)location {
    NSData *data = [NSData dataWithContentsOfURL:location];
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.delegate issue:self downloadStarted:nil];
        [self unpackAssetDownload:data toURL:location];
    });
}

- (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didResumeAtOffset:(int64_t)fileOffset expectedTotalBytes:(int64_t)expectedTotalBytes {
    
}

- (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didWriteData:(long long)bytesWritten totalBytesWritten:(long long)totalBytesWritten totalBytesExpectedToWrite:(long long)totalBytesExpectedToWrite {
    NSDictionary *userInfo = @{@"totalBytesWritten": @(totalBytesWritten), @"expectedTotalBytes": @(totalBytesExpectedToWrite)};
    if(self.delegate) {
        [self.delegate issue:self downloadProgressing:userInfo];
    }
}

- (void)unpackAssetDownload:(NSData*)issueAssetDownload toURL:(NSURL*)destinationURL {
    UIApplication *application = [UIApplication sharedApplication];
    NSString *destinationPath  = [destinationURL path];
    
    __block UIBackgroundTaskIdentifier backgroundTask = [application beginBackgroundTaskWithExpirationHandler:^{
        [application endBackgroundTask:backgroundTask];
        backgroundTask = UIBackgroundTaskInvalid;
    }];
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSLog(@"[BakerShelf] Newsstand - File is being unzipped to %@", destinationPath);
        BOOL unzipSuccessful = NO;
        unzipSuccessful = [BKRZipArchive unzipFileAtPath:[destinationURL path] toDestination:destinationPath];
        if (!unzipSuccessful) {
            NSLog(@"[BakerShelf] Newsstand - Unable to unzip file: %@. The file may not be a valid HPUB archive.", [destinationURL path]);
            dispatch_async(dispatch_get_main_queue(), ^(void) {
                if(self.delegate) {
                    [self.delegate issue:self unzipError:nil];
                }
            });
        }
        
        NSLog(@"[BakerShelf] Newsstand - Removing temporary downloaded file %@", [destinationURL path]);
        NSFileManager *fileMgr = [NSFileManager defaultManager];
        NSError *error;
        if ([fileMgr removeItemAtPath:[destinationURL path] error:&error] != YES){
            NSLog(@"[BakerShelf] Newsstand - Unable to delete file: %@", [error localizedDescription]);
        }
        
        if (unzipSuccessful) {
            // Notification and UI update have to be handled on the main thread
            dispatch_async(dispatch_get_main_queue(), ^(void) {
                if(self.delegate) {
                    [self.delegate issue:self downloadFinished:nil];
                }
            });
        }
        
        [application endBackgroundTask:backgroundTask];
        backgroundTask = UIBackgroundTaskInvalid;
    });
}
`
Thanks for any help!

**Comment by whohitme** [comment]
Has anyone else tried their hand at this? I feel like I'm close, but I think one of the main issues is with getting the file to download and unzip properly, and I can't seem to update the status in both the log and UI, which I think is also part of the problem.
Right now it seems to be able to grab the hpub file and save in a temp folder, but then when it tries to unzip the file it gives me an error.
Any ideas? @quba88

**Comment by whohitme** [comment]
If anyone is interested, I believe that I have a working version for displaying free issues. I have not yet submitted to Apple, but all testing is looking good. I'm not sure how best to share this version, but I'm happy to help if anyone else is interested.

**Comment by mbjacket81** [comment]
Hi @whohitme, I'm really interested if you have a version that works with free issues.  I have a magazine app (completely free) but I'm having trouble because the free subscription option is gone.  If you have a working solution, I'd love to see it.  Thanks!

**Comment by whohitme** [comment]
@mbjacket81 I'll try to create a post that goes through the process and post the coding changes for the BKRIssues.m file. I'm no Objective-C coder, so I just kind of fumbled my way through it, but I have a working app that is in the app store right now.

**Comment by petesavva** [comment]
Hi guys is there an update to this thread? thanks

**Comment by GennadyK** [comment]
@whohitme   Hi, we would really appreciate it if you could, please, post your version that eliminates use of the Newsstand Kit library. Thank you!

**Comment by GennadyK** [comment]
This is related issue as it is about download part of Newsstand framework: https://github.com/bakerframework/baker/issues/571
