### ISSUE TITLE
iPhone7 iOS 10.1.1 cannot double tap to return to navigation bar

### ISSUE THREAD

**Issue by plippard** [bakerframework/baker#553]
I have downloaded latest baker master as of today and I am seeing the same issue as I experienced with baker 4.3.   When viewing a book if I double tap to return to the navigation bar .... nothing happens on a real device.   It works fine on a simulator.  The problem only exhibits itself on a real iPhone7.   

iOS 10.1.1 on an iPad also works fine.

Has anyone seen this problem only on an iPhone 7 ?

In reviewing the outstanding issues, I was hopeful that issue # 541 would resolve this.... however as I said above I downloaded the latest master today and the problem still persists.

HELP !!!!

**Comment by quba88** [comment]
try this https://github.com/bakerframework/baker/issues/508

**Comment by plippard** [comment]
Thanks...# 508 appears to now work fine.
