### ISSUE TITLE
Always on first page when relaunch the app

### ISSUE THREAD

**Issue by kelvinlee79** [bakerframework/baker#554]
Hi, is there anyway to set the Standalone app to always start on the first page during every relaunch of the app rather than on the last visited page? Please advise. Thank you!

**Comment by GennadyK** [comment]
In the BKRBookViewController.m inside the loadBookWithBookPath function find:
`int lastPageViewed = [bookStatus.page intValue];`
And replace [bookStatus.page intValue] with 1:
`int lastPageViewed = 1;`

**Comment by kelvinlee79** [comment]
It's working. Thank you so much @GennadyK!
