### ISSUE TITLE
offline reading

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#558]
Bizzarely, when the internet connection is not working, the user do get prompted with the "No internet Connection. Some functionnalities requires an internet connection.. etc" alert.
BUT THEN, the shelf remains empty and no book appear, nor can be read, even those already downloaded and subsequently present within the App/iPad.
How come?!
I'm using the latest version of Baker, and iOS 10.2 on iPad Air.
But surprisingly, at the same time the problem  does not happen on my iPhone with iOS.

**Comment by NemoMag** [comment]
It seems that it happens when the hosting server does not answer.

**Comment by GennadyK** [comment]
Lucky you guys, I just fixed this bug a few days ago :)
https://github.com/bakerframework/baker/issues/35#issuecomment-265472125

**Comment by NemoMag** [comment]
Just implemented your code but then 
![capture d ecran 2016-12-20 a 11 28 11](https://cloud.githubusercontent.com/assets/8971320/21347121/a23d7090-c6a7-11e6-968c-46cde024bcd4.png)
the build failed

**Comment by GennadyK** [comment]
if (error) {
        NSLog(@"[ERROR] Failed GET request to %@: %@", [request URL], [error localizedDescription]);
        return nil;
    } else if ([response statusCode] == 200) {
    ^
    You are missing this closing "}"

**Comment by NemoMag** [comment]
Yes, right!
But, sorry to keep on asking ;-), but there's still a syntax problem that makes the build fail : 
![capture d ecran 2016-12-20 a 21 31 48](https://cloud.githubusercontent.com/assets/8971320/21366828/cb9c78ec-c6fb-11e6-858d-e9287ebeafd0.png)

**Comment by NemoMag** [comment]
Then i tried to correct this like this but... boom
![capture d ecran 2016-12-20 a 21 34 21](https://cloud.githubusercontent.com/assets/8971320/21366914/3e8122cc-c6fc-11e6-913d-653197a24d23.png)
![capture d ecran 2016-12-20 a 21 34 15](https://cloud.githubusercontent.com/assets/8971320/21366918/40955bc8-c6fc-11e6-98cb-d8b61abbe471.png)

**Comment by GennadyK** [comment]
Sorry, this line didn't copied properly:
if ([dataString rangeOfString:@""name":"].location == NSNotFound) {

Should be like below. I also attached the whole BKRBakerAPI.m.zip to the original post:
`if ([dataString rangeOfString:@"\"name\":"].location == NSNotFound) {`

**Comment by NemoMag** [comment]
This is quite a nasty resident bug ;-)
I used your new BKRBakerAPI.m and the app remains stuck loading...
![capture d ecran 2016-12-21 a 10 09 29](https://cloud.githubusercontent.com/assets/8971320/21383538/8c530c76-c766-11e6-985f-40dcfe7ef42d.png)

**Comment by GennadyK** [comment]
There is nothing wrong there. You unknowingly set breakpoint on that line. Right-click on that bluish arrow at the very beginning of the line and choose "Delete Breakpoint". To understand the term read this:
http://jeffreysambells.com/2014/01/14/using-breakpoints-in-xcode
