### ISSUE TITLE
Red alert! Can't upload app to AppStore : Storyboard missing

### ISSUE THREAD

**Issue by NemoMag** [bakerframework/baker#559]
Hi,
My archive upload of a new baker app (v.4.3) just failed with an ERROR ITMS-90475 : "invalid bundle. iPad multitasking support requires launch story board in bundle."
First time it happens to me. 
WTF ? ;-)
I'am using Xcode 8.2.1., with a baker 4.3 that till then worked perfectly.
And I did entered as usual all the launch images required in the asset catalogue.
Please help!
![capture d ecran 2017-02-02 a 15 36 14](https://cloud.githubusercontent.com/assets/8971320/22554001/e815fcac-e95e-11e6-8723-e05b29a4dccb.png)

**Comment by GennadyK** [comment]
stackoverflow.com/questions/32557783/invalid-bundle-error-requires-launch-storyboard#32563605
