### ISSUE TITLE
BakerFramework DEAD

### ISSUE THREAD

**Issue by shutterflypro** [bakerframework/baker#563]
So is the BakerFramework dead....

Am having issues with launching new mag app on the new iOS would love to know if anyone out there is having the issues and fixed it?

**Comment by GennadyK** [comment]
The app works well for us and does what we need from it.
The project is just in the slow/passive development mode :)   And it's done now by MagLoft's team mainly. So I would start (and this is what we actually did) from this version:
`## [4.3.pr_476] - Jun 11, 2015`
`### Version from which development is started`
`https://github.com/bakerframework/baker/issues/445`
Then whatever issue you have you search/ask here or google it.
Good luck with your development!

**Comment by shutterflypro** [comment]
Thanks @GennadyK appreciate the response.  here is the issue I am having.  The book is getting purchased just fine.  The download button shows and everything, however that is where it stops.  In the console it just repeats the issue has been purchased.  When I do a trace through the code it is getting the proper URL and I can even copy and paste that into a browser and the download begins.  However in the app it will not begin the download it just repeats that the issue has been purchased.

Any ideas or fixes would be great.

The whole reason for the thread title was because I have gone through all of the reported issues and their fixes to no avail.  And it looks like nothing has been added or updated to this repository in years now.

@nicholasmartin @nin9creative Any ideas?  I am thinking this is new iOS issue but I know someone has come across this and fixed it.

**Comment by nicholasmartin** [comment]
Hi Raymond (@shutterflypro), it's just like @GennadyK mentioned. Updates to the baker Framework tend to come in waves. There haven't been a lot lately that is correct. Here at MagLoft we have been developing heavily on our backend servers and publishing portal to accommodate the many requests we get from customers. This has required that we also customize the app versions heavily towards our backend setup which makes it very hard for us to submit updates to the Baker version that runs on Baker Cloud.

We are constantly revisiting the Baker Framework and discuss internally what options we have to contribute. We are a team of 6 full time MagLoft team members and we are flooded with work. I had no idea the amount of investment we would all be making when entering this industry. It's of course very exciting!

Our backend and apps are extremely tightly connected and updated on a daily basis. And we still have new feature requests and issues arising weekly that we need to debug and develop. It would be an impossible task for us to properly support an open source project where there are so many other factors involved.

Andrew @nin9creative has invested an incredible amount of time and resources in Baker Framework with help from a few dedicated others over time. I really respect that as I have first hand experience with running a digital publishing SaaS and know how challenging it is! So a big KUDOS to Andrew for all he has done and who knows what tricks he might pull out of the bag :)

**Comment by shutterflypro** [comment]
@nicholasmartin Thanks for the reply.  As you know I have been with this project for years myself and yes mucho kudos goes out to @nin9creative Andrew.  Not real sure how he managed to make it as great as it is.  I also remember when the MagLoft team was much smaller than it is now.  Congrats on that by the way.

I am figuring out that a majority of my problems are a lack of knowledge of the GitHub system.  For instance I started with what I thought was the newest codebase from the code section of this area however after following the a link in @GennadyK response I got a new updated codebase and my problem is no longer an issue.  It did show me an issue with my conversion software though so that is another thing to tackle.

@nicholasmartin now I understand you guys are super busy, but do you think there is any chance you could help get the android version of this repository working.  (If it is can you just point me in the right direction :) I know very little about Android.)

**Comment by GennadyK** [comment]
Hi Raymond,
In our case all the books are free and once download ("GET") button is pressed the book gets downloaded from folder on the server. We just use shelf.json and folder on the server for the book storage (with no backend server). So my guess, you just need a bit more time to dig deeper. And please either create new issue or change subject for this bug. Do you use 4.3.pr_476 or any other version of the code?

**Comment by GennadyK** [comment]
BTW, there are still some bugs in 4.3.pr_476, that were fixed before we went into production, this is the important one:
https://github.com/bakerframework/baker/issues/35

**Comment by whohitme** [comment]
@GennadyK I'm trying to create the same type of environment (all free material for download), but with the changes that Apple has made you can no longer select a free subscription option, so I'm having trouble once I submit to Apple. I also started with the above codebase you linked to. Do you have any suggestions to get me started? Thank you!

**Comment by GennadyK** [comment]
@whohitme Hi, sorry that I can't help you as we are using it outside of the app store. I noticed you were posting in the right issue - https://github.com/bakerframework/baker/issues/549. You may ask quba88 to share his/her code (BKRIssue.m/.h files) privately if not publicly, or try to do it by yourself.

**Comment by nin9creative** [comment]
Hey everyone...  Sorry that things have been stagnant here for so long.  My day job/family workload has been consuming 110% of my available cycles for a long time now and I haven't had as much time to continue to work on Baker.

That being said, if there is anyone that has some time and motivation to continue to help push things forward - please let me know and I'd be happy to figure out how to get things going again.

Thanks!
Andrew

**Comment by shutterflypro** [comment]
@nin9creative Great to hear you chime in and glad you are still around.  I love baker and have for years as you know and I hate to see it stagnant like it is right now.

What can I do to help!

**Comment by GennadyK** [comment]
Hi guys,
Just a few thoughts about Baker's future:
It's just the time when Baker got into maintenance stage (very limited new features, mostly bugs fixes) of it's life. As the new way for digital publishing is the "article-based" vs "issue-based" publishing. But Baker is a great platform (thanks to all who invested their time and money) and still could be used by many. And hopefully some of us will be willing to share the code (even it is not perfect and even this still requires of extra time invested) for the things we implemented, e.g. replaced Newsstand kit with NSURLSession to download books to fix the problem of free subscription. And this is just within the Open Source spirit - to give back to the community.
One thing Andrew can still help with - is adding category to the Cloud console or just providing 2 older Cloud console versions with one additional field added in-between or any additional info/resources that will help to add category to it.
Also in some cases a few interested parties may chip in some funds and advertise bounty for the feature they would like to see added.
And Raymond can assume project coordinator's role if no one else (MagLoft guys?) is interested/has time for it.

Thanks

**Comment by shutterflypro** [comment]
I would gladly help where I can.

**Comment by whohitme** [comment]
I'm also happy to help somehow. My main concern right now is the ability to provide free editions by downloading directly from the server.

**Comment by LuxViz** [comment]
Hello @shutterflypro (and anyone else who might benefit from this. Raymond, you sent me a message asking for the Android version of Baker, so I archived what I THINK is the last version we had been using a couple of years ago, and uploaded it to my DropBox account. I also uploaded a complete (I think) standalone Android app we created, in case that can be of assistance.

https://www.dropbox.com/sh/jum4idyq36icg6h/AACLZSm_Zg4wTVZpQOME8ncTa?dl=0

My programmer, who was doing all the low-level coding for these apps left my company about 2 years ago and I have not done any other Android apps since then. So my remembrance of how things “worked” is very sketchy. But, hopefully this archives will be helpful for you.

Best wishes,
Rick

**Comment by shutterflypro** [comment]
@luxviz  Thank you so much for reaching back out to this community and providing way assistance you have.  I will go through the code and see if I can get it to work and what state it is in.

Now how much work have you done that you would be willing to share concerning the html & css that comprises the main parts of the HPUB?  Would love to get a hold of those and I am sure so would the baker community.

Raymond

**Comment by LuxViz** [comment]
Hi again @shutterflypro -  ALL the files (css, js, html etc) have already been included in the Android app archive. There is even the Android Studio project file. So, you should be able to use that archive to produce a fully functional Android version of our villa app for Chandra Villas in Bali. If you'd like to download the app, here are the links:

Android - https://play.google.com/store/apps/details?id=com.luxviz.chandra
iOS - https://itunes.apple.com/us/app/chandra-luxury-villas/id986688817?ls=1&mt=8

**Comment by shutterflypro** [comment]
@LuxViz Thanks Rich, I will go through them and see what all is there.  Once again thanks for extending this information to the community. (And Me :))

**Comment by nin9creative** [comment]
Raymond, let's email offline to figure out the best way to have you do this...
I can grant you admin rights on the Baker Framework GitHub repo, and potentially also on the website if you want to update information / blog post etc.
Andrew

**Comment by ahvink** [comment]
I read a lot of good intentions here, but is there progress of some sort on the framework or have people moved on to other solutions?
If so what are some of the alternatives ?

**Comment by GennadyK** [comment]
Try it and see if it covers your needs either as is or with a bit of development. Some of alternatives are MagLoft and Twixl (has also newly developed article-based publication), both started from Baker framework.
