### ISSUE TITLE
Apple rejects the app

### ISSUE THREAD

**Issue by webcarp** [bakerframework/baker#565]
Hi. I have a recent problem, now that I want to update the app.
Apple is becoming more demanding and intolerant!
The problem is how the "info" button page is displayed on the baker shelf page.
On the iphone, this page looks like this:
![baker-iphone](https://user-images.githubusercontent.com/6560159/28659267-25e8ef7e-72af-11e7-8886-f220365beacc.PNG)
But on the ipad, this page is displayed in a pop-up window:
![baker-ipad](https://user-images.githubusercontent.com/6560159/28659274-2fe90644-72af-11e7-8087-9e443adbcf76.png)
The answer from Apple is:
_

> Specifically, the Auto-Renewable subscription information is shown within a popup or custom modal alert which is not in compliance. Adding the information to a popup or custom modal alert is not sufficient; the information must also be listed somewhere within the app itself, and it must be displayed clearly and conspicuously.

_ 
Please, does anyone know how I can do so that on the ipad this page will be displayed as on the iphone?
Thank you
(Pardon in advance, translated with Google Translator)

**Comment by webschnecke** [comment]
Apple rejected me, too ;-( Here is the Info from Apple: 

> Guideline 4.2 - Design - Minimum Functionality
> **Your app is primarily a book and is therefore not appropriate for the App Store.**
> 
> Next Steps
> 
> Books should be submitted to iBooks Store. To work with Apple on iBooks distribution, you should first verify that your content meets the following requirements:
> 
> - ISBNs are required for all paid titles you intend to distribute
> - Is in either:
> - EPUB format, passing EpubCheck 1.0.5	
> - Multi-Touch format, created by iBooks Author
> 
> Resources
> 
> To obtain an ISBN for your content and learn more about ISBNs, please see US ISBN Agency. Then complete the iTunes Connect Online Application.
> 
> Note: An ISBN is not required if you have a free book agreement and choose to offer your book free in iBooks.
> 
> Visit Books Partner Search for information on working with a content partner.

**Comment by GennadyK** [comment]
Hi webschnecke,
> Guideline 4.2 - Design - Minimum Functionality
> Your app is primarily a book and is therefore not appropriate for the App Store.
- I assume you have the app with the single built-in HTML book (standalone app). Your app/book needs to be one of these two types to fix this:
1) Single built-in HTML book must have interactive elements/videos that are not possible to have in the iBooks format;
2) Use app in multi-book subscription format - with intension of publishing second book at some point (or never :).
