### ISSUE TITLE
Creating html 5 Pages 

### ISSUE THREAD

**Issue by Graemezee** [bakerframework/baker#566]
I am very new to the  the bakerframwork and have been looking  for  responsive templates   to get started  on a magazine design  I came across the Laker compendium  which seems like a good starting  point but kind of wondered  why there was  nothing based on bootstrap is there any practical reason why can you not design your pages based on the bootstrap framework are there any hpub templates or  is it just a case of creating your own,    or could you base one on the many bootstrap templates available?

**Comment by GennadyK** [comment]
You may use anything you like and what does the job, for some books we even
use screen-size images for specific device. We also use together different
js libraries. It's the same freedom as for a website development.

**Comment by Graemezee** [comment]
Thanks  much appreciated
