### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by daveshickey** [bakerframework/baker#568]
Hi,

Not sure if anyone has ran into this, but I keep getting the same two errors when I test my project in Xcode:

<img width="689" alt="errors" src="https://user-images.githubusercontent.com/41960185/44875469-a806c580-ac74-11e8-9632-79b9df36a4cf.png">

Any thoughts?

**Comment by GennadyK** [comment]
Hi,
Just one question: Do you use 4.3.pr_476 or any other version of the code? I believe that 4.3.pr_476 is the latest working code: https://github.com/bakerframework/baker/pull/476

**Comment by daveshickey** [comment]
Hi,

Apologies for the delay in reply--I'm just seeing this now. This is probably really obvious, but I couldn't figure out where to download that version. I was using 4.3, which is dated to 11/12/2014.

**Comment by GennadyK** [comment]
It's in here:
https://github.com/bakerframework/baker/issues/445
Find this line and get the zip:
Please give it a try using #476 ... (Download Source ZIP)
